import { useEffect, useRef, useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import './InnovationLab.css';

const modules = [['rag','Semantic RAG','Ranked document chunks and citations'],['agents','Agent Builder','Reusable experts with tools'],['fallback','Model Fallback','Automatic provider recovery'],['multimodal','Multimodal','Voice, files, images, and prompts'],['evals','Evaluation Lab','Multi-model quality benchmarks']];
const models = ['gpt','claude','gemini','deepseek','llama'];
async function api(url, options={}){const response=await fetch(url,{credentials:'include',...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Request failed');return data;}
async function ask(model,prompt,fallbackEnabled=true){const started=performance.now();const response=await fetch('/api/chat',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'user',text:prompt}],temporary:true,fallbackEnabled})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.message||`${model} failed`);}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',text='',fallback=null;while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const events=buffer.replaceAll('\r\n','\n').split('\n\n');buffer=events.pop()||'';events.forEach(raw=>{const line=raw.split('\n').find(item=>item.startsWith('data: '));if(!line||line.slice(6)==='[DONE]')return;const event=JSON.parse(line.slice(6));if(event.text)text+=event.text;if(event.fallback)fallback=event.actualModel;});if(done)break;}return{text,fallback,latency:Math.round(performance.now()-started)};}

export default function InnovationLab(){
 const saved=sessionStorage.getItem('allmodelai_user'),user=saved?JSON.parse(saved):null,navigate=useNavigate(),picker=useRef(null);
 const[active,setActive]=useState('rag'),[error,setError]=useState(''),[documents,setDocuments]=useState([]),[doc,setDoc]=useState({name:'',content:''}),[query,setQuery]=useState(''),[results,setResults]=useState([]);
 const[agents,setAgents]=useState([]),[agent,setAgent]=useState({name:'',model:'smart',instructions:'',tools:['knowledge','fallback']});
 const[fallbackEnabled,setFallbackEnabled]=useState(()=>localStorage.getItem('allmodelai_fallback')!=='false'),[fallbackPrompt,setFallbackPrompt]=useState(''),[fallbackResult,setFallbackResult]=useState(null),[busy,setBusy]=useState(false);
 const[attachment,setAttachment]=useState(null),[multiPrompt,setMultiPrompt]=useState(''),[listening,setListening]=useState(false);
 const[evalPrompt,setEvalPrompt]=useState(''),[evalModels,setEvalModels]=useState(['gpt','claude','gemini']),[evalResults,setEvalResults]=useState([]),[evaluating,setEvaluating]=useState(false);
 useEffect(()=>{if(!user?.email)return;const type=active==='rag'?'document':active==='agents'?'agent':null;if(type)api(`/api/workspace?type=${type}`).then(type==='document'?setDocuments:setAgents).catch(e=>setError(e.message));},[active,user?.email]);
 if(!user)return <Navigate to="/" replace/>;
 const saveDocument=async event=>{event.preventDefault();try{const created=await api('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'document',...doc})});setDocuments(items=>[created,...items]);setDoc({name:'',content:''});}catch(e){setError(e.message);}};
 const importFile=async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2e6)return setError('File must be smaller than 2 MB.');if(!/\.(txt|md|csv|json|js|jsx|ts|tsx|py|html|css)$/i.test(file.name))return setError('Paste extracted PDF or DOCX text. Text and code files can be indexed directly.');setDoc({name:file.name,content:(await file.text()).slice(0,100000)});};
 const search=async()=>{try{const data=await api('/api/knowledge/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,limit:8})});setResults(data.results||[]);}catch(e){setError(e.message);}};
 const saveAgent=async event=>{event.preventDefault();try{const created=await api('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'agent',...agent})});setAgents(items=>[created,...items]);setAgent({name:'',model:'smart',instructions:'',tools:['knowledge','fallback']});}catch(e){setError(e.message);}};
 const launchAgent=item=>{localStorage.setItem('allmodelai_system_instructions',item.instructions||'');navigate(`/chat?model=${item.model||'smart'}`,{state:{starterPrompt:`You are running as ${item.name}. Introduce yourself briefly and ask what task to begin.`}});};
 const testFallback=async()=>{setBusy(true);setError('');setFallbackResult(null);try{setFallbackResult(await ask('claude',fallbackPrompt,fallbackEnabled));}catch(e){setError(e.message);}finally{setBusy(false);}};
 const chooseAttachment=async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2e6)return setError('Attachment must be smaller than 2 MB.');const text=/^(text\/)|json|javascript/.test(file.type)||/\.(md|csv|py|js|jsx|ts|tsx|html|css)$/i.test(file.name);setAttachment({name:file.name,type:file.type||'file',content:text?(await file.text()).slice(0,50000):'',preview:file.type.startsWith('image/')?URL.createObjectURL(file):''});};
 const speak=()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return setError('Speech recognition is unavailable in this browser.');const recognition=new Recognition();recognition.lang=navigator.language;recognition.onstart=()=>setListening(true);recognition.onend=()=>setListening(false);recognition.onresult=event=>setMultiPrompt(value=>`${value} ${event.results[0][0].transcript}`.trim());recognition.start();};
 const openMultimodal=()=>{const context=attachment?.content?`\n\nATTACHED FILE: ${attachment.name}\n${attachment.content}`:attachment?`\n\nATTACHED IMAGE: ${attachment.name}. Use my description to help with this image.`:'';navigate('/chat?model=smart',{state:{starterPrompt:`${multiPrompt}${context}`}});};
 const toggleModel=model=>setEvalModels(items=>items.includes(model)?items.filter(item=>item!==model):[...items,model].slice(0,4));
 const runEvaluation=async()=>{setEvaluating(true);setError('');setEvalResults(evalModels.map(model=>({model,loading:true})));const rows=await Promise.all(evalModels.map(async model=>{try{const output=await ask(model,evalPrompt,fallbackEnabled);const quality=await api('/api/quality/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:output.text})});return{model,...output,quality};}catch(e){return{model,error:e.message};}}));setEvalResults(rows);setEvaluating(false);api('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'evaluation',name:evalPrompt.slice(0,60),prompt:evalPrompt,models:evalModels,results:rows.map(({model,latency,quality,error:rowError})=>({model,latency,score:quality?.score,error:rowError}))})}).catch(()=>{});};
 return <main className="innovation-lab"><header><Link to="/dashboard" className="lab-brand"><span>AI</span>AllModelAI</Link><div><Link to="/chat">Chat</Link><Link to="/studio">Studio</Link></div></header><section className="lab-hero"><p>ADVANCED AI WORKSPACE</p><h1>Innovation Lab</h1><span>Build reliable agents, grounded answers, multimodal prompts, and measurable workflows.</span></section><div className="lab-layout"><nav>{modules.map(([key,name,description])=><button className={active===key?'active':''} onClick={()=>{setActive(key);setError('');}} key={key}><strong>{name}</strong><small>{description}</small></button>)}</nav><section className="lab-panel"><div className="lab-title"><small>MODULE {modules.findIndex(([key])=>key===active)+1} OF 5</small><h2>{modules.find(([key])=>key===active)?.[1]}</h2></div>{error&&<p className="lab-error">{error}</p>}
 {active==='rag'&&<><form className="lab-form" onSubmit={saveDocument}><label className="lab-upload">Import text or code<input type="file" onChange={importFile}/></label><input value={doc.name} onChange={e=>setDoc({...doc,name:e.target.value})} placeholder="Document name" required/><textarea value={doc.content} onChange={e=>setDoc({...doc,content:e.target.value})} placeholder="Paste document content" required/><button>Index document</button></form><div className="lab-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask your knowledge base"/><button onClick={search} disabled={!query.trim()}>Semantic search</button></div><div className="lab-results">{results.map((item,index)=><article key={item.chunkId||`${item.id}-${index}`}><small>[KB{index+1}] relevance {item.score}</small><h3>{item.name}</h3><p>{item.excerpt}</p></article>)}</div><p className="lab-note">{documents.length} indexed document(s). Matching chunks are cited automatically in Smart Chat.</p></>}
 {active==='agents'&&<><form className="lab-form" onSubmit={saveAgent}><input value={agent.name} onChange={e=>setAgent({...agent,name:e.target.value})} placeholder="Agent name" required/><select value={agent.model} onChange={e=>setAgent({...agent,model:e.target.value})}><option>smart</option>{models.map(model=><option key={model}>{model}</option>)}</select><textarea value={agent.instructions} onChange={e=>setAgent({...agent,instructions:e.target.value})} placeholder="Role, rules, style, and goals" required/><div className="tool-pills"><span>Knowledge base</span><span>Smart fallback</span><span>Saved memory</span></div><button>Create agent</button></form><div className="agent-grid">{agents.map(item=><article key={item.id}><small>{item.model}</small><h3>{item.name}</h3><p>{item.instructions}</p><button onClick={()=>launchAgent(item)}>Launch agent →</button></article>)}</div></>}
 {active==='fallback'&&<div className="fallback-card"><h3>Automatic provider recovery</h3><p>If a selected gateway model fails, AllModelAI retries through a compatible GPT route and reports the switch.</p><label className="switch"><input type="checkbox" checked={fallbackEnabled} onChange={e=>{setFallbackEnabled(e.target.checked);localStorage.setItem('allmodelai_fallback',String(e.target.checked));}}/>{fallbackEnabled?'Enabled':'Disabled'}</label><textarea value={fallbackPrompt} onChange={e=>setFallbackPrompt(e.target.value)} placeholder="Prompt to test the resilient route"/><button onClick={testFallback} disabled={!fallbackPrompt.trim()||busy}>{busy?'Testing route…':'Test resilient request'}</button>{fallbackResult&&<article className="fallback-result"><small>{fallbackResult.fallback?`Fell back to ${fallbackResult.fallback}`:'Primary provider succeeded'} · {fallbackResult.latency} ms</small><p>{fallbackResult.text}</p></article>}</div>}
 {active==='multimodal'&&<div className="multi-card"><div className="multi-actions"><button onClick={()=>picker.current?.click()}>＋ Attach file or image</button><button className={listening?'recording':''} onClick={speak}>● {listening?'Listening…':'Speak prompt'}</button><input ref={picker} hidden type="file" accept="image/*,.txt,.md,.csv,.json,.js,.jsx,.ts,.tsx,.py,.html,.css" onChange={chooseAttachment}/></div>{attachment&&<article className="attachment-card">{attachment.preview&&<img src={attachment.preview} alt="Attachment preview"/>}<div><strong>{attachment.name}</strong><small>{attachment.content?`${attachment.content.length.toLocaleString()} characters extracted`:attachment.type}</small></div><button onClick={()=>setAttachment(null)}>Remove</button></article>}<textarea value={multiPrompt} onChange={e=>setMultiPrompt(e.target.value)} placeholder="Ask about the attachment or dictate a prompt"/><button onClick={openMultimodal} disabled={!multiPrompt.trim()}>Continue in Smart Chat →</button><p className="lab-note">Text and code are extracted locally; images receive a safe preview and your accompanying instruction.</p></div>}
 {active==='evals'&&<><textarea className="eval-prompt" value={evalPrompt} onChange={e=>setEvalPrompt(e.target.value)} placeholder="One benchmark prompt for every selected model"/><div className="eval-models">{models.map(model=><button className={evalModels.includes(model)?'selected':''} onClick={()=>toggleModel(model)} key={model}>{model}</button>)}</div><button className="primary-run" onClick={runEvaluation} disabled={!evalPrompt.trim()||evalModels.length<2||evaluating}>{evaluating?'Running benchmark…':`Run ${evalModels.length}-model evaluation`}</button><div className="eval-grid">{evalResults.map(row=><article key={row.model}><h3>{row.model}</h3>{row.loading?<p>Waiting for model…</p>:row.error?<p className="lab-error">{row.error}</p>:<><div className="score-row"><strong>{row.quality?.score}/100</strong><span>{row.latency} ms</span>{row.fallback&&<span>fallback: {row.fallback}</span>}</div><p>{row.text}</p></>}</article>)}</div></>}
 </section></div></main>;
}
