import { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import './ExpansionHub.css';

const modules=[['workflow','Workflow Builder','Connect repeatable AI steps'],['marketplace','Model Marketplace','Install agents and templates'],['meetings','Meeting Assistant','Turn transcripts into action'],['collaboration','Live Collaboration','Work together with roles'],['memory','Memory Graph','Explore connected knowledge'],['versions','Prompt Versions','Compare and restore revisions'],['security','Security Center','Scan prompts and content'],['local','Local Models','Manage your Ollama connection'],['research','Research Agent','Build cited research reports'],['developer','Developer API','Keys, SDK examples, and usage']];
const marketplace=[{name:'Security Reviewer',kind:'agent',model:'deepseek',description:'Reviews code for security and correctness.',content:'Act as a senior application security reviewer. Identify vulnerabilities, explain impact, and propose safe patches.'},{name:'Research Brief',kind:'prompt',model:'smart',description:'Produces a structured, cited research brief.',content:'Research {{topic}}. Include dates, competing viewpoints, inline citations, and a concise source list.'},{name:'Product Strategist',kind:'agent',model:'claude',description:'Turns product ideas into plans and experiments.',content:'Act as a pragmatic product strategist. Clarify the user, problem, risks, metrics, and smallest useful experiment.'}];
const steps=['Input','Research','Draft','Review','Final answer'];
async function api(url,options={}){const response=await fetch(url,{credentials:'include',...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Request failed');return data;}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});

export default function ExpansionHub(){
 const saved=sessionStorage.getItem('allmodelai_user'),user=saved?JSON.parse(saved):null,navigate=useNavigate(),[searchParams]=useSearchParams(),requestedFeature=searchParams.get('feature');
 const[active,setActive]=useState(modules.some(([key])=>key===requestedFeature)?requestedFeature:'workflow'),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[workflow,setWorkflow]=useState({name:'Content production',nodes:['Input','Research','Draft','Review']}),[savedWorkflows,setSavedWorkflows]=useState([]);
 const[meeting,setMeeting]=useState({name:'',transcript:''}),[teams,setTeams]=useState([]),[graph,setGraph]=useState([]);
 const[promptName,setPromptName]=useState(''),[promptText,setPromptText]=useState(''),[versions,setVersions]=useState([]);
 const[securityText,setSecurityText]=useState(''),[securityResult,setSecurityResult]=useState(null),[ollama,setOllama]=useState(null);
 const[researchQuery,setResearchQuery]=useState(''),[research,setResearch]=useState(null),[researching,setResearching]=useState(false);
 const[keys,setKeys]=useState([]),[keyName,setKeyName]=useState(''),[newSecret,setNewSecret]=useState('');
 const title=useMemo(()=>modules.find(([key])=>key===active)?.[1],[active]);
 useEffect(()=>{if(!user?.email)return;if(active==='workflow')api('/api/workspace?type=workflow').then(setSavedWorkflows).catch(e=>setError(e.message));if(active==='collaboration')api('/api/teams').then(setTeams).catch(e=>setError(e.message));if(active==='versions')api('/api/workspace?type=prompt_version').then(setVersions).catch(e=>setError(e.message));if(active==='local')api('/api/ollama/models').then(setOllama).catch(e=>setOllama({online:false,models:[],message:e.message}));if(active==='developer')api('/api/developer/keys').then(setKeys).catch(e=>setError(e.message));if(active==='memory')Promise.all(['memory','project','document','agent'].map(type=>api(`/api/workspace?type=${type}`).catch(()=>[]))).then(groups=>setGraph(groups.flat().slice(0,18)));},[active,user?.email]);
 if(!user)return <Navigate to="/" replace/>;
 const flash=text=>{setNotice(text);window.setTimeout(()=>setNotice(''),2500);};
 const saveWorkflow=async()=>{try{const created=await post('/api/workspace',{type:'workflow',...workflow});setSavedWorkflows(items=>[created,...items]);flash('Workflow saved.');}catch(e){setError(e.message);}};
 const install=async item=>{try{await post('/api/workspace',{type:item.kind==='agent'?'agent':'prompt',name:item.name,model:item.model,instructions:item.kind==='agent'?item.content:'',content:item.content,installedFrom:'marketplace'});flash(`${item.name} installed.`);}catch(e){setError(e.message);}};
 const processMeeting=async()=>{if(!meeting.transcript.trim())return;try{await post('/api/workspace',{type:'meeting',...meeting,createdAt:new Date().toISOString()});navigate('/chat?model=smart',{state:{starterPrompt:`Analyze this meeting transcript. Return: executive summary, decisions, action items with owners, risks, and a follow-up email.\n\nMEETING: ${meeting.name||'Untitled'}\n\n${meeting.transcript}`}});}catch(e){setError(e.message);}};
 const saveVersion=async()=>{try{const created=await post('/api/workspace',{type:'prompt_version',name:promptName||'Untitled prompt',content:promptText,version:versions.filter(item=>item.name===(promptName||'Untitled prompt')).length+1});setVersions(items=>[created,...items]);flash('Prompt revision saved.');}catch(e){setError(e.message);}};
 const scanSecurity=()=>{const findings=[];const rules=[['critical','Possible API key',/(?:sk|amai|ghp|xoxb)_[A-Za-z0-9_-]{12,}/g],['high','Prompt-injection instruction',/ignore (?:all |the )?(?:previous|prior|system) instructions|reveal (?:the )?system prompt/gi],['high','Private key material',/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/g],['medium','Personal email address',/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g],['medium','Possible bearer token',/bearer\s+[A-Za-z0-9._-]{16,}/gi]];rules.forEach(([severity,name,pattern])=>{const matches=securityText.match(pattern)||[];if(matches.length)findings.push({severity,name,count:matches.length});});setSecurityResult({findings,score:Math.max(0,100-findings.reduce((sum,item)=>sum+(item.severity==='critical'?45:item.severity==='high'?25:10)*item.count,0))});};
 const runResearch=async()=>{setResearching(true);setError('');try{setResearch(await post('/api/research',{query:researchQuery}));}catch(e){setError(e.message);}finally{setResearching(false);}};
 const createKey=async event=>{event.preventDefault();try{const created=await post('/api/developer/keys',{name:keyName});setNewSecret(created.secret);setKeys(items=>[{id:created.id,name:created.name,prefix:created.prefix,createdAt:created.createdAt},...items]);setKeyName('');}catch(e){setError(e.message);}};
 const revokeKey=async id=>{try{await api(`/api/developer/keys/${id}`,{method:'DELETE'});setKeys(items=>items.filter(item=>item.id!==id));}catch(e){setError(e.message);}};
 return <main className="expansion-hub"><header><Link className="exp-brand" to="/dashboard"><span>AI</span>AllModelAI</Link><div><Link to="/innovation-lab">Innovation Lab</Link><Link to="/chat">Chat</Link></div></header><section className="exp-hero"><p>NEXT-GENERATION MODULES</p><h1>Expansion Hub</h1><span>Ten connected tools that turn AllModelAI into a complete creation and automation platform.</span></section><div className="exp-layout"><nav>{modules.map(([key,name,description],index)=><button className={active===key?'active':''} onClick={()=>{setActive(key);setError('');setNotice('');}} key={key}><i>{String(index+1).padStart(2,'0')}</i><span><strong>{name}</strong><small>{description}</small></span></button>)}</nav><section className="exp-panel"><div className="exp-title"><small>EXPANSION MODULE</small><h2>{title}</h2></div>{error&&<p className="exp-error">{error}</p>}{notice&&<p className="exp-notice">✓ {notice}</p>}
 {active==='workflow'&&<><div className="workflow-name"><input value={workflow.name} onChange={e=>setWorkflow({...workflow,name:e.target.value})}/><button onClick={saveWorkflow}>Save workflow</button></div><div className="workflow-canvas">{workflow.nodes.map((node,index)=><div className="workflow-node" key={`${node}-${index}`}><i>{index+1}</i><input value={node} onChange={e=>setWorkflow({...workflow,nodes:workflow.nodes.map((item,i)=>i===index?e.target.value:item)})}/><button onClick={()=>setWorkflow({...workflow,nodes:workflow.nodes.filter((_,i)=>i!==index)})}>×</button>{index<workflow.nodes.length-1&&<b>→</b>}</div>)}</div><div className="step-library"><span>Add step:</span>{steps.map(step=><button onClick={()=>setWorkflow({...workflow,nodes:[...workflow.nodes,step]})} key={step}>+ {step}</button>)}</div><div className="saved-list">{savedWorkflows.map(item=><button onClick={()=>setWorkflow({name:item.name,nodes:item.nodes||[]})} key={item.id}><strong>{item.name}</strong><small>{item.nodes?.join(' → ')}</small></button>)}</div></>}
 {active==='marketplace'&&<div className="market-grid">{marketplace.map(item=><article key={item.name}><small>{item.kind} · {item.model}</small><h3>{item.name}</h3><p>{item.description}</p><button onClick={()=>install(item)}>Install template</button></article>)}</div>}
 {active==='meetings'&&<div className="meeting-tool"><input value={meeting.name} onChange={e=>setMeeting({...meeting,name:e.target.value})} placeholder="Meeting name"/><textarea value={meeting.transcript} onChange={e=>setMeeting({...meeting,transcript:e.target.value})} placeholder="Paste a meeting transcript here…"/><div className="meeting-output"><span>Summary</span><span>Decisions</span><span>Action items</span><span>Follow-up email</span></div><button onClick={processMeeting} disabled={!meeting.transcript.trim()}>Process meeting with AI →</button></div>}
 {active==='collaboration'&&<><p className="module-copy">Your existing role-based team workspaces are now the foundation for collaborative AI rooms. Owners and editors can invite teammates; viewers can follow shared work safely.</p><div className="team-cards">{teams.map(team=><article key={team.id}><small>{team.role}</small><h3>{team.name}</h3><p>{team.members?.length||0} members</p><div>{team.members?.map(member=><span key={member.email}>{member.email} · {member.role}</span>)}</div><button onClick={()=>navigate('/studio?tool=team')}>Open workspace</button></article>)}{!teams.length&&<button onClick={()=>navigate('/studio?tool=team')}>Create your first team workspace</button>}</div></>}
 {active==='memory'&&<><p className="module-copy">A live map of your saved memories, documents, projects, and agents.</p><div className="memory-graph"><div className="graph-core">YOU</div>{graph.map((item,index)=><button style={{'--angle':`${index*(360/Math.max(graph.length,1))}deg`,'--ring':`${105+(index%3)*55}px`}} title={item.content||item.instructions||item.name} key={item.id}><small>{item.type}</small><strong>{item.name||'Saved item'}</strong></button>)}</div></>}
 {active==='versions'&&<><div className="version-editor"><input value={promptName} onChange={e=>setPromptName(e.target.value)} placeholder="Prompt name"/><textarea value={promptText} onChange={e=>setPromptText(e.target.value)} placeholder="Write or improve your prompt…"/><button onClick={saveVersion} disabled={!promptText.trim()}>Save new version</button></div><div className="version-list">{versions.map(item=><article key={item.id}><small>VERSION {item.version||1}</small><h3>{item.name}</h3><p>{item.content}</p><button onClick={()=>{setPromptName(item.name);setPromptText(item.content);}}>Restore</button></article>)}</div></>}
 {active==='security'&&<><textarea className="security-input" value={securityText} onChange={e=>setSecurityText(e.target.value)} placeholder="Paste a prompt, document, configuration, or AI output to scan…"/><button onClick={scanSecurity} disabled={!securityText.trim()}>Run local security scan</button>{securityResult&&<div className="security-report"><div className="security-score"><strong>{securityResult.score}</strong><span>Safety score</span></div><div>{securityResult.findings.length?securityResult.findings.map(item=><p className={item.severity} key={item.name}><b>{item.severity}</b>{item.name}<span>{item.count}</span></p>):<p className="safe">No common secret, PII, or injection patterns detected.</p>}</div></div>}</>}
 {active==='local'&&<><div className={`ollama-status ${ollama?.online?'online':''}`}><i/><div><strong>{ollama?.online?'Ollama connected':'Ollama offline'}</strong><small>{ollama?.online?`${ollama.models.length} local model(s) available`:ollama?.message||'Checking local runtime…'}</small></div><button onClick={()=>api('/api/ollama/models').then(setOllama).catch(e=>setOllama({online:false,models:[],message:e.message}))}>Refresh</button></div><div className="local-grid">{ollama?.models?.map(model=><article key={model.name}><h3>{model.name}</h3><p>{(Number(model.size)/1e9).toFixed(1)} GB</p><small>{model.modifiedAt}</small></article>)}</div><pre><code>ollama serve{`\n`}ollama pull llama3.2</code></pre></>}
 {active==='research'&&<><div className="research-form"><textarea value={researchQuery} onChange={e=>setResearchQuery(e.target.value)} placeholder="Define a research objective…"/><button onClick={runResearch} disabled={!researchQuery.trim()||researching}>{researching?'Researching sources…':'Start research agent'}</button></div>{research&&<div className="research-report"><h3>Research timeline</h3>{research.sources?.map((source,index)=><article key={source.url}><i>{index+1}</i><div><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><p>{source.excerpt}</p></div></article>)}</div>}</>}
 {active==='developer'&&<><form className="key-form" onSubmit={createKey}><input value={keyName} onChange={e=>setKeyName(e.target.value)} placeholder="Key name, e.g. Production app"/><button disabled={!keyName.trim()}>Create API key</button></form>{newSecret&&<div className="secret-once"><strong>Copy this key now—it will not appear again.</strong><code>{newSecret}</code><button onClick={()=>navigator.clipboard.writeText(newSecret)}>Copy</button></div>}<div className="key-list">{keys.map(key=><article key={key.id}><div><strong>{key.name}</strong><small>{key.prefix} · created {new Date(key.createdAt).toLocaleDateString()}</small></div><button onClick={()=>revokeKey(key.id)}>Revoke</button></article>)}</div><h3>JavaScript quick start</h3><pre><code>{`const response = await fetch('/api/chat', {\n  method: 'POST',\n  headers: { Authorization: 'Bearer YOUR_KEY' },\n  body: JSON.stringify({ model: 'smart', prompt: 'Hello' })\n});`}</code></pre><p className="module-copy">Key creation and revocation are ready. Bearer-key authentication for public API requests should be enabled before exposing this endpoint outside your private deployment.</p></>}
 </section></div></main>;
}
