const { describe,test,before,after }=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const request=require('supertest');
process.env.NODE_ENV='test';process.env.DB_FILE=path.join(os.tmpdir(),`allmodelai-users-secure-${process.pid}.sqlite`);process.env.ADMIN_KEY='test-admin';fs.rmSync(process.env.DB_FILE,{force:true});const app=require('../app');let owner,viewer;
describe('accounts, teams, and sharing',()=>{
 before(async()=>{owner=request.agent(app);viewer=request.agent(app);await owner.post('/api/auth/register').send({name:'Owner',email:'owner@example.com',password:'secret'});await viewer.post('/api/auth/register').send({name:'Viewer',email:'viewer@example.com',password:'secret'})});
 after(()=>app.locals.db.close());
 test('returns the active HTTP-only session',async()=>{const response=await owner.get('/api/auth/session');assert.equal(response.status,200);assert.equal(response.body.user.email,'owner@example.com')});
 test('protects user administration',async()=>{assert.equal((await request(app).get('/api/users')).status,401);assert.equal((await request(app).get('/api/users').set('x-admin-key','test-admin')).status,200)});
 test('publishes only seeded community profiles',async()=>{const response=await request(app).get('/api/community/users');assert.equal(response.status,200);assert.equal(response.body.length,8);assert.deepEqual(Object.keys(response.body[0]).sort(),['email','id','name']);assert.equal(response.body.some((user)=>user.email==='owner@example.com'),false)});
 test('signs in a seeded user without exposing the password hash',async()=>{const response=await request(app).post('/api/auth/login').send({email:'alice.johnson@gmail.com',password:'AliceAI1!'});assert.equal(response.status,200);assert.equal(response.body.user.email,'alice.johnson@gmail.com');assert.equal(response.body.user.passwordHash,undefined)});
 test('creates a team and enforces roles',async()=>{const created=await owner.post('/api/teams').send({name:'Product team'});assert.equal(created.status,201);const id=created.body.id;const invited=await owner.post(`/api/teams/${id}/members`).send({email:'viewer@example.com',role:'viewer'});assert.equal(invited.status,201);assert.equal((await viewer.post(`/api/teams/${id}/members`).send({email:'other@example.com'})).status,403);assert.equal((await viewer.get('/api/teams')).body[0].role,'viewer')});
 test('publishes a read-only conversation without exposing owner data',async()=>{const chat=await owner.post('/api/chat/history').send({model:'gpt',messages:[{role:'user',text:'Public demo'}]});const shared=await owner.post(`/api/chat/history/${chat.body.id}/share`);assert.equal(shared.status,200);const publicCopy=await request(app).get(`/api/share/${shared.body.token}`);assert.equal(publicCopy.status,200);assert.equal(publicCopy.body.email,undefined);assert.equal(publicCopy.body.messages[0].content,'Public demo')});
 test('cannot delete another account by submitting its email',async()=>{const response=await owner.delete('/api/auth/account').send({email:'viewer@example.com'});assert.equal(response.status,200);assert.equal((await viewer.get('/api/auth/session')).status,200)});
});
