import { useMemo, useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import '../NextTen/NextTen.css';
import '../NextTwentyFive/NextTwentyFive.css';

const tools=[
 ['artifacts','Artifacts Workspace','Build','Create an interactive calculator, table, chart, or mini application directly from a description.','/control-center?feature=artifacts','Create an interactive artifact from this description. Return a clear specification and a complete self-contained HTML file with CSS and JavaScript:\n\n'],
 ['sandbox','Live Code Sandbox','Developer','Run HTML, CSS, and JavaScript with instant preview and inspect errors safely.','/studio?tool=code'],
 ['repository','GitHub Repository Analyzer','Developer','Review repository structure, architecture, dependencies, risks, and code quality.','/chat?model=smart','Analyze this repository information as a senior software architect. Review structure, architecture, dependencies, security, maintainability, and give a prioritized improvement plan:\n\n'],
 ['pull-request','AI Pull Request Reviewer','Developer','Review a pull request and produce actionable comments for specific changes.','/chat?model=deepseek','Review this pull request diff. Find correctness bugs, regressions, security risks, missing tests, and maintainability problems. Reference the affected file and line whenever possible:\n\n'],
 ['database','Database Assistant','Data','Understand schemas, generate safe SQL, and explain or visualize query results.','/chat?model=smart','Act as a database engineer. Analyze this schema or data task, write safe SQL, explain it, and suggest indexes or validation where useful:\n\n'],
 ['api-builder','API Integration Builder','Developer','Turn API documentation or an OpenAPI schema into a production-ready integration.','/chat?model=smart','Build a robust API integration from the following documentation. Include authentication, validation, timeouts, retries, error handling, and a complete usage example:\n\n'],
 ['no-code-agent','No-code Agent Builder','Agents','Combine a model, memory, tools, conditions, and actions in a visual agent configuration.','/innovation-lab?feature=agents'],
 ['autonomous','Autonomous Project Mode','Agents','Plan a goal, execute its stages, track progress, and pause for important decisions.','/production'],
 ['terminal','AI Terminal Assistant','Developer','Explain terminal commands, detect dangerous operations, and diagnose command failures.','/chat?model=deepseek','Act as a cautious terminal assistant. Explain the command or error below, identify the cause, warn about destructive actions, and provide the safest commands to continue:\n\n'],
 ['logs','Error Log Analyzer','Developer','Group related log events and identify the most likely root cause and fix.','/chat?model=smart','Analyze these application logs. Group related errors, build a timeline, identify the likely root cause, and provide verification and repair steps:\n\n'],
 ['dashboard','Prompt-to-Dashboard','Data','Generate an interactive dashboard with charts, filters, KPIs, and responsive layout.','/website-builder','Create a dashboard for: '],
 ['data-studio','Data Analysis Studio','Data','Clean CSV or spreadsheet data, calculate metrics, and create useful visualizations.','/skills-hub'],
 ['document-diff','Document Comparison','Documents','Compare document versions and explain edits, conflicts, and semantic changes.','/chat?model=smart','Compare the following two document versions. Show additions, removals, contradictions, and important semantic changes, then recommend the best final wording:\n\n'],
 ['contract','Contract Risk Scanner','Documents','Extract obligations, deadlines, penalties, missing protections, and risky clauses.','/chat?model=claude','Review this contract for risks. Extract obligations, deadlines, renewal terms, penalties, ambiguous clauses, and missing protections. This is an informational review, not legal advice:\n\n'],
 ['resume','Resume & Job Matcher','Career','Score a resume against a vacancy and recommend targeted improvements.','/chat?model=smart','Compare the resume and job description below. Score the match, identify missing skills and keywords, and rewrite the strongest relevant resume sections without inventing experience:\n\n'],
 ['repurpose','Content Repurposing Studio','Content','Transform one source into posts, email, scripts, summaries, and short-form content.','/creator-tools','Repurpose this source into a LinkedIn post, short video script, email, five social posts, and a concise summary. Preserve the original facts and brand tone:\n\n'],
 ['brand','Brand Voice Manager','Content','Save brand rules and evaluate whether generated content matches the desired voice.','/studio?tool=memory','Analyze this brand voice and content. Identify voice rules, score consistency, and rewrite mismatched sections while preserving meaning:\n\n'],
 ['support','AI Customer Support Center','Business','Draft grounded customer replies and escalate sensitive or uncertain cases to a person.','/studio?tool=assistant','Act as a customer support specialist. Draft a helpful reply using only the supplied policy and facts, identify uncertainty, and mark whether human escalation is required:\n\n'],
 ['email','Email Workspace','Business','Write, improve, translate, classify, and prepare context-aware email replies.','/chat?model=smart','Help with this email. Detect the needed action, preserve all important facts, and produce a clear professional response in the appropriate language and tone:\n\n'],
 ['visual-prompt','Visual Prompt Builder','Prompts','Assemble strong prompts from goal, audience, style, constraints, context, and output format.','/studio?tool=prompt'],
 ['cache','Model Response Cache','Infrastructure','Reuse approved results for repeated requests to reduce latency, tokens, and cost.','/production'],
 ['offline','Offline Workspace','Infrastructure','Access saved history, documents, and local Ollama models without cloud connectivity.','/expansion-hub?feature=local'],
 ['accessibility','Accessibility Assistant','Quality','Audit interfaces and documents for WCAG issues and propose specific fixes.','/chat?model=smart','Audit the following interface code or document for accessibility. Check keyboard use, semantics, labels, contrast, focus, screen readers, and WCAG compliance. Return prioritized fixes and corrected examples:\n\n'],
 ['notifications','AI Notifications Center','Infrastructure','Collect updates from agents, workflows, tasks, providers, budgets, and integrations.','/control-center?feature=notify'],
 ['public-app','Public AI App Builder','Build','Publish an agent or workflow as a focused application with its own shareable URL.','/website-builder','Build a polished public AI application for: '],
];
const groups=['All',...new Set(tools.map(item=>item[2]))];

export default function BuilderTwentyFive(){
 const saved=sessionStorage.getItem('allmodelai_user'),user=saved?JSON.parse(saved):null,navigate=useNavigate();
 const[active,setActive]=useState('artifacts'),[group,setGroup]=useState('All'),[query,setQuery]=useState(''),[input,setInput]=useState('');
 const visible=useMemo(()=>tools.filter(item=>(group==='All'||item[2]===group)&&`${item[1]} ${item[2]} ${item[3]}`.toLowerCase().includes(query.toLowerCase())),[group,query]);
 const selected=tools.find(item=>item[0]===active)||tools[0],acceptsInput=Boolean(selected[5]);
 if(!user)return <Navigate to="/" replace/>;
 const launch=()=>{if(acceptsInput){if(!input.trim())return;const route=selected[4];if(route==='/website-builder'){navigate(route,{state:{starterPrompt:`${selected[5]}${input}`}});return;}navigate(route,{state:{starterPrompt:`${selected[5]}${input}`}});return;}navigate(selected[4]);};
 return <main className="next-ten-page next-25-page"><header className="next-ten-nav"><Link to="/dashboard" className="next-ten-brand"><b>AI</b>AllModelAI</Link><nav><Link to="/next-25">Next 25</Link><Link to="/chat">Chat</Link><Link to="/dashboard">Dashboard</Link></nav></header>
  <section className="next-ten-hero"><div><p>ALLMODEL AI · BUILDER 25</p><h1>From prompt.<br/><span>To working product.</span></h1><small>Developer, data, document, content, agent, business, and infrastructure tools connected in one workspace.</small></div><strong>25</strong></section>
  <section className="next-25-toolbar"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Builder 25..."/></label><div>{groups.map(item=><button className={group===item?'active':''} onClick={()=>setGroup(item)} key={item}>{item}</button>)}</div></section>
  <section className="next-ten-shell next-25-shell"><aside>{visible.map(item=><button type="button" className={active===item[0]?'active':''} onClick={()=>{setActive(item[0]);setInput('');}} key={item[0]}><i>{String(tools.indexOf(item)+1).padStart(2,'0')}</i><span>{item[2]==='Developer'?'</>':item[2]==='Data'?'▥':'✦'}</span><div><strong>{item[1]}</strong><small>{item[2]}</small></div></button>)}</aside>
   <article className="next-ten-panel"><div className="next-ten-panel-title"><span>{String(tools.findIndex(item=>item[0]===selected[0])+1).padStart(2,'0')}</span><div><small>{selected[2].toUpperCase()} TOOL</small><h2>{selected[1]}</h2></div></div><p className="next-ten-description">{selected[3]}</p>{acceptsInput?<div className="agent-team"><label>Project input<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste code, data, documentation, or describe the result you need..."/></label></div>:<div className="next-ten-flow"><div><i>1</i><span>Add context</span></div><b>→</b><div><i>2</i><span>Build with AI</span></div><b>→</b><div><i>3</i><span>Test & export</span></div></div>}<button className="next-ten-launch" disabled={acceptsInput&&!input.trim()} onClick={launch}>Open {selected[1]} <span>→</span></button><footer><span>● Builder connected</span><small>Uses your models, saved workspace, privacy controls, and project history.</small></footer></article>
  </section></main>;
}
