import { useEffect, useRef, useState } from "react";
import { platformStats } from "../../data/platformStats";
import "./HomeBlocks.css";

/* ---------- Animated stats bar ---------- */

function CountUp({ value = 0, decimals = 0, suffix = "" }) {
  const [display, setDisplay] = useState(0);
  const ref = useRef(null);
  const started = useRef(false);
  const frameRef = useRef(null);

  useEffect(() => {
    const element = ref.current;

    if (!element) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !started.current) {
          started.current = true;

          const duration = 1400;
          const start = performance.now();

          const tick = (now) => {
            const progress = Math.min((now - start) / duration, 1);
            const eased = 1 - Math.pow(1 - progress, 3);

            setDisplay(value * eased);

            if (progress < 1) {
              frameRef.current = requestAnimationFrame(tick);
            } else {
              setDisplay(value);
            }
          };

          frameRef.current = requestAnimationFrame(tick);
        }
      },
      { threshold: 0.4 }
    );

    observer.observe(element);

    return () => {
      observer.disconnect();

      if (frameRef.current) {
        cancelAnimationFrame(frameRef.current);
      }
    };
  }, [value]);

  const formatted =
    decimals > 0
      ? display.toFixed(decimals)
      : Math.round(display).toLocaleString();

  return (
    <strong ref={ref}>
      {formatted}
      {suffix}
    </strong>
  );
}

/* ---------- Stats Bar ---------- */

export function StatsBar() {
  return (
    <section className="stats-bar" aria-label="Platform statistics">
      {platformStats.map((stat) => (
        <div key={stat.label} className="stat-item">
          <CountUp
            value={stat.value}
            suffix={stat.suffix || ""}
            decimals={stat.decimals ?? 0}
          />

          <span>{stat.label}</span>
        </div>
      ))}
    </section>
  );
}

/* ---------- Use Cases ---------- */

const USE_CASES = {
  Developers: {
    icon: "👨‍💻",
    title: "Ship faster with AI pair programming",
    points: [
      "Debug and refactor code across any language",
      "Generate tests and documentation instantly",
      "Compare model output and pick the best patch",
    ],
    cta: "Open Chat",
  },

  Marketers: {
    icon: "📈",
    title: "Campaigns that write themselves",
    points: [
      "Ad copy and landing pages in seconds",
      "Brand-consistent tone across channels",
      "A/B test ideas generated by different models",
    ],
    cta: "Try Prompts",
  },

  Students: {
    icon: "🎓",
    title: "Learn anything, explained your way",
    points: [
      "Complex topics broken into simple steps",
      "Summaries of long papers and lectures",
      "Practice questions tailored to your level",
    ],
    cta: "Start Learning",
  },

  Designers: {
    icon: "🎨",
    title: "From idea to interface",
    points: [
      "Generate website layouts with the Website Builder",
      "Copy, colors and structure in one prompt",
      "Iterate with a different model in one click",
    ],
    cta: "Open Builder",
  },
};

export function UseCases() {
  const [active, setActive] = useState("Developers");

  const current = USE_CASES[active];

  return (
    <section className="use-cases" aria-label="Use cases">
      <h2 className="block-title">
        Built for how <span>you</span> work
      </h2>

      <div className="uc-tabs">
        {Object.keys(USE_CASES).map((key) => (
          <button
            key={key}
            type="button"
            className={key === active ? "active" : ""}
            onClick={() => setActive(key)}
          >
            {USE_CASES[key].icon} {key}
          </button>
        ))}
      </div>

      <div className="uc-panel">
        <div className="uc-copy">
          <h3>{current.title}</h3>

          <ul>
            {current.points.map((point) => (
              <li key={point}>✓ {point}</li>
            ))}
          </ul>

          <a href="/chat" className="uc-cta">
            {current.cta} →
          </a>
        </div>

        <div className="uc-visual" aria-hidden="true">
          <div className="uc-card uc-card-a">
            {current.icon} {active}
          </div>

          <div className="uc-card uc-card-b">
            ✦ Smart Router selected the best model
          </div>

          <div className="uc-card uc-card-c">
            Response ready in 1.6s
          </div>
        </div>
      </div>
    </section>
  );
}

/* ---------- FAQ ---------- */

const FAQS = [
  {
    q: "What is AllModelAI?",
    a: "AllModelAI brings the world's leading AI models — Claude, GPT, Gemini, Llama and more — into a single workspace with one subscription and one interface.",
  },
  {
    q: "Do I need separate API keys for each model?",
    a: "No. AllModelAI handles all provider connections for you. One account gives you access to every connected model, and Smart Router picks the best one per task.",
  },
  {
    q: "Is there a free plan?",
    a: "Yes. The free tier includes access to free models like Gemini Flash, Llama 2 and Cloudflare AI with generous daily limits. Upgrade any time for premium models.",
  },
  {
    q: "How does Smart Router work?",
    a: "Smart Router analyzes your prompt — its length, task type and complexity — and routes it to the model best suited for it, with automatic fallback if a model is unavailable.",
  },
  {
    q: "Can I cancel my subscription?",
    a: "Any time, in one click from Settings. Your data stays exportable and your account remains on the free tier.",
  },
];

export function FAQ() {
  const [open, setOpen] = useState(0);

  return (
    <section
      className="faq-block"
      aria-label="Frequently asked questions"
    >
      <h2 className="block-title">
        Frequently asked <span>questions</span>
      </h2>

      <div className="faq-list">
        {FAQS.map((item, index) => {
          const isOpen = open === index;

          return (
            <div
              key={item.q}
              className={`faq-item ${isOpen ? "open" : ""}`}
            >
              <button
                type="button"
                onClick={() => setOpen(isOpen ? -1 : index)}
                aria-expanded={isOpen}
              >
                {item.q}
                <span className="faq-chevron">▾</span>
              </button>

              <div
                className="faq-answer"
                style={{
                  maxHeight: isOpen ? "200px" : "0px",
                }}
              >
                <p>{item.a}</p>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}

/* ---------- Newsletter ---------- */

export function Newsletter() {
  const [email, setEmail] = useState("");
  const [done, setDone] = useState(false);

  const submit = (event) => {
    event.preventDefault();

    if (!email.trim()) return;

    setDone(true);
  };

  return (
    <section className="newsletter" aria-label="Newsletter">
      <div className="newsletter-card">
        <h2>Stay ahead of the AI curve</h2>

        <p>
          One email a week: new models, features and prompt ideas. No spam,
          unsubscribe anytime.
        </p>

        {done ? (
          <p className="newsletter-done">
            ✓ You're in! Check your inbox to confirm.
          </p>
        ) : (
          <form onSubmit={submit}>
            <input
              type="email"
              required
              placeholder="you@example.com"
              value={email}
              onChange={(event) => setEmail(event.target.value)}
            />

            <button type="submit">Subscribe</button>
          </form>
        )}
      </div>
    </section>
  );
}