"""Safe upper bounds for educational training jobs."""

MAX_EPOCHS = 500
MAX_BATCH_SIZE = 128
MAX_DATA_POINTS = 512
MIN_EPOCHS = 5
MIN_LEARNING_RATE = 1e-5
MAX_LEARNING_RATE = 1.0
MAX_CONCURRENT_JOBS = 2
TRAINING_TIMEOUT_SEC = 120
