import { useEffect, useState } from 'react';
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import './AIToolsLab.css';

const tools=[['research','Web research'],['voice','Voice chat'],['ollama','Local Ollama'],['documents','PDF & documents'],['slides','Presentation maker'],['website','Website generator'],['agents','Personal agents'],['memory','Shared memory'],['team','Team workspace'],['quality','Answer quality']];
const download=(name,content,type='text/plain')=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type}));link.download=name;link.click();URL.revokeObjectURL(link.href)};

export default function AIToolsLab(){
 const navigate=useNavigate(); const [searchParams]=useSearchParams(); const requestedTool=searchParams.get('tool'); const saved=sessionStorage.getItem('allmodelai_user'); const user=saved?JSON.parse(saved):null;
 const [active,setActive]=useState(tools.some(([key])=>key===requestedTool)?requestedTool:'research'); const [query,setQuery]=useState(''); const [research,setResearch]=useState(null); const [busy,setBusy]=useState(false);
 const [ollama,setOllama]=useState(null); const [topic,setTopic]=useState(''); const [slides,setSlides]=useState([]); const [sitePrompt,setSitePrompt]=useState(''); const [siteHtml,setSiteHtml]=useState('');
 const [members,setMembers]=useState([]); const [member,setMember]=useState(''); const [qualityText,setQualityText]=useState(''); const [quality,setQuality]=useState(null);
 useEffect(()=>{if(user?.email)fetch(`/api/workspace?email=${encodeURIComponent(user.email)}&type=team`).then(r=>r.ok?r.json():[]).then(setMembers)},[user?.email]);
 if(!user)return <Navigate to="/" replace/>;
 const runResearch=async()=>{if(!query.trim())return;setBusy(true);setResearch(null);try{const response=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const data=await response.json();if(!response.ok)throw new Error(data.message);setResearch(data)}catch(error){setResearch({error:error.message})}finally{setBusy(false)}};
 const checkOllama=async()=>{const response=await fetch('/api/ollama/models');const data=await response.json();setOllama(data)};
 const makeSlides=()=>{if(!topic.trim())return;setSlides([['Opening',topic],['Problem',`What challenge does ${topic} solve?`],['Key insights',`Three important ideas about ${topic}`],['Solution','Recommended approach and implementation'],['Roadmap','Next steps, owners, and milestones'],['Conclusion','Summary and call to action']])};
 const makeSite=()=>{const name=sitePrompt.trim()||'My new product';setSiteHtml(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{margin:0;font-family:system-ui;background:#07111f;color:white}main{min-height:100vh;display:grid;place-items:center;text-align:center;padding:40px;background:radial-gradient(circle at top,#4f46e5,transparent 45%)}h1{font-size:clamp(3rem,8vw,7rem);margin:0}p{color:#cbd5e1;font-size:1.2rem}button{padding:14px 22px;border:0;border-radius:12px;background:#7c3aed;color:white;font-weight:800}</style></head><body><main><section><small>BUILT WITH ALLMODEL AI</small><h1>${name.replaceAll('<','&lt;')}</h1><p>A fast, modern landing page generated from your idea.</p><button>Get started</button></section></main></body></html>`)};
 const invite=async()=>{if(!member.trim())return;const response=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,type:'team',name:member,role:'Editor'})});if(response.ok){const item=await response.json();setMembers(current=>[item,...current]);setMember('')}};
 const checkQuality=async()=>{const response=await fetch('/api/quality/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:qualityText})});setQuality(await response.json())};
 return <main className="tools-lab"><header><Link to="/dashboard"><b>AI</b>AllModelAI</Link><nav><Link to="/chat">Chat</Link><Link to="/studio">Studio</Link><Link to="/dashboard">Dashboard</Link></nav></header><section className="tools-hero"><small>10 NEW CAPABILITIES</small><h1>AI Power Lab</h1><p>Research, create, collaborate, and run free local intelligence.</p></section><div className="tools-layout"><aside>{tools.map(([key,name],index)=><button className={active===key?'active':''} onClick={()=>setActive(key)} key={key}><i>{index+1}</i>{name}</button>)}</aside><section className="tool-panel">
 {active==='research'&&<><h2>Web research with sources</h2><div className="tool-input"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What do you want to research?"/><button onClick={runResearch}>{busy?'Searching…':'Search web'}</button></div>{research?.error&&<p className="tool-error">{research.error}</p>}<div className="source-results">{research?.sources?.map((source,index)=><article key={source.url}><small>SOURCE {index+1}</small><h3>{source.title}</h3><p>{source.excerpt}</p><a href={source.url} target="_blank" rel="noreferrer">Open source ↗</a></article>)}</div></>}
 {active==='voice'&&<Tool title="Voice conversation" text="Use speech recognition in Chat, dictate prompts, and receive answers in your language." button="Open voice chat" onClick={()=>navigate('/chat')}/>}
 {active==='ollama'&&<><h2>Free local models with Ollama</h2><p>Your prompts stay on this computer and do not consume cloud credits.</p><button className="tool-primary" onClick={checkOllama}>Check Ollama</button>{ollama&&<div className="tool-status"><strong>{ollama.online?'Ollama is online':'Ollama is offline'}</strong><p>{ollama.message||`${ollama.models.length} local models found`}</p>{ollama.models?.map(model=><span key={model.name}>{model.name}</span>)}</div>}</>}
 {active==='documents'&&<Tool title="Chat with documents" text="Import text, code, CSV, Markdown, PDF or DOCX knowledge and ask questions from Smart Chat." button="Open document workspace" onClick={()=>navigate('/studio')}/>}
 {active==='slides'&&<><h2>Presentation maker</h2><div className="tool-input"><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Presentation topic"/><button onClick={makeSlides}>Generate deck</button></div><div className="slide-grid">{slides.map(([title,text],index)=><article key={title}><small>SLIDE {index+1}</small><h3>{title}</h3><p>{text}</p></article>)}</div>{slides.length>0&&<button className="tool-primary" onClick={()=>download(`${topic||'presentation'}.md`,slides.map(([title,text],i)=>`# ${i+1}. ${title}\n\n${text}`).join('\n\n---\n\n'),'text/markdown')}>Download deck</button>}</>}
 {active==='website'&&<><h2>Website generator</h2><div className="tool-input"><input value={sitePrompt} onChange={e=>setSitePrompt(e.target.value)} placeholder="Product or website name"/><button onClick={makeSite}>Generate website</button></div>{siteHtml&&<><iframe className="site-preview" sandbox="" title="Generated website" srcDoc={siteHtml}/><button className="tool-primary" onClick={()=>download('allmodelai-site.html',siteHtml,'text/html')}>Download HTML</button></>}</>}
 {active==='agents'&&<Tool title="Personal AI agents" text="Create an expert with its own name, model, instructions, knowledge, and response style." button="Manage agents" onClick={()=>navigate('/studio')}/>}
 {active==='memory'&&<Tool title="Shared AI memory" text="Save facts and preferences once so every model can use the same controlled context." button="Manage memory" onClick={()=>navigate('/studio')}/>}
 {active==='team'&&<><h2>Team workspace</h2><div className="tool-input"><input value={member} onChange={e=>setMember(e.target.value)} placeholder="teammate@example.com"/><button onClick={invite}>Invite member</button></div><div className="member-list">{members.map(item=><article key={item.id}><strong>{item.name}</strong><span>{item.role}</span></article>)}</div></>}
 {active==='quality'&&<><h2>Answer quality check</h2><textarea className="quality-input" value={qualityText} onChange={e=>setQualityText(e.target.value)} placeholder="Paste an AI answer to evaluate…"/><button className="tool-primary" disabled={!qualityText.trim()} onClick={checkQuality}>Evaluate answer</button>{quality?.score!=null&&<div className="quality-result"><strong>{quality.score}/100</strong>{Object.entries(quality.metrics).map(([name,value])=><p key={name}><span>{name}</span><b>{value}</b></p>)}<ul>{quality.suggestions.map(item=><li key={item}>{item}</li>)}</ul></div>}</>}
 </section></div></main>;
}
function Tool({title,text,button,onClick}){return <div className="tool-action"><small>ALLMODEL AI TOOL</small><h2>{title}</h2><p>{text}</p><button className="tool-primary" onClick={onClick}>{button}</button></div>}
