const crypto = require('node:crypto');
const { promisify } = require('node:util');
const users = require('../data/data');
const scrypt = promisify(crypto.scrypt);
const hash = (value) => crypto.createHash('sha256').update(value).digest('hex');
const json = (value, fallback = {}) => { try { return JSON.parse(value); } catch { return fallback; } };
const now = () => new Date().toISOString();
const audit = (req, action, targetType, targetId, metadata = {}) => req.app.locals.db.database.prepare('INSERT INTO audit_events (email, action, target_type, target_id, metadata, ip, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(req.user.email, action, targetType || null, targetId || null, JSON.stringify(metadata), req.ip || null, now());

const health = (req, res) => {
    const database = req.app.locals.db.database;
    const checks = { database: false, openai: Boolean(process.env.OPENAI_API_KEY || process.env.OPEN_AI_API_KEY), openrouter: Boolean(process.env.OPENROUTER_API_KEY || process.env.API_KEY), email: Boolean(process.env.RESEND_API_KEY && process.env.EMAIL_FROM), payments: Boolean(process.env.STRIPE_SECRET_KEY), postgres: Boolean(process.env.DATABASE_URL), monitoring: Boolean(process.env.SENTRY_DSN) };
    try { database.prepare('SELECT 1').get(); checks.database = true; } catch { /* reported below */ }
    const ready = checks.database;
    return res.status(ready ? 200 : 503).json({ status: ready ? 'healthy' : 'degraded', service: 'AllModelAI', version: process.env.APP_VERSION || '1.0.0', uptimeSeconds: Math.floor(process.uptime()), checks, timestamp: now() });
};

const globalSearch = (req, res) => {
    const query = String(req.query.q || '').trim().slice(0, 200);
    if (query.length < 2) return res.json({ query, results: [] });
    const pattern = `%${query.replace(/[%_]/g, '')}%`; const db = req.app.locals.db.database;
    const conversations = db.prepare('SELECT id, title AS name, model, updated_at AS updatedAt FROM conversations WHERE email = ? AND (title LIKE ? OR messages LIKE ?) ORDER BY updated_at DESC LIMIT 20').all(req.user.email, pattern, pattern).map(item => ({ ...item, type: 'conversation', excerpt: `Chat with ${item.model || 'AI'}` }));
    const workspace = db.prepare('SELECT id, type, data, updated_at AS updatedAt FROM workspace_items WHERE email = ? AND data LIKE ? ORDER BY updated_at DESC LIMIT 30').all(req.user.email, pattern).map(row => { const data = json(row.data); return { id: row.id, type: row.type, name: data.name || row.type, excerpt: String(data.content || data.instructions || data.prompt || '').slice(0, 220), updatedAt: row.updatedAt }; });
    return res.json({ query, results: [...conversations, ...workspace].sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0, 40) });
};

const jobPayload = row => ({ id: row.id, type: row.type, status: row.status, progress: row.progress, stage: row.stage, payload: json(row.payload), result: json(row.result, null), error: row.error, createdAt: row.created_at, updatedAt: row.updated_at });
const processJob = (app, id) => {
    const db = app.locals.db.database; const row = db.prepare('SELECT * FROM background_jobs WHERE id = ?').get(id); if (!row || row.status !== 'queued') return;
    db.prepare("UPDATE background_jobs SET status='running', progress=15, stage='Planning', updated_at=? WHERE id=?").run(now(), id);
    const stages = [['Collecting inputs', 35], ['Processing', 65], ['Verifying result', 90]]; let index = 0;
    const advance = () => { const current = db.prepare('SELECT status FROM background_jobs WHERE id=?').get(id); if (!current || current.status === 'canceled') return; if (index < stages.length) { const [stage, progress] = stages[index++]; db.prepare('UPDATE background_jobs SET stage=?, progress=?, updated_at=? WHERE id=?').run(stage, progress, now(), id); return setTimeout(advance, 60); } const payload = json(row.payload); const result = { completed: true, message: `${row.type} job completed`, input: payload, completedAt: now() }; db.transaction(() => { db.prepare("UPDATE background_jobs SET status='completed', progress=100, stage='Complete', result=?, updated_at=? WHERE id=?").run(JSON.stringify(result), now(), id); db.prepare('INSERT INTO notifications (id,email,title,message,kind,created_at) VALUES (?,?,?,?,?,?)').run(`notification-${crypto.randomUUID()}`, row.email, 'Background task finished', `${row.type} is ready to review.`, 'job', now()); })(); };
    setTimeout(advance, 60);
};
const listJobs = (req, res) => res.json(req.app.locals.db.database.prepare('SELECT * FROM background_jobs WHERE email=? ORDER BY created_at DESC LIMIT 100').all(req.user.email).map(jobPayload));
const createJob = (req, res) => { const type = String(req.body.type || '').trim().slice(0, 50); if (!['research','evaluation','meeting','workflow','document'].includes(type)) return res.status(400).json({ message: 'Unsupported job type' }); const id = `job-${crypto.randomUUID()}`, createdAt = now(); req.app.locals.db.database.prepare("INSERT INTO background_jobs (id,email,type,status,progress,stage,payload,created_at,updated_at) VALUES (?,?,?,'queued',0,'Queued',?,?,?)").run(id, req.user.email, type, JSON.stringify(req.body.payload || {}), createdAt, createdAt); audit(req, 'job.created', 'job', id, { type }); if (process.env.NODE_ENV !== 'test') setImmediate(() => processJob(req.app, id)); return res.status(202).json(jobPayload(req.app.locals.db.database.prepare('SELECT * FROM background_jobs WHERE id=?').get(id))); };
const cancelJob = (req, res) => { const result = req.app.locals.db.database.prepare("UPDATE background_jobs SET status='canceled', stage='Canceled', updated_at=? WHERE id=? AND email=? AND status IN ('queued','running')").run(now(), req.params.id, req.user.email); if (result.changes) audit(req, 'job.canceled', 'job', req.params.id); return result.changes ? res.json({ message: 'Job canceled' }) : res.status(404).json({ message: 'Cancelable job not found' }); };

const listNotifications = (req, res) => res.json(req.app.locals.db.database.prepare('SELECT id,title,message,kind,read_at AS readAt,created_at AS createdAt FROM notifications WHERE email=? ORDER BY created_at DESC LIMIT 100').all(req.user.email));
const readNotification = (req, res) => { const result = req.app.locals.db.database.prepare('UPDATE notifications SET read_at=? WHERE id=? AND email=?').run(now(), req.params.id, req.user.email); return result.changes ? res.json({ message: 'Notification read' }) : res.status(404).json({ message: 'Notification not found' }); };
const usageReport = (req, res) => { const rows = req.app.locals.db.database.prepare('SELECT model, input_tokens AS inputTokens, output_tokens AS outputTokens, latency_ms AS latencyMs, fallback_used AS fallbackUsed, estimated_cost AS estimatedCost, created_at AS createdAt FROM usage_events WHERE email=? ORDER BY created_at DESC LIMIT 500').all(req.user.email); const totals = rows.reduce((sum,row)=>({requests:sum.requests+1,inputTokens:sum.inputTokens+row.inputTokens,outputTokens:sum.outputTokens+row.outputTokens,estimatedCost:sum.estimatedCost+row.estimatedCost,fallbacks:sum.fallbacks+row.fallbackUsed}),{requests:0,inputTokens:0,outputTokens:0,estimatedCost:0,fallbacks:0}); return res.json({ totals:{...totals,estimatedCost:Number(totals.estimatedCost.toFixed(6))},events:rows }); };
const auditLog = (req, res) => res.json(req.app.locals.db.database.prepare('SELECT id,action,target_type AS targetType,target_id AS targetId,metadata,ip,created_at AS createdAt FROM audit_events WHERE email=? ORDER BY created_at DESC LIMIT 200').all(req.user.email).map(row=>({...row,metadata:json(row.metadata)})));

const listWebhooks = (req, res) => res.json(req.app.locals.db.database.prepare('SELECT id,name,url,active,created_at AS createdAt FROM webhooks WHERE email=? ORDER BY created_at DESC').all(req.user.email));
const createWebhook = (req, res) => { const name = String(req.body.name || '').trim().slice(0,80), url = String(req.body.url || '').trim(); let parsed; try { parsed = new URL(url); } catch { return res.status(400).json({ message: 'Valid HTTPS webhook URL required' }); } if (parsed.protocol !== 'https:' && process.env.NODE_ENV === 'production') return res.status(400).json({ message: 'Production webhooks must use HTTPS' }); const secret = `whsec_${crypto.randomBytes(24).toString('base64url')}`, id=`webhook-${crypto.randomUUID()}`, createdAt=now(); req.app.locals.db.database.prepare('INSERT INTO webhooks (id,email,name,url,secret_hash,created_at) VALUES (?,?,?,?,?,?)').run(id,req.user.email,name||parsed.hostname,url,hash(secret),createdAt);audit(req,'webhook.created','webhook',id);return res.status(201).json({id,name:name||parsed.hostname,url,active:1,createdAt,secret,warning:'Copy the signing secret now.'}); };
const deleteWebhook = (req,res)=>{const result=req.app.locals.db.database.prepare('DELETE FROM webhooks WHERE id=? AND email=?').run(req.params.id,req.user.email);if(result.changes)audit(req,'webhook.deleted','webhook',req.params.id);return result.changes?res.json({message:'Webhook deleted'}):res.status(404).json({message:'Webhook not found'});};

const privacyExport = (req,res)=>{const db=req.app.locals.db.database,email=req.user.email;const user=db.prepare('SELECT id,name,email,email_verified AS emailVerified,role FROM users WHERE lower(email)=lower(?)').get(email);const conversations=db.prepare('SELECT id,model,title,messages,created_at AS createdAt,updated_at AS updatedAt FROM conversations WHERE email=?').all(email).map(row=>({...row,messages:json(row.messages,[])}));const workspace=db.prepare('SELECT id,type,data,created_at AS createdAt,updated_at AS updatedAt FROM workspace_items WHERE email=?').all(email).map(row=>({...row,...json(row.data),data:undefined}));audit(req,'privacy.exported','account',String(user.id));res.setHeader('Content-Disposition',`attachment; filename="allmodelai-export-${Date.now()}.json"`);return res.json({exportedAt:now(),user,conversations,workspace});};

const createAccountToken=(req,res,purpose)=>{const secret=crypto.randomBytes(32).toString('base64url'),expiresAt=Date.now()+30*60*1000;req.app.locals.db.database.prepare('INSERT INTO account_tokens (token_hash,email,purpose,expires_at,created_at) VALUES (?,?,?,?,?)').run(hash(secret),req.user.email,purpose,expiresAt,now());audit(req,`${purpose}.requested`,'account',String(req.user.id));return res.json({message:`${purpose==='verify_email'?'Verification':'Password reset'} request created`,...(process.env.NODE_ENV==='test'||process.env.EXPOSE_ACCOUNT_TOKENS==='true'?{token:secret}:{})});};
const requestEmailVerification=(req,res)=>createAccountToken(req,res,'verify_email');
const confirmEmailVerification=(req,res)=>{const token=String(req.body.token||''),db=req.app.locals.db.database,row=db.prepare("SELECT * FROM account_tokens WHERE token_hash=? AND purpose='verify_email' AND expires_at>?").get(hash(token),Date.now());if(!row)return res.status(400).json({message:'Invalid or expired verification token'});db.transaction(()=>{db.prepare('UPDATE users SET email_verified=1 WHERE lower(email)=lower(?)').run(row.email);db.prepare('DELETE FROM account_tokens WHERE token_hash=?').run(hash(token));})();return res.json({message:'Email verified'});};
const requestPasswordReset=(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),db=req.app.locals.db.database,user=db.prepare('SELECT id,email FROM users WHERE lower(email)=lower(?)').get(email);if(!user)return res.json({message:'If the account exists, a password reset request was created.'});const secret=crypto.randomBytes(32).toString('base64url'),expiresAt=Date.now()+30*60*1000;db.prepare('INSERT INTO account_tokens (token_hash,email,purpose,expires_at,created_at) VALUES (?,?,?,?,?)').run(hash(secret),user.email,'password_reset',expiresAt,now());return res.json({message:'If the account exists, a password reset request was created.',...(process.env.NODE_ENV==='test'||process.env.EXPOSE_ACCOUNT_TOKENS==='true'?{token:secret}:{})});};
const confirmPasswordReset=async(req,res)=>{const token=String(req.body.token||''),password=String(req.body.password||''),db=req.app.locals.db.database,row=db.prepare("SELECT * FROM account_tokens WHERE token_hash=? AND purpose='password_reset' AND expires_at>?").get(hash(token),Date.now());if(!row||password.length<8)return res.status(400).json({message:'Valid token and password of at least 8 characters required'});const salt=crypto.randomBytes(16).toString('hex'),derived=await scrypt(password,salt,64),passwordHash=`${salt}:${Buffer.from(derived).toString('hex')}`;const memoryUser=users.find(user=>user.email.toLowerCase()===row.email.toLowerCase());if(memoryUser)memoryUser.passwordHash=passwordHash;db.transaction(()=>{db.prepare('UPDATE users SET password_hash=? WHERE lower(email)=lower(?)').run(passwordHash,row.email);db.prepare('DELETE FROM auth_sessions WHERE user_id IN (SELECT id FROM users WHERE lower(email)=lower(?))').run(row.email);db.prepare('DELETE FROM account_tokens WHERE token_hash=?').run(hash(token));})();return res.json({message:'Password changed. Sign in again.'});};

module.exports={health,globalSearch,listJobs,createJob,cancelJob,listNotifications,readNotification,usageReport,auditLog,listWebhooks,createWebhook,deleteWebhook,privacyExport,requestEmailVerification,confirmEmailVerification,requestPasswordReset,confirmPasswordReset};
