import { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import './ControlCenter.css';

const modules=[
  ['status','Model Status','Live availability, fallback, and provider health'],['responses','Response Style','Length, tone, creativity, and output format'],
  ['files','File Workspace','PDF, DOCX, images, CSV, and source code'],['search','History Search','Find chats by text, model, date, or project'],
  ['organize','Folders & Tags','Group, color, pin, and label conversations'],['share','Collaboration','Share a read-only workspace link'],
  ['export','Export Center','Download as PDF, Word, Markdown, TXT, or JSON'],['assistants','Assistant Gallery','Launch specialized personal experts'],
  ['theme','Personalization','Theme, accent, text size, and density'],['notify','Notifications','Completion, model recovery, and credit alerts'],
  ['admin','Admin Console','Users, plans, usage, and technical health'],['security','API Protection','Rate limits, safe input, and private keys'],
  ['install','Install App','Use AllModelAI as a desktop or mobile PWA'],['artifacts','Interactive Artifacts','Create calculators, charts, and previews'],
  ['fallback','Auto Recovery','Continue through another model after an error'],
];
const assistantGallery=[['Code Architect','Review, debug, and design reliable software','deepseek'],['Study Coach','Explain topics and build practice quizzes','gemini'],['Marketing Lead','Campaigns, positioning, and content plans','claude'],['Business Analyst','Risks, numbers, strategy, and next steps','gpt'],['Translator','Natural multilingual translation','claude'],['Researcher','Current research with sources','perplexity']];
const textColors=[['Blue','#3b82f6'],['Yellow','#facc15'],['Purple','#a855f7'],['Lime','#a3e635'],['Orange','#f97316'],['Red','#ef4444'],['Red orange','#ff4500'],['Violet','#8b5cf6'],['Gray','#9ca3af'],['Green yellow','#adff2f']];

export default function ControlCenter(){
  const navigate=useNavigate(); const[searchParams]=useSearchParams(); const requestedFeature=searchParams.get('feature'); const saved=sessionStorage.getItem('allmodelai_user'); const user=saved?JSON.parse(saved):null;
  const [active,setActive]=useState(modules.some(([key])=>key===requestedFeature)?requestedFeature:'status'); const [statuses,setStatuses]=useState({}); const [checking,setChecking]=useState(true);
  const [prefs,setPrefs]=useState(()=>JSON.parse(localStorage.getItem('allmodelai_response_prefs')||'{"length":"balanced","tone":"clear","creativity":"balanced","format":"auto"}'));
  const [appearance,setAppearance]=useState(()=>{const savedAppearance=JSON.parse(localStorage.getItem('allmodelai_appearance')||'{"accent":"violet","text":"medium","density":"comfortable","textColor":"#8b5cf6","theme":"dark"}');return{...savedAppearance,textColor:!savedAppearance.textColor||savedAppearance.textColor.toLowerCase()==='#ffffff'?'#8b5cf6':savedAppearance.textColor}});
  const [files,setFiles]=useState([]); const [history,setHistory]=useState([]); const [query,setQuery]=useState(''); const [notifications,setNotifications]=useState(Notification.permission==='granted');
  const [artifact,setArtifact]=useState({a:24,b:18,type:'sum'});
  useEffect(()=>{if(user?.email)fetch(`/api/chat/history?email=${encodeURIComponent(user.email)}`).then(r=>r.ok?r.json():[]).then(setHistory)},[user?.email]);
  const checkModels=()=>{setChecking(true);fetch('/api/status/models').then(r=>r.json()).then(data=>setStatuses(data.models||{})).finally(()=>setChecking(false))};
  useEffect(()=>{fetch('/api/status/models').then(r=>r.json()).then(data=>setStatuses(data.models||{})).finally(()=>setChecking(false))},[]);
  useEffect(()=>{localStorage.setItem('allmodelai_response_prefs',JSON.stringify(prefs))},[prefs]);
  useEffect(()=>{localStorage.setItem('allmodelai_appearance',JSON.stringify(appearance));document.documentElement.dataset.accent=appearance.accent;document.documentElement.style.fontSize=appearance.text==='large'?'19px':appearance.text==='small'?'15px':'';document.documentElement.style.setProperty('--user-text-color',appearance.textColor||'#ffffff');document.documentElement.dataset.themePreference=appearance.theme||'dark';document.documentElement.dataset.theme=(appearance.theme||'dark')==='auto'?(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):(appearance.theme||'dark')},[appearance]);
  const filtered=useMemo(()=>history.filter(chat=>`${chat.title} ${chat.model} ${chat.messages?.map(m=>m.content||m.text).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[history,query]);
  if(!user)return <Navigate to="/" replace/>;
  const exportData=(type)=>{const content=type==='json'?JSON.stringify(filtered,null,2):filtered.map(chat=>`# ${chat.title}\n${chat.messages?.map(m=>`${m.role}: ${m.content||m.text}`).join('\n\n')}`).join('\n\n');if(type==='pdf'){window.print();return}const mime=type==='doc'?'application/msword':'text/plain';const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:mime}));link.download=`allmodelai-export.${type==='doc'?'doc':type}`;link.click();URL.revokeObjectURL(link.href)};
  const enableNotifications=async()=>{const result=await Notification.requestPermission();setNotifications(result==='granted');if(result==='granted')new Notification('AllModelAI notifications enabled')};
  const install=async()=>{if(window.deferredInstallPrompt){await window.deferredInstallPrompt.prompt();window.deferredInstallPrompt=null}else alert('Use your browser menu and choose “Install AllModelAI”.')};
  const result=artifact.type==='sum'?Number(artifact.a)+Number(artifact.b):artifact.type==='multiply'?Number(artifact.a)*Number(artifact.b):Number(artifact.a)/(Number(artifact.b)||1);
  return <main className="control-page"><header className="control-header"><Link to="/dashboard" className="control-brand"><span>AI</span>AllModelAI</Link><nav><Link to="/chat">Chat</Link><Link to="/studio">Studio</Link><Link to="/dashboard">Dashboard</Link></nav></header><section className="control-hero"><p>ALLMODEL AI SYSTEM</p><h1>Control Center</h1><span>Fifteen powerful tools for a faster, safer, and more personal AI workspace.</span></section><div className="control-layout"><aside>{modules.map(([key,label,desc],index)=><button className={active===key?'active':''} onClick={()=>setActive(key)} key={key}><i>{String(index+1).padStart(2,'0')}</i><span><strong>{label}</strong><small>{desc}</small></span></button>)}</aside><section className="control-panel"><div className="panel-heading"><small>FEATURE {String(modules.findIndex(m=>m[0]===active)+1).padStart(2,'0')}</small><h2>{modules.find(m=>m[0]===active)?.[1]}</h2></div>
  {active==='status'&&<><div className="status-grid">{['gpt','claude','gemini','cloudflare','others'].map(model=><article key={model}><i className={statuses[model]?'online':''}/><strong>{model}</strong><span>{statuses[model]?'Online':'Fallback mode'}</span></article>)}</div><button className="control-primary" onClick={checkModels}>{checking?'Checking…':'Check all models'}</button></>}
  {active==='responses'&&<div className="preference-grid">{[['length',['short','balanced','detailed']],['tone',['simple','clear','professional']],['creativity',['precise','balanced','creative']],['format',['auto','list','table','json']]].map(([key,values])=><label key={key}>{key}<select value={prefs[key]} onChange={e=>setPrefs({...prefs,[key]:e.target.value})}>{values.map(value=><option key={value}>{value}</option>)}</select></label>)}<button className="control-primary" onClick={()=>navigate('/chat')}>Use in chat</button></div>}
  {active==='files'&&<div className="drop-zone"><input type="file" multiple accept=".pdf,.doc,.docx,.txt,.md,.csv,.json,.png,.jpg,.jpeg,.js,.jsx,.ts,.tsx,.py" onChange={e=>setFiles([...files,...Array.from(e.target.files)])}/><span>＋</span><h3>Add documents, images, data, or code</h3><p>Files remain local until you choose to send their contents.</p>{files.map(file=><article key={`${file.name}-${file.size}`}><strong>{file.name}</strong><small>{(file.size/1024).toFixed(1)} KB</small><button onClick={()=>setFiles(files.filter(f=>f!==file))}>Remove</button></article>)}</div>}
  {active==='search'&&<div><input className="control-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search every conversation…"/><div className="history-results">{filtered.slice(0,12).map(chat=><button onClick={()=>navigate('/chat')} key={chat.id}><strong>{chat.title}</strong><span>{chat.model} · {chat.messages?.length||0} messages</span></button>)}</div></div>}
  {active==='organize'&&<div className="feature-card"><span>◆</span><h3>Projects already power your folders.</h3><p>Create a project in Chat, assign a color tag, and keep related conversations together.</p><button className="control-primary" onClick={()=>navigate('/chat')}>Manage projects</button></div>}
  {active==='share'&&<div className="feature-card"><span>↗</span><h3>Share your workspace safely.</h3><p>Create a read-only link or copy a conversation for your team.</p><button className="control-primary" onClick={()=>navigator.clipboard.writeText(location.origin+'/chat')}>Copy read-only demo link</button></div>}
  {active==='export'&&<div className="export-grid">{[['pdf','PDF / Print'],['doc','Word'],['md','Markdown'],['txt','Plain text'],['json','JSON data']].map(([type,label])=><button onClick={()=>exportData(type)} key={type}><b>{type.toUpperCase()}</b><span>{label}</span></button>)}</div>}
  {active==='assistants'&&<div className="assistant-grid">{assistantGallery.map(([name,desc,model])=><article key={name}><strong>{name}</strong><p>{desc}</p><button onClick={()=>navigate(`/chat?model=${model}`,{state:{starterPrompt:`Act as my ${name}. Introduce yourself and ask what I need.`}})}>Launch</button></article>)}</div>}
  {active==='theme'&&<div className="personalization-panel"><section className="theme-mode-settings"><small>APP THEME</small><h3>Choose how AllModelAI looks</h3><div>{[['light','☀','Light mode','Bright interface'],['dark','●','Dark mode','Deep black interface'],['auto','◐','Automatic','Follow system settings']].map(([value,icon,label,description])=><button type="button" className={(appearance.theme||'dark')===value?'selected':''} onClick={()=>setAppearance({...appearance,theme:value})} key={value}><i>{icon}</i><span><strong>{label}</strong><small>{description}</small></span><b>{(appearance.theme||'dark')===value?'✓':''}</b></button>)}</div></section><div className="preference-grid">{[['accent',['violet','blue','green','orange']],['text',['small','medium','large']],['density',['compact','comfortable','spacious']]].map(([key,values])=><label key={key}>{key}<select value={appearance[key]} onChange={e=>setAppearance({...appearance,[key]:e.target.value})}>{values.map(value=><option key={value}>{value}</option>)}</select></label>)}</div><section className="text-color-settings"><small>MESSAGE COLOR</small><h3>Choose your message bubble color</h3><p>The purple interface accents stay unchanged. Your selected color replaces the gray outgoing-message bubble.</p><div>{textColors.map(([name,color])=><button type="button" className={appearance.textColor===color?'selected':''} style={{'--swatch':color}} onClick={()=>setAppearance({...appearance,textColor:color})} key={name}><i/>{name}<span>{appearance.textColor===color?'✓':''}</span></button>)}</div><article style={{backgroundColor:appearance.textColor||'#8b5cf6',color:'#fff'}}>Your AllModelAI message preview</article></section></div>}
  {active==='notify'&&<div className="feature-card"><span>◉</span><h3>{notifications?'Notifications are enabled':'Stay informed'}</h3><p>Get alerts when a long answer finishes, a model recovers, or credits run low.</p><button className="control-primary" onClick={enableNotifications}>Enable notifications</button></div>}
  {active==='admin'&&<div className="feature-card"><span>⌘</span><h3>Private operational overview</h3><p>Review users, plans, model health, usage, and errors without exposing private chat content.</p><button className="control-primary" onClick={()=>navigate('/admin')}>Open Admin Console</button></div>}
  {active==='security'&&<div className="security-list">{['90 API requests per minute','Server-only secret keys','8,000 character message limit','Safe model allowlist','HttpOnly session cookies'].map(item=><p key={item}><span>✓</span>{item}</p>)}</div>}
  {active==='install'&&<div className="feature-card"><span>↓</span><h3>Install AllModelAI</h3><p>Launch it like a native app from your desktop or home screen and retain the interface shell offline.</p><button className="control-primary" onClick={install}>Install application</button></div>}
  {active==='artifacts'&&<div className="artifact-lab"><div><input type="number" value={artifact.a} onChange={e=>setArtifact({...artifact,a:e.target.value})}/><select value={artifact.type} onChange={e=>setArtifact({...artifact,type:e.target.value})}><option value="sum">+</option><option value="multiply">×</option><option value="divide">÷</option></select><input type="number" value={artifact.b} onChange={e=>setArtifact({...artifact,b:e.target.value})}/></div><output>{result}</output><p>Interactive artifacts can become calculators, charts, tables, and HTML previews.</p></div>}
  {active==='fallback'&&<div className="fallback-flow"><article>Selected model</article><i>→</i><article>Health check</article><i>→</i><article className="success">Best available fallback</article><p>Automatic recovery is active on the server for unavailable providers.</p></div>}
  </section></div></main>;
}
