import { useMemo, useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import './InnovationHub.css';

const ideas=[
['market','Assistant Marketplace','Install community experts'],['flows','Visual AI Workflows','Connect model steps'],['tasks','Automations','Schedule recurring AI work'],
['knowledge','Knowledge Base','Ground answers in your files'],['canvas','Canvas Editor','Write and refine together'],['code','Code Sandbox','Run JavaScript safely'],
['images','Image Studio','Generate creative visuals'],['slides','Presentation Maker','Build complete slide decks'],['vision','Vision Lab','Analyze screenshots and photos'],
['search','Web Research','Current answers with sources'],['memory','Project Memory','Separate context per project'],['budget','Budget Control','Set spending limits'],
['teams','Team Workspaces','Members, roles, and projects'],['versions','Answer Versions','Compare and restore drafts'],['templates','Project Templates','Start from proven workflows'],
['api','Developer API','Use Smart Router in apps'],['webhooks','Webhook Integrations','Send results to your tools'],['privacy','Privacy Mode','Temporary chats and auto-delete'],
];
const templates=[['App Development','Architecture, code review, QA, launch'],['Study Program','Curriculum, notes, quizzes, progress'],['Marketing Campaign','Audience, positioning, calendar, metrics'],['Research Project','Sources, synthesis, report, citations'],['Business Plan','Market, risks, budget, roadmap'],['Content Studio','Ideas, production, review, publishing']];
const assistants=[['Code Reviewer','DeepSeek','Installed'],['Growth Strategist','Claude','Install'],['Research Analyst','Perplexity','Install'],['Study Coach','Gemini','Installed']];
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};

export default function InnovationHub(){
 const navigate=useNavigate(); const saved=sessionStorage.getItem('allmodelai_user'); const user=saved?JSON.parse(saved):null; const [active,setActive]=useState('market');
 const [tasks,setTasks]=useState(()=>load('allmodelai_tasks',[])); const [task,setTask]=useState(''); const [canvas,setCanvas]=useState(()=>localStorage.getItem('allmodelai_canvas')||'');
 const [code,setCode]=useState("document.body.innerHTML='<h1>Hello from AllModelAI</h1><p>Your code runs in a sandbox.</p>';document.body.style='font-family:system-ui;background:#111827;color:white;padding:24px'"); const [runId,setRunId]=useState(0);
 const [budget,setBudget]=useState(()=>localStorage.getItem('allmodelai_budget')||'25'); const [members,setMembers]=useState(()=>load('allmodelai_team',[])); const [member,setMember]=useState('');
 const [versions,setVersions]=useState(()=>load('allmodelai_versions',[])); const [draft,setDraft]=useState(''); const [webhook,setWebhook]=useState(()=>localStorage.getItem('allmodelai_webhook')||'');
 const [privacy,setPrivacy]=useState(()=>load('allmodelai_privacy',{temporary:true,autoDelete:'24 hours',memory:false})); const [knowledge,setKnowledge]=useState([]);
 const apiKey=useMemo(()=>`amai_demo_${crypto.randomUUID().replaceAll('-','').slice(0,24)}`,[]);
 if(!user)return <Navigate to="/" replace/>;
 const saveTask=()=>{if(!task.trim())return;const next=[...tasks,{id:Date.now(),name:task,frequency:'Weekly'}];setTasks(next);localStorage.setItem('allmodelai_tasks',JSON.stringify(next));setTask('')};
 const addMember=()=>{if(!member.trim())return;const next=[...members,{email:member,role:'Editor'}];setMembers(next);localStorage.setItem('allmodelai_team',JSON.stringify(next));setMember('')};
 const addVersion=()=>{if(!draft.trim())return;const next=[{id:Date.now(),text:draft,date:new Date().toLocaleString()},...versions];setVersions(next);localStorage.setItem('allmodelai_versions',JSON.stringify(next))};
 const panelTitle=ideas.find(([key])=>key===active)?.[1];
 return <main className="innovation-page"><header><Link to="/dashboard" className="innovation-brand"><span>AI</span>AllModelAI</Link><nav><Link to="/chat">Chat</Link><Link to="/control-center">Control Center</Link><Link to="/dashboard">Dashboard</Link></nav></header><section className="innovation-hero"><div><p>NEXT-GENERATION WORKSPACE</p><h1>Innovation Hub</h1><span>Eighteen advanced capabilities for building, automating, and scaling with AI.</span></div><b>18</b></section><div className="innovation-layout"><aside>{ideas.map(([key,name,desc],index)=><button className={active===key?'active':''} onClick={()=>setActive(key)} key={key}><i>{index+1}</i><span><strong>{name}</strong><small>{desc}</small></span></button>)}</aside><section className="innovation-panel"><small>INNOVATION MODULE</small><h2>{panelTitle}</h2>
 {active==='market'&&<div className="market-grid">{assistants.map(([name,model,status])=><article key={name}><span>✦</span><h3>{name}</h3><p>Powered by {model}</p><button>{status}</button></article>)}</div>}
 {active==='flows'&&<div><div className="visual-flow"><article>Input</article><i>→</i><article>GPT Draft</article><i>→</i><article>Claude Review</article><i>→</i><article>Final</article></div><button className="innovation-primary" onClick={()=>navigate('/studio')}>Open workflow builder</button></div>}
 {active==='tasks'&&<div><div className="inline-form"><input value={task} onChange={e=>setTask(e.target.value)} placeholder="Example: Monday market report"/><button onClick={saveTask}>Schedule</button></div><div className="record-list">{tasks.map(item=><article key={item.id}><strong>{item.name}</strong><span>{item.frequency}</span></article>)}</div></div>}
 {active==='knowledge'&&<div className="upload-lab"><input type="file" multiple accept=".pdf,.doc,.docx,.txt,.md,.csv" onChange={e=>setKnowledge([...knowledge,...Array.from(e.target.files)])}/><h3>Project knowledge</h3><p>Choose the documents the assistant must use for grounded answers.</p>{knowledge.map(file=><article key={file.name}><strong>{file.name}</strong><span>Ready</span></article>)}</div>}
 {active==='canvas'&&<div><textarea className="canvas-editor" value={canvas} onChange={e=>setCanvas(e.target.value)} placeholder="Write your document, plan, or draft here…"/><button className="innovation-primary" onClick={()=>localStorage.setItem('allmodelai_canvas',canvas)}>Save canvas</button><button className="innovation-secondary" onClick={()=>navigate('/chat',{state:{starterPrompt:`Improve this canvas document:\n\n${canvas}`}})}>Improve with AI</button></div>}
 {active==='code'&&<div className="code-lab"><textarea value={code} onChange={e=>setCode(e.target.value)}/><button onClick={()=>setRunId(runId+1)}>Run safely</button><iframe key={runId} sandbox="allow-scripts" title="Code result" srcDoc={`<!doctype html><body><script>${code.replaceAll('</script>','<\\/script>')}<\/script></body>`}/></div>}
 {active==='images'&&<Action icon="◈" title="AI Image Studio" text="Describe an image, choose a model, and keep generations in your workspace." action="Create image" onClick={()=>navigate('/chat',{state:{starterPrompt:'Create an image of: '}})}/>}
 {active==='slides'&&<Action icon="▤" title="Presentation Maker" text="Generate a structured deck with titles, speaker notes, and visual suggestions." action="Create presentation" onClick={()=>navigate('/chat',{state:{starterPrompt:'Create a complete presentation about: '}})}/>}
 {active==='vision'&&<div className="upload-lab"><input type="file" accept="image/*"/><h3>Analyze an image</h3><p>Upload a screenshot or photo, then send it to a multimodal model from Chat.</p><button className="innovation-primary" onClick={()=>navigate('/chat?model=gemini')}>Open Vision Chat</button></div>}
 {active==='search'&&<Action icon="◎" title="Research the live web" text="Smart Router selects a research model and requests citations, dates, and direct source links." action="Start research" onClick={()=>navigate('/chat?model=perplexity',{state:{starterPrompt:'Research this using current reliable web sources and cite every important claim: '}})}/>}
 {active==='memory'&&<Action icon="◆" title="Independent project memory" text="Projects already keep their own instructions, documents, and context in Workspace Studio." action="Manage memory" onClick={()=>navigate('/studio')}/>}
 {active==='budget'&&<div className="budget-card"><label>Monthly AI limit, USD<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)}/></label><div><span>Used this month</span><strong>$0.00 / ${Number(budget||0).toFixed(2)}</strong><i style={{width:'2%'}}/></div><button className="innovation-primary" onClick={()=>localStorage.setItem('allmodelai_budget',budget)}>Save limit</button></div>}
 {active==='teams'&&<div><div className="inline-form"><input value={member} onChange={e=>setMember(e.target.value)} placeholder="teammate@example.com"/><button onClick={addMember}>Invite</button></div><div className="record-list">{members.map(item=><article key={item.email}><strong>{item.email}</strong><span>{item.role}</span></article>)}</div></div>}
 {active==='versions'&&<div><textarea className="canvas-editor small" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Paste an answer or draft…"/><button className="innovation-primary" onClick={addVersion}>Save version</button><div className="record-list">{versions.map((item,index)=><article key={item.id}><strong>Version {versions.length-index}</strong><span>{item.date}</span><button onClick={()=>setDraft(item.text)}>Restore</button></article>)}</div></div>}
 {active==='templates'&&<div className="template-market">{templates.map(([name,desc])=><article key={name}><h3>{name}</h3><p>{desc}</p><button onClick={()=>navigate('/studio')}>Use template</button></article>)}</div>}
 {active==='api'&&<div className="api-card"><p>Your local demonstration API key</p><code>{apiKey}</code><pre>{`fetch('/api/chat', {\n  method: 'POST',\n  body: JSON.stringify({ model: 'smart', messages })\n})`}</pre><small>Demo key only. Production issuance requires server-side key management.</small></div>}
 {active==='webhooks'&&<div className="webhook-card"><label>Destination URL<input value={webhook} onChange={e=>setWebhook(e.target.value)} placeholder="https://example.com/allmodelai"/></label><div>{['Telegram','Discord','Slack','Custom server'].map(name=><button key={name}>{name}</button>)}</div><button className="innovation-primary" onClick={()=>localStorage.setItem('allmodelai_webhook',webhook)}>Save integration</button><p>Local mode saves configuration but does not send external messages.</p></div>}
 {active==='privacy'&&<div className="privacy-grid">{[['temporary','Temporary chats'],['memory','Disable memory']].map(([key,label])=><label key={key}><span><strong>{label}</strong><small>Protect sensitive conversations</small></span><input type="checkbox" checked={privacy[key]} onChange={e=>{const next={...privacy,[key]:e.target.checked};setPrivacy(next);localStorage.setItem('allmodelai_privacy',JSON.stringify(next))}}/></label>)}<label><span><strong>Auto-delete</strong><small>Remove temporary history</small></span><select value={privacy.autoDelete} onChange={e=>{const next={...privacy,autoDelete:e.target.value};setPrivacy(next);localStorage.setItem('allmodelai_privacy',JSON.stringify(next))}}><option>1 hour</option><option>24 hours</option><option>7 days</option></select></label></div>}
 </section></div></main>;
}
function Action({icon,title,text,action,onClick}){return <div className="innovation-action"><span>{icon}</span><h3>{title}</h3><p>{text}</p><button className="innovation-primary" onClick={onClick}>{action}</button></div>}
