// Chat controls. Keep user messages and model responses in their original language.
export const CHAT_STRINGS = {
  "ru": {
    "Change input and message colors": "Цвета поля ввода и сообщений",
    "Not saved to history": "Не сохраняется в истории",
    "Organize chats by goal": "Группируйте чаты по цели",
    "AI Arena": "Арена ИИ",
    "Compare answers side by side": "Сравнивайте ответы рядом",
    "Smart Router": "Умный маршрутизатор",
    "Choose the best AI automatically": "Автоматический выбор лучшего ИИ",
    "Generate image": "Создать изображение",
    "Create an image from text": "Изображение по описанию",
    "Prompt library": "Библиотека запросов",
    "Ready-to-use templates": "Готовые шаблоны",
    "Export chat": "Экспорт чата",
    "Download this conversation": "Скачать этот разговор",
    "AI instructions": "Инструкции для ИИ",
    "Set language, style, and behavior": "Язык, стиль и поведение",
    "Backup workspace": "Резервная копия",
    "Download chats and settings": "Скачать чаты и настройки",
    "Projects": "Проекты",
    "Favorites": "Избранное",
    "Your saved chats will appear here.": "Здесь появятся сохранённые чаты.",
    "No matching conversations.": "Подходящих разговоров нет.",
    "AI Platform": "Платформа ИИ",
    "Website Builder": "Конструктор сайтов",
    "Workspace Studio": "Рабочая студия",
    "Control Center": "Центр управления",
    "Model library": "Библиотека моделей",
    "What can I help you create?": "Что вы хотите создать?",
    "Start with your own question, upload a screenshot (Ctrl+V), or choose one of these ideas.": "Задайте вопрос, загрузите снимок экрана (Ctrl+V) или выберите одну из идей.",
    "User": "Пользователь",
    "Developer": "Разработчик",
    "All models": "Все модели",
    "5 free models": "5 бесплатных моделей",
    "Saving…": "Сохранение…",
    "Listening…": "Слушаю…",
    "Generating — you can keep typing": "Генерация — можно продолжать ввод",
    "Screenshot ready to send": "Снимок экрана готов к отправке",
    "Ready · replies in your language": "Готово · ответы на вашем языке",
    "Open sidebar": "Открыть боковую панель",
    "Close sidebar": "Закрыть боковую панель",
    "Chat navigation": "Навигация чата",
    "Theme settings": "Настройки темы",
    "Sign out": "Выйти",
    "Choose AI model": "Выберите модель ИИ",
    "Chat message": "Сообщение",
    "Open tools": "Открыть инструменты",
    "Use microphone": "Включить микрофон",
    "Stop generating": "Остановить генерацию",
    "Upload screenshot or image": "Загрузить снимок экрана или изображение",
    "Export current conversation": "Экспорт текущего разговора",
    "Subscription": "Подписка",
    "Copy": "Копировать",
    "Download": "Скачать",
    "Retry": "Повторить",
    "Feedback": "Отзыв",
    "Share": "Поделиться",
    "Read aloud": "Прочитать вслух",
    "Save": "Сохранить",
    "Saved": "Сохранено",
    "New chat": "Новый чат",
    "Checking your session...": "Проверка сеанса...",
    "Could not connect. Please try again.": "Не удалось подключиться. Попробуйте ещё раз."
  },
  "uk": {
    "Change input and message colors": "Кольори поля введення та повідомлень",
    "Not saved to history": "Не зберігається в історії",
    "Organize chats by goal": "Групуйте чати за метою",
    "AI Arena": "Арена ШІ",
    "Compare answers side by side": "Порівнюйте відповіді поруч",
    "Smart Router": "Розумний маршрутизатор",
    "Choose the best AI automatically": "Автоматичний вибір найкращого ШІ",
    "Generate image": "Створити зображення",
    "Create an image from text": "Зображення за описом",
    "Prompt library": "Бібліотека запитів",
    "Ready-to-use templates": "Готові шаблони",
    "Export chat": "Експорт чату",
    "Download this conversation": "Завантажити цю розмову",
    "AI instructions": "Інструкції для ШІ",
    "Set language, style, and behavior": "Мова, стиль і поведінка",
    "Backup workspace": "Резервна копія",
    "Download chats and settings": "Завантажити чати й налаштування",
    "Projects": "Проєкти",
    "Favorites": "Обране",
    "Your saved chats will appear here.": "Тут з’являться збережені чати.",
    "No matching conversations.": "Відповідних розмов немає.",
    "AI Platform": "Платформа ШІ",
    "Website Builder": "Конструктор сайтів",
    "Workspace Studio": "Робоча студія",
    "Control Center": "Центр керування",
    "Model library": "Бібліотека моделей",
    "What can I help you create?": "Що ви хочете створити?",
    "Start with your own question, upload a screenshot (Ctrl+V), or choose one of these ideas.": "Поставте запитання, завантажте знімок екрана (Ctrl+V) або виберіть одну з ідей.",
    "User": "Користувач",
    "Developer": "Розробник",
    "All models": "Усі моделі",
    "5 free models": "5 безкоштовних моделей",
    "Saving…": "Збереження…",
    "Listening…": "Слухаю…",
    "Generating — you can keep typing": "Генерація — можна продовжувати введення",
    "Screenshot ready to send": "Знімок екрана готовий до надсилання",
    "Ready · replies in your language": "Готово · відповіді вашою мовою",
    "Open sidebar": "Відкрити бічну панель",
    "Close sidebar": "Закрити бічну панель",
    "Chat navigation": "Навігація чату",
    "Theme settings": "Налаштування теми",
    "Sign out": "Вийти",
    "Choose AI model": "Виберіть модель ШІ",
    "Chat message": "Повідомлення",
    "Open tools": "Відкрити інструменти",
    "Use microphone": "Увімкнути мікрофон",
    "Stop generating": "Зупинити генерацію",
    "Upload screenshot or image": "Завантажити знімок екрана або зображення",
    "Export current conversation": "Експорт поточної розмови",
    "Subscription": "Підписка",
    "Copy": "Копіювати",
    "Download": "Завантажити",
    "Retry": "Повторити",
    "Feedback": "Відгук",
    "Share": "Поділитися",
    "Read aloud": "Прочитати вголос",
    "Save": "Зберегти",
    "Saved": "Збережено",
    "New chat": "Новий чат",
    "Checking your session...": "Перевірка сеансу...",
    "Could not connect. Please try again.": "Не вдалося підключитися. Спробуйте ще раз."
  },
  "fr": {
    "Change input and message colors": "Couleurs de saisie et des messages",
    "Not saved to history": "Non enregistré dans l’historique",
    "Organize chats by goal": "Organiser les chats par objectif",
    "AI Arena": "Arène IA",
    "Compare answers side by side": "Comparer les réponses côte à côte",
    "Smart Router": "Routeur intelligent",
    "Choose the best AI automatically": "Choisir automatiquement la meilleure IA",
    "Generate image": "Générer une image",
    "Create an image from text": "Créer une image à partir de texte",
    "Prompt library": "Bibliothèque de prompts",
    "Ready-to-use templates": "Modèles prêts à l’emploi",
    "Export chat": "Exporter le chat",
    "Download this conversation": "Télécharger cette conversation",
    "AI instructions": "Instructions pour l’IA",
    "Set language, style, and behavior": "Langue, style et comportement",
    "Backup workspace": "Sauvegarder l’espace de travail",
    "Download chats and settings": "Télécharger les chats et paramètres",
    "Projects": "Projets",
    "Favorites": "Favoris",
    "Your saved chats will appear here.": "Vos conversations enregistrées apparaîtront ici.",
    "No matching conversations.": "Aucune conversation correspondante.",
    "AI Platform": "Plateforme IA",
    "Website Builder": "Créateur de sites",
    "Workspace Studio": "Studio de travail",
    "Control Center": "Centre de contrôle",
    "Model library": "Bibliothèque de modèles",
    "What can I help you create?": "Que souhaitez-vous créer ?",
    "Start with your own question, upload a screenshot (Ctrl+V), or choose one of these ideas.": "Posez une question, ajoutez une capture d’écran (Ctrl+V) ou choisissez une idée.",
    "User": "Utilisateur",
    "Developer": "Développeur",
    "All models": "Tous les modèles",
    "5 free models": "5 modèles gratuits",
    "Saving…": "Enregistrement…",
    "Listening…": "À l’écoute…",
    "Generating — you can keep typing": "Génération — vous pouvez continuer à écrire",
    "Screenshot ready to send": "Capture prête à envoyer",
    "Ready · replies in your language": "Prêt · réponses dans votre langue",
    "Open sidebar": "Ouvrir le panneau latéral",
    "Close sidebar": "Fermer le panneau latéral",
    "Chat navigation": "Navigation du chat",
    "Theme settings": "Paramètres du thème",
    "Sign out": "Se déconnecter",
    "Choose AI model": "Choisir un modèle IA",
    "Chat message": "Message du chat",
    "Open tools": "Ouvrir les outils",
    "Use microphone": "Utiliser le microphone",
    "Stop generating": "Arrêter la génération",
    "Upload screenshot or image": "Importer une capture ou une image",
    "Export current conversation": "Exporter la conversation actuelle",
    "Subscription": "Abonnement",
    "Copy": "Copier",
    "Download": "Télécharger",
    "Retry": "Réessayer",
    "Feedback": "Avis",
    "Share": "Partager",
    "Read aloud": "Lire à voix haute",
    "Save": "Enregistrer",
    "Saved": "Enregistré",
    "New chat": "Nouveau chat",
    "Checking your session...": "Vérification de votre session...",
    "Could not connect. Please try again.": "Connexion impossible. Veuillez réessayer."
  },
  "en": {
    "Change input and message colors": "Change input and message colors",
    "Not saved to history": "Not saved to history",
    "Organize chats by goal": "Organize chats by goal",
    "AI Arena": "AI Arena",
    "Compare answers side by side": "Compare answers side by side",
    "Smart Router": "Smart Router",
    "Choose the best AI automatically": "Choose the best AI automatically",
    "Generate image": "Generate image",
    "Create an image from text": "Create an image from text",
    "Prompt library": "Prompt library",
    "Ready-to-use templates": "Ready-to-use templates",
    "Export chat": "Export chat",
    "Download this conversation": "Download this conversation",
    "AI instructions": "AI instructions",
    "Set language, style, and behavior": "Set language, style, and behavior",
    "Backup workspace": "Backup workspace",
    "Download chats and settings": "Download chats and settings",
    "Projects": "Projects",
    "Favorites": "Favorites",
    "Your saved chats will appear here.": "Your saved chats will appear here.",
    "No matching conversations.": "No matching conversations.",
    "AI Platform": "AI Platform",
    "Website Builder": "Website Builder",
    "Workspace Studio": "Workspace Studio",
    "Control Center": "Control Center",
    "Model library": "Model library",
    "What can I help you create?": "What can I help you create?",
    "Start with your own question, upload a screenshot (Ctrl+V), or choose one of these ideas.": "Start with your own question, upload a screenshot (Ctrl+V), or choose one of these ideas.",
    "User": "User",
    "Developer": "Developer",
    "All models": "All models",
    "5 free models": "5 free models",
    "Saving…": "Saving…",
    "Listening…": "Listening…",
    "Generating — you can keep typing": "Generating — you can keep typing",
    "Screenshot ready to send": "Screenshot ready to send",
    "Ready · replies in your language": "Ready · replies in your language",
    "Open sidebar": "Open sidebar",
    "Close sidebar": "Close sidebar",
    "Chat navigation": "Chat navigation",
    "Theme settings": "Theme settings",
    "Sign out": "Sign out",
    "Choose AI model": "Choose AI model",
    "Chat message": "Chat message",
    "Open tools": "Open tools",
    "Use microphone": "Use microphone",
    "Stop generating": "Stop generating",
    "Upload screenshot or image": "Upload screenshot or image",
    "Export current conversation": "Export current conversation",
    "Subscription": "Subscription",
    "Copy": "Copy",
    "Download": "Download",
    "Retry": "Retry",
    "Feedback": "Feedback",
    "Share": "Share",
    "Read aloud": "Read aloud",
    "Save": "Save",
    "Saved": "Saved",
    "New chat": "New chat",
    "Checking your session...": "Checking your session...",
    "Could not connect. Please try again.": "Could not connect. Please try again."
  }
};
