// Explicit translations for settings and shared navigation. User content is never translated.
export const INTERFACE_STRINGS = {
  "en": {
    "backChat": "Back to chat",
    "personalChat": "PERSONAL CHAT",
    "settings": "Settings",
    "appearance": "Appearance",
    "settingsIntro": "Make your AllModelAI chat feel like your own.",
    "inputField": "INPUT FIELD",
    "inputTitle": "Choose input color",
    "inputDescription": "Change the background of the field where you type messages.",
    "themeTitle": "Choose your theme",
    "themeDescription": "Change the workspace appearance while keeping the violet AllModelAI accents.",
    "bubbleTitle": "Choose your color",
    "bubbleDescription": "Your selected color replaces the gray outgoing-message block.",
    "liveResult": "LIVE RESULT",
    "previewTitle": "Your chat preview",
    "autoSaved": "Changes are saved automatically.",
    "previewHello": "Hello, {name}! What would you like to build today?",
    "previewPrompt": "Help me create a great new project",
    "messagePlaceholder": "Message AllModelAI...",
    "selected": "Selected",
    "custom": "Custom",
    "creator": "creator",
    "light": "Light",
    "dark": "Dark",
    "auto": "System",
    "bright": "Bright and clean",
    "deepBlack": "Deep black workspace",
    "matchDevice": "Match your device",
    "Black": "Black",
    "Graphite": "Graphite",
    "Blue": "Blue",
    "Yellow": "Yellow",
    "Purple": "Purple",
    "Lime": "Lime",
    "Orange": "Orange",
    "Red": "Red",
    "Red orange": "Red orange",
    "Violet": "Violet",
    "Gray": "Gray",
    "Green yellow": "Green yellow",
    "Dashboard": "Dashboard",
    "Open chat": "Open chat",
    "Home": "Home",
    "About": "About",
    "Pricing": "Pricing",
    "Models": "Models",
    "Sign in": "Sign in",
    "Sign up": "Sign up",
    "New conversation": "New conversation",
    "Chat settings": "Chat settings",
    "Temporary chat": "Temporary chat",
    "New project": "New project",
    "Saved conversations": "Saved conversations",
    "Search saved chats": "Search saved chats",
    "Settings": "Settings",
    "Send message": "Send message",
    "Model": "Model",
    "Chatting with": "Chatting with",
    "Online": "Online",
    "API needed": "API needed",
    "Ready": "Ready",
    "Edit": "Edit",
    "Delete": "Delete",
    "Cancel": "Cancel",
    "Open question history panel": "Open question history panel",
    "Your question history": "Your question history",
    "questions": "questions",
    "Rename question": "Rename question",
    "Delete this question from history?": "Delete this question from history?",
    "Question history": "Question history",
    "Close": "Close",
    "Open sidebar": "Open sidebar",
    "Close sidebar": "Close sidebar",
    "Collapse sidebar": "Collapse sidebar",
    "Quick navigation": "Quick navigation",
    "Projects": "Projects",
    "Generate image": "Generate image",
    "Smart Router": "Smart Router"
  },
  "ru": {
    "backChat": "Назад в чат",
    "personalChat": "ЛИЧНЫЙ ЧАТ",
    "settings": "Настройки",
    "appearance": "Оформление",
    "settingsIntro": "Настройте чат AllModelAI под себя.",
    "inputField": "ПОЛЕ ВВОДА",
    "inputTitle": "Цвет поля ввода",
    "inputDescription": "Измените фон поля, в котором вы пишете сообщения.",
    "themeTitle": "Выберите тему",
    "themeDescription": "Измените оформление, сохранив фиолетовые акценты AllModelAI.",
    "bubbleTitle": "Выберите цвет сообщений",
    "bubbleDescription": "Выбранный цвет заменит серый фон ваших сообщений.",
    "liveResult": "ПРЕДПРОСМОТР",
    "previewTitle": "Как будет выглядеть чат",
    "autoSaved": "Изменения сохраняются автоматически.",
    "previewHello": "Привет, {name}! Что вы хотите создать сегодня?",
    "previewPrompt": "Помоги мне создать отличный новый проект",
    "messagePlaceholder": "Сообщение AllModelAI...",
    "selected": "Выбрано",
    "custom": "Свой цвет",
    "creator": "автор",
    "light": "Светлая",
    "dark": "Тёмная",
    "auto": "Системная",
    "bright": "Светло и лаконично",
    "deepBlack": "Тёмное рабочее пространство",
    "matchDevice": "Как на вашем устройстве",
    "Black": "Чёрный",
    "Graphite": "Графитовый",
    "Blue": "Синий",
    "Yellow": "Жёлтый",
    "Purple": "Пурпурный",
    "Lime": "Лаймовый",
    "Orange": "Оранжевый",
    "Red": "Красный",
    "Red orange": "Красно-оранжевый",
    "Violet": "Фиолетовый",
    "Gray": "Серый",
    "Green yellow": "Жёлто-зелёный",
    "Dashboard": "Панель управления",
    "Open chat": "Открыть чат",
    "Home": "Главная",
    "About": "О проекте",
    "Pricing": "Тарифы",
    "Models": "Модели",
    "Sign in": "Войти",
    "Sign up": "Регистрация",
    "New conversation": "Новый разговор",
    "Chat settings": "Настройки чата",
    "Temporary chat": "Временный чат",
    "New project": "Новый проект",
    "Saved conversations": "Сохранённые разговоры",
    "Search saved chats": "Поиск по чатам",
    "Settings": "Настройки",
    "Send message": "Отправить сообщение",
    "Model": "Модель",
    "Chatting with": "Чат с",
    "Online": "В сети",
    "API needed": "Нужен API",
    "Ready": "Готово",
    "Edit": "Изменить",
    "Delete": "Удалить",
    "Cancel": "Отмена",
    "Open question history panel": "Открыть историю вопросов",
    "Your question history": "История ваших вопросов",
    "questions": "вопросов",
    "Rename question": "Переименовать вопрос",
    "Delete this question from history?": "Удалить этот вопрос из истории?",
    "Question history": "История вопросов",
    "Close": "Закрыть",
    "Open sidebar": "Открыть боковую панель",
    "Close sidebar": "Закрыть боковую панель",
    "Collapse sidebar": "Свернуть панель",
    "Quick navigation": "Быстрая навигация",
    "Projects": "Проекты",
    "Generate image": "Создать изображение",
    "Smart Router": "Smart Router"
  },
  "uk": {
    "backChat": "Назад до чату",
    "personalChat": "ОСОБИСТИЙ ЧАТ",
    "settings": "Налаштування",
    "appearance": "Оформлення",
    "settingsIntro": "Налаштуйте чат AllModelAI під себе.",
    "inputField": "ПОЛЕ ВВЕДЕННЯ",
    "inputTitle": "Колір поля введення",
    "inputDescription": "Змініть фон поля, у якому ви пишете повідомлення.",
    "themeTitle": "Виберіть тему",
    "themeDescription": "Змініть оформлення, зберігши фіолетові акценти AllModelAI.",
    "bubbleTitle": "Виберіть колір повідомлень",
    "bubbleDescription": "Вибраний колір замінить сірий фон ваших повідомлень.",
    "liveResult": "ПОПЕРЕДНІЙ ПЕРЕГЛЯД",
    "previewTitle": "Як виглядатиме чат",
    "autoSaved": "Зміни зберігаються автоматично.",
    "previewHello": "Вітаю, {name}! Що ви хочете створити сьогодні?",
    "previewPrompt": "Допоможи мені створити чудовий новий проєкт",
    "messagePlaceholder": "Повідомлення AllModelAI...",
    "selected": "Вибрано",
    "custom": "Власний колір",
    "creator": "автор",
    "light": "Світла",
    "dark": "Темна",
    "auto": "Системна",
    "bright": "Світло й лаконічно",
    "deepBlack": "Темний робочий простір",
    "matchDevice": "Як на вашому пристрої",
    "Black": "Чорний",
    "Graphite": "Графітовий",
    "Blue": "Синій",
    "Yellow": "Жовтий",
    "Purple": "Пурпуровий",
    "Lime": "Лаймовий",
    "Orange": "Помаранчевий",
    "Red": "Червоний",
    "Red orange": "Червоно-помаранчевий",
    "Violet": "Фіолетовий",
    "Gray": "Сірий",
    "Green yellow": "Жовто-зелений",
    "Dashboard": "Панель керування",
    "Open chat": "Відкрити чат",
    "Home": "Головна",
    "About": "Про проєкт",
    "Pricing": "Тарифи",
    "Models": "Моделі",
    "Sign in": "Увійти",
    "Sign up": "Реєстрація",
    "New conversation": "Нова розмова",
    "Chat settings": "Налаштування чату",
    "Temporary chat": "Тимчасовий чат",
    "New project": "Новий проєкт",
    "Saved conversations": "Збережені розмови",
    "Search saved chats": "Пошук у чатах",
    "Settings": "Налаштування",
    "Send message": "Надіслати повідомлення",
    "Model": "Модель",
    "Chatting with": "Чат із",
    "Online": "У мережі",
    "API needed": "Потрібен API",
    "Ready": "Готово",
    "Edit": "Змінити",
    "Delete": "Видалити",
    "Cancel": "Скасувати"
  },
  "fr": {
    "backChat": "Retour au chat",
    "personalChat": "CHAT PERSONNEL",
    "settings": "Paramètres",
    "appearance": "Apparence",
    "settingsIntro": "Personnalisez votre chat AllModelAI.",
    "inputField": "CHAMP DE SAISIE",
    "inputTitle": "Couleur du champ de saisie",
    "inputDescription": "Modifiez le fond du champ où vous écrivez vos messages.",
    "themeTitle": "Choisissez votre thème",
    "themeDescription": "Modifiez l’apparence en conservant les accents violets d’AllModelAI.",
    "bubbleTitle": "Choisissez votre couleur",
    "bubbleDescription": "La couleur choisie remplace le fond gris de vos messages.",
    "liveResult": "APERÇU",
    "previewTitle": "Aperçu de votre chat",
    "autoSaved": "Les modifications sont enregistrées automatiquement.",
    "previewHello": "Bonjour, {name} ! Que souhaitez-vous créer aujourd’hui ?",
    "previewPrompt": "Aide-moi à créer un excellent nouveau projet",
    "messagePlaceholder": "Écrire à AllModelAI...",
    "selected": "Sélectionné",
    "custom": "Personnalisé",
    "creator": "créateur",
    "light": "Clair",
    "dark": "Sombre",
    "auto": "Système",
    "bright": "Clair et épuré",
    "deepBlack": "Espace de travail noir",
    "matchDevice": "Suivre votre appareil",
    "Black": "Noir",
    "Graphite": "Graphite",
    "Blue": "Bleu",
    "Yellow": "Jaune",
    "Purple": "Pourpre",
    "Lime": "Citron vert",
    "Orange": "Orange",
    "Red": "Rouge",
    "Red orange": "Rouge orangé",
    "Violet": "Violet",
    "Gray": "Gris",
    "Green yellow": "Jaune-vert",
    "Dashboard": "Tableau de bord",
    "Open chat": "Ouvrir le chat",
    "Home": "Accueil",
    "About": "À propos",
    "Pricing": "Tarifs",
    "Models": "Modèles",
    "Sign in": "Se connecter",
    "Sign up": "S’inscrire",
    "New conversation": "Nouvelle conversation",
    "Chat settings": "Paramètres du chat",
    "Temporary chat": "Chat temporaire",
    "New project": "Nouveau projet",
    "Saved conversations": "Conversations enregistrées",
    "Search saved chats": "Rechercher des conversations",
    "Settings": "Paramètres",
    "Send message": "Envoyer le message",
    "Model": "Modèle",
    "Chatting with": "Discussion avec",
    "Online": "En ligne",
    "API needed": "API requise",
    "Ready": "Prêt",
    "Edit": "Modifier",
    "Delete": "Supprimer",
    "Cancel": "Annuler"
  },
  "pl": {
    "backChat": "Powrót do czatu",
    "personalChat": "CZAT OSOBISTY",
    "settings": "Ustawienia",
    "appearance": "Wygląd",
    "settingsIntro": "Dostosuj czat AllModelAI do siebie.",
    "inputField": "POLE TEKSTOWE",
    "inputTitle": "Kolor pola tekstowego",
    "inputDescription": "Zmień tło pola, w którym piszesz wiadomości.",
    "themeTitle": "Wybierz motyw",
    "themeDescription": "Zmień wygląd, zachowując fioletowe akcenty AllModelAI.",
    "bubbleTitle": "Wybierz kolor",
    "bubbleDescription": "Wybrany kolor zastąpi szare tło Twoich wiadomości.",
    "liveResult": "PODGLĄD",
    "previewTitle": "Podgląd czatu",
    "autoSaved": "Zmiany są zapisywane automatycznie.",
    "previewHello": "Witaj, {name}! Co chcesz dziś stworzyć?",
    "previewPrompt": "Pomóż mi stworzyć świetny nowy projekt",
    "messagePlaceholder": "Napisz do AllModelAI...",
    "selected": "Wybrano",
    "custom": "Własny",
    "creator": "twórca",
    "light": "Jasny",
    "dark": "Ciemny",
    "auto": "Systemowy",
    "bright": "Jasno i przejrzyście",
    "deepBlack": "Ciemna przestrzeń robocza",
    "matchDevice": "Zgodnie z urządzeniem",
    "Black": "Czarny",
    "Graphite": "Grafitowy",
    "Blue": "Niebieski",
    "Yellow": "Żółty",
    "Purple": "Purpurowy",
    "Lime": "Limonkowy",
    "Orange": "Pomarańczowy",
    "Red": "Czerwony",
    "Red orange": "Czerwonopomarańczowy",
    "Violet": "Fioletowy",
    "Gray": "Szary",
    "Green yellow": "Żółtozielony",
    "Dashboard": "Panel",
    "Open chat": "Otwórz czat",
    "Home": "Strona główna",
    "About": "O nas",
    "Pricing": "Cennik",
    "Models": "Modele",
    "Sign in": "Zaloguj się",
    "Sign up": "Zarejestruj się",
    "New conversation": "Nowa rozmowa",
    "Chat settings": "Ustawienia czatu",
    "Temporary chat": "Czat tymczasowy",
    "New project": "Nowy projekt",
    "Saved conversations": "Zapisane rozmowy",
    "Search saved chats": "Szukaj rozmów",
    "Settings": "Ustawienia",
    "Send message": "Wyślij wiadomość",
    "Model": "Model",
    "Chatting with": "Rozmowa z",
    "Online": "Online",
    "API needed": "Wymagane API",
    "Ready": "Gotowe",
    "Edit": "Edytuj",
    "Delete": "Usuń",
    "Cancel": "Anuluj"
  },
  "de": {
    "backChat": "Zurück zum Chat",
    "personalChat": "PERSÖNLICHER CHAT",
    "settings": "Einstellungen",
    "appearance": "Darstellung",
    "settingsIntro": "Gestalte deinen AllModelAI-Chat ganz persönlich.",
    "inputField": "EINGABEFELD",
    "inputTitle": "Farbe des Eingabefelds",
    "inputDescription": "Ändere den Hintergrund des Felds für deine Nachrichten.",
    "themeTitle": "Wähle dein Design",
    "themeDescription": "Ändere die Darstellung mit den violetten AllModelAI-Akzenten.",
    "bubbleTitle": "Wähle deine Farbe",
    "bubbleDescription": "Die gewählte Farbe ersetzt den grauen Hintergrund deiner Nachrichten.",
    "liveResult": "VORSCHAU",
    "previewTitle": "Deine Chat-Vorschau",
    "autoSaved": "Änderungen werden automatisch gespeichert.",
    "previewHello": "Hallo, {name}! Was möchtest du heute erstellen?",
    "previewPrompt": "Hilf mir, ein tolles neues Projekt zu erstellen",
    "messagePlaceholder": "Nachricht an AllModelAI...",
    "selected": "Ausgewählt",
    "custom": "Benutzerdefiniert",
    "creator": "Kreativer",
    "light": "Hell",
    "dark": "Dunkel",
    "auto": "System",
    "bright": "Hell und klar",
    "deepBlack": "Dunkler Arbeitsbereich",
    "matchDevice": "Wie auf deinem Gerät",
    "Black": "Schwarz",
    "Graphite": "Graphit",
    "Blue": "Blau",
    "Yellow": "Gelb",
    "Purple": "Purpur",
    "Lime": "Limette",
    "Orange": "Orange",
    "Red": "Rot",
    "Red orange": "Rotorange",
    "Violet": "Violett",
    "Gray": "Grau",
    "Green yellow": "Gelbgrün",
    "Dashboard": "Übersicht",
    "Open chat": "Chat öffnen",
    "Home": "Startseite",
    "About": "Über uns",
    "Pricing": "Preise",
    "Models": "Modelle",
    "Sign in": "Anmelden",
    "Sign up": "Registrieren",
    "New conversation": "Neues Gespräch",
    "Chat settings": "Chat-Einstellungen",
    "Temporary chat": "Temporärer Chat",
    "New project": "Neues Projekt",
    "Saved conversations": "Gespeicherte Gespräche",
    "Search saved chats": "Chats durchsuchen",
    "Settings": "Einstellungen",
    "Send message": "Nachricht senden",
    "Model": "Modell",
    "Chatting with": "Chat mit",
    "Online": "Online",
    "API needed": "API erforderlich",
    "Ready": "Bereit",
    "Edit": "Bearbeiten",
    "Delete": "Löschen",
    "Cancel": "Abbrechen"
  },
  "es": {
    "backChat": "Volver al chat",
    "personalChat": "CHAT PERSONAL",
    "settings": "Ajustes",
    "appearance": "Apariencia",
    "settingsIntro": "Personaliza tu chat de AllModelAI.",
    "inputField": "CAMPO DE TEXTO",
    "inputTitle": "Color del campo de texto",
    "inputDescription": "Cambia el fondo del campo donde escribes mensajes.",
    "themeTitle": "Elige tu tema",
    "themeDescription": "Cambia la apariencia manteniendo los detalles violetas de AllModelAI.",
    "bubbleTitle": "Elige tu color",
    "bubbleDescription": "El color elegido sustituye el fondo gris de tus mensajes.",
    "liveResult": "VISTA PREVIA",
    "previewTitle": "Vista previa del chat",
    "autoSaved": "Los cambios se guardan automáticamente.",
    "previewHello": "¡Hola, {name}! ¿Qué quieres crear hoy?",
    "previewPrompt": "Ayúdame a crear un nuevo proyecto genial",
    "messagePlaceholder": "Escribe a AllModelAI...",
    "selected": "Seleccionado",
    "custom": "Personalizado",
    "creator": "creador",
    "light": "Claro",
    "dark": "Oscuro",
    "auto": "Sistema",
    "bright": "Claro y limpio",
    "deepBlack": "Espacio de trabajo oscuro",
    "matchDevice": "Igual que tu dispositivo",
    "Black": "Negro",
    "Graphite": "Grafito",
    "Blue": "Azul",
    "Yellow": "Amarillo",
    "Purple": "Púrpura",
    "Lime": "Lima",
    "Orange": "Naranja",
    "Red": "Rojo",
    "Red orange": "Rojo anaranjado",
    "Violet": "Violeta",
    "Gray": "Gris",
    "Green yellow": "Amarillo verdoso",
    "Dashboard": "Panel",
    "Open chat": "Abrir chat",
    "Home": "Inicio",
    "About": "Acerca de",
    "Pricing": "Precios",
    "Models": "Modelos",
    "Sign in": "Iniciar sesión",
    "Sign up": "Registrarse",
    "New conversation": "Nueva conversación",
    "Chat settings": "Ajustes del chat",
    "Temporary chat": "Chat temporal",
    "New project": "Nuevo proyecto",
    "Saved conversations": "Conversaciones guardadas",
    "Search saved chats": "Buscar conversaciones",
    "Settings": "Ajustes",
    "Send message": "Enviar mensaje",
    "Model": "Modelo",
    "Chatting with": "Conversando con",
    "Online": "En línea",
    "API needed": "Se necesita API",
    "Ready": "Listo",
    "Edit": "Editar",
    "Delete": "Eliminar",
    "Cancel": "Cancelar"
  },
  "it": {
    "backChat": "Torna alla chat",
    "personalChat": "CHAT PERSONALE",
    "settings": "Impostazioni",
    "appearance": "Aspetto",
    "settingsIntro": "Personalizza la tua chat AllModelAI.",
    "inputField": "CAMPO DI TESTO",
    "inputTitle": "Colore del campo di testo",
    "inputDescription": "Cambia lo sfondo del campo in cui scrivi i messaggi.",
    "themeTitle": "Scegli il tema",
    "themeDescription": "Cambia l’aspetto mantenendo gli accenti viola di AllModelAI.",
    "bubbleTitle": "Scegli il colore",
    "bubbleDescription": "Il colore scelto sostituisce lo sfondo grigio dei tuoi messaggi.",
    "liveResult": "ANTEPRIMA",
    "previewTitle": "Anteprima della chat",
    "autoSaved": "Le modifiche vengono salvate automaticamente.",
    "previewHello": "Ciao, {name}! Cosa vuoi creare oggi?",
    "previewPrompt": "Aiutami a creare un nuovo fantastico progetto",
    "messagePlaceholder": "Scrivi ad AllModelAI...",
    "selected": "Selezionato",
    "custom": "Personalizzato",
    "creator": "creatore",
    "light": "Chiaro",
    "dark": "Scuro",
    "auto": "Sistema",
    "bright": "Chiaro e pulito",
    "deepBlack": "Spazio di lavoro scuro",
    "matchDevice": "Come il tuo dispositivo",
    "Black": "Nero",
    "Graphite": "Grafite",
    "Blue": "Blu",
    "Yellow": "Giallo",
    "Purple": "Porpora",
    "Lime": "Lime",
    "Orange": "Arancione",
    "Red": "Rosso",
    "Red orange": "Rosso arancio",
    "Violet": "Viola",
    "Gray": "Grigio",
    "Green yellow": "Giallo verde",
    "Dashboard": "Pannello",
    "Open chat": "Apri chat",
    "Home": "Home",
    "About": "Informazioni",
    "Pricing": "Prezzi",
    "Models": "Modelli",
    "Sign in": "Accedi",
    "Sign up": "Registrati",
    "New conversation": "Nuova conversazione",
    "Chat settings": "Impostazioni chat",
    "Temporary chat": "Chat temporanea",
    "New project": "Nuovo progetto",
    "Saved conversations": "Conversazioni salvate",
    "Search saved chats": "Cerca conversazioni",
    "Settings": "Impostazioni",
    "Send message": "Invia messaggio",
    "Model": "Modello",
    "Chatting with": "Conversazione con",
    "Online": "Online",
    "API needed": "API necessaria",
    "Ready": "Pronto",
    "Edit": "Modifica",
    "Delete": "Elimina",
    "Cancel": "Annulla"
  },
  "pt": {
    "backChat": "Voltar ao chat",
    "personalChat": "CHAT PESSOAL",
    "settings": "Configurações",
    "appearance": "Aparência",
    "settingsIntro": "Personalize seu chat AllModelAI.",
    "inputField": "CAMPO DE TEXTO",
    "inputTitle": "Cor do campo de texto",
    "inputDescription": "Altere o fundo do campo onde você escreve mensagens.",
    "themeTitle": "Escolha o tema",
    "themeDescription": "Altere a aparência mantendo os detalhes violetas do AllModelAI.",
    "bubbleTitle": "Escolha a cor",
    "bubbleDescription": "A cor escolhida substitui o fundo cinza das suas mensagens.",
    "liveResult": "PRÉVIA",
    "previewTitle": "Prévia do chat",
    "autoSaved": "As alterações são salvas automaticamente.",
    "previewHello": "Olá, {name}! O que você quer criar hoje?",
    "previewPrompt": "Ajude-me a criar um novo projeto incrível",
    "messagePlaceholder": "Mensagem para AllModelAI...",
    "selected": "Selecionado",
    "custom": "Personalizado",
    "creator": "criador",
    "light": "Claro",
    "dark": "Escuro",
    "auto": "Sistema",
    "bright": "Claro e limpo",
    "deepBlack": "Espaço de trabalho escuro",
    "matchDevice": "Como seu dispositivo",
    "Black": "Preto",
    "Graphite": "Grafite",
    "Blue": "Azul",
    "Yellow": "Amarelo",
    "Purple": "Púrpura",
    "Lime": "Lima",
    "Orange": "Laranja",
    "Red": "Vermelho",
    "Red orange": "Vermelho alaranjado",
    "Violet": "Violeta",
    "Gray": "Cinza",
    "Green yellow": "Amarelo esverdeado",
    "Dashboard": "Painel",
    "Open chat": "Abrir chat",
    "Home": "Início",
    "About": "Sobre",
    "Pricing": "Preços",
    "Models": "Modelos",
    "Sign in": "Entrar",
    "Sign up": "Cadastrar-se",
    "New conversation": "Nova conversa",
    "Chat settings": "Configurações do chat",
    "Temporary chat": "Chat temporário",
    "New project": "Novo projeto",
    "Saved conversations": "Conversas salvas",
    "Search saved chats": "Buscar conversas",
    "Settings": "Configurações",
    "Send message": "Enviar mensagem",
    "Model": "Modelo",
    "Chatting with": "Conversando com",
    "Online": "Online",
    "API needed": "API necessária",
    "Ready": "Pronto",
    "Edit": "Editar",
    "Delete": "Excluir",
    "Cancel": "Cancelar"
  },
  "fi": {
    "backChat": "Takaisin keskusteluun",
    "personalChat": "OMA KESKUSTELU",
    "settings": "Asetukset",
    "appearance": "Ulkoasu",
    "settingsIntro": "Tee AllModelAI-keskustelusta omanlaisesi.",
    "inputField": "TEKSTIKENTTÄ",
    "inputTitle": "Tekstikentän väri",
    "inputDescription": "Vaihda viestien kirjoituskentän taustaa.",
    "themeTitle": "Valitse teema",
    "themeDescription": "Vaihda ulkoasua säilyttäen AllModelAI:n violetit korostukset.",
    "bubbleTitle": "Valitse väri",
    "bubbleDescription": "Valittu väri korvaa viestiesi harmaan taustan.",
    "liveResult": "ESIKATSELU",
    "previewTitle": "Keskustelun esikatselu",
    "autoSaved": "Muutokset tallennetaan automaattisesti.",
    "previewHello": "Hei, {name}! Mitä haluat luoda tänään?",
    "previewPrompt": "Auta minua luomaan hieno uusi projekti",
    "messagePlaceholder": "Viesti AllModelAI:lle...",
    "selected": "Valittu",
    "custom": "Mukautettu",
    "creator": "luoja",
    "light": "Vaalea",
    "dark": "Tumma",
    "auto": "Järjestelmä",
    "bright": "Vaalea ja selkeä",
    "deepBlack": "Tumma työtila",
    "matchDevice": "Laitteen asetusten mukaan",
    "Black": "Musta",
    "Graphite": "Grafiitti",
    "Blue": "Sininen",
    "Yellow": "Keltainen",
    "Purple": "Purppura",
    "Lime": "Lime",
    "Orange": "Oranssi",
    "Red": "Punainen",
    "Red orange": "Punaoranssi",
    "Violet": "Violetti",
    "Gray": "Harmaa",
    "Green yellow": "Keltavihreä",
    "Dashboard": "Hallintapaneeli",
    "Open chat": "Avaa keskustelu",
    "Home": "Etusivu",
    "About": "Tietoa",
    "Pricing": "Hinnat",
    "Models": "Mallit",
    "Sign in": "Kirjaudu sisään",
    "Sign up": "Rekisteröidy",
    "New conversation": "Uusi keskustelu",
    "Chat settings": "Keskusteluasetukset",
    "Temporary chat": "Tilapäinen keskustelu",
    "New project": "Uusi projekti",
    "Saved conversations": "Tallennetut keskustelut",
    "Search saved chats": "Etsi keskusteluja",
    "Settings": "Asetukset",
    "Send message": "Lähetä viesti",
    "Model": "Malli",
    "Chatting with": "Keskustelu mallin kanssa",
    "Online": "Verkossa",
    "API needed": "API tarvitaan",
    "Ready": "Valmis",
    "Edit": "Muokkaa",
    "Delete": "Poista",
    "Cancel": "Peruuta"
  },
  "cs": {
    "backChat": "Zpět do chatu",
    "personalChat": "OSOBNÍ CHAT",
    "settings": "Nastavení",
    "appearance": "Vzhled",
    "settingsIntro": "Přizpůsobte si chat AllModelAI.",
    "inputField": "TEXTOVÉ POLE",
    "inputTitle": "Barva textového pole",
    "inputDescription": "Změňte pozadí pole, do kterého píšete zprávy.",
    "themeTitle": "Vyberte motiv",
    "themeDescription": "Změňte vzhled se zachováním fialových prvků AllModelAI.",
    "bubbleTitle": "Vyberte barvu",
    "bubbleDescription": "Vybraná barva nahradí šedé pozadí vašich zpráv.",
    "liveResult": "NÁHLED",
    "previewTitle": "Náhled chatu",
    "autoSaved": "Změny se ukládají automaticky.",
    "previewHello": "Ahoj, {name}! Co chcete dnes vytvořit?",
    "previewPrompt": "Pomoz mi vytvořit skvělý nový projekt",
    "messagePlaceholder": "Zpráva pro AllModelAI...",
    "selected": "Vybráno",
    "custom": "Vlastní",
    "creator": "tvůrce",
    "light": "Světlý",
    "dark": "Tmavý",
    "auto": "Systémový",
    "bright": "Světlý a čistý",
    "deepBlack": "Tmavý pracovní prostor",
    "matchDevice": "Podle zařízení",
    "Black": "Černá",
    "Graphite": "Grafitová",
    "Blue": "Modrá",
    "Yellow": "Žlutá",
    "Purple": "Purpurová",
    "Lime": "Limetková",
    "Orange": "Oranžová",
    "Red": "Červená",
    "Red orange": "Červenooranžová",
    "Violet": "Fialová",
    "Gray": "Šedá",
    "Green yellow": "Žlutozelená",
    "Dashboard": "Přehled",
    "Open chat": "Otevřít chat",
    "Home": "Domů",
    "About": "O nás",
    "Pricing": "Ceny",
    "Models": "Modely",
    "Sign in": "Přihlásit se",
    "Sign up": "Registrovat se",
    "New conversation": "Nová konverzace",
    "Chat settings": "Nastavení chatu",
    "Temporary chat": "Dočasný chat",
    "New project": "Nový projekt",
    "Saved conversations": "Uložené konverzace",
    "Search saved chats": "Hledat konverzace",
    "Settings": "Nastavení",
    "Send message": "Odeslat zprávu",
    "Model": "Model",
    "Chatting with": "Chat s",
    "Online": "Online",
    "API needed": "Vyžaduje API",
    "Ready": "Připraveno",
    "Edit": "Upravit",
    "Delete": "Smazat",
    "Cancel": "Zrušit"
  },
  "sl": {
    "backChat": "Nazaj v klepet",
    "personalChat": "OSEBNI KLEPET",
    "settings": "Nastavitve",
    "appearance": "Videz",
    "settingsIntro": "Prilagodite klepet AllModelAI po svoje.",
    "inputField": "VNOSNO POLJE",
    "inputTitle": "Barva vnosnega polja",
    "inputDescription": "Spremenite ozadje polja za pisanje sporočil.",
    "themeTitle": "Izberite temo",
    "themeDescription": "Spremenite videz in ohranite vijolične poudarke AllModelAI.",
    "bubbleTitle": "Izberite barvo",
    "bubbleDescription": "Izbrana barva nadomesti sivo ozadje vaših sporočil.",
    "liveResult": "PREDOGLED",
    "previewTitle": "Predogled klepeta",
    "autoSaved": "Spremembe se shranijo samodejno.",
    "previewHello": "Pozdravljeni, {name}! Kaj želite ustvariti danes?",
    "previewPrompt": "Pomagaj mi ustvariti odličen nov projekt",
    "messagePlaceholder": "Sporočilo za AllModelAI...",
    "selected": "Izbrano",
    "custom": "Po meri",
    "creator": "ustvarjalec",
    "light": "Svetla",
    "dark": "Temna",
    "auto": "Sistemska",
    "bright": "Svetlo in pregledno",
    "deepBlack": "Temen delovni prostor",
    "matchDevice": "Glede na napravo",
    "Black": "Črna",
    "Graphite": "Grafitna",
    "Blue": "Modra",
    "Yellow": "Rumena",
    "Purple": "Škrlatna",
    "Lime": "Limetna",
    "Orange": "Oranžna",
    "Red": "Rdeča",
    "Red orange": "Rdečeoranžna",
    "Violet": "Vijolična",
    "Gray": "Siva",
    "Green yellow": "Rumenozelena",
    "Dashboard": "Nadzorna plošča",
    "Open chat": "Odpri klepet",
    "Home": "Domov",
    "About": "O nas",
    "Pricing": "Cene",
    "Models": "Modeli",
    "Sign in": "Prijava",
    "Sign up": "Registracija",
    "New conversation": "Nov pogovor",
    "Chat settings": "Nastavitve klepeta",
    "Temporary chat": "Začasni klepet",
    "New project": "Nov projekt",
    "Saved conversations": "Shranjeni pogovori",
    "Search saved chats": "Išči pogovore",
    "Settings": "Nastavitve",
    "Send message": "Pošlji sporočilo",
    "Model": "Model",
    "Chatting with": "Klepet z",
    "Online": "Na spletu",
    "API needed": "Potreben je API",
    "Ready": "Pripravljeno",
    "Edit": "Uredi",
    "Delete": "Izbriši",
    "Cancel": "Prekliči"
  },
  "hr": {
    "backChat": "Natrag na razgovor",
    "personalChat": "OSOBNI RAZGOVOR",
    "settings": "Postavke",
    "appearance": "Izgled",
    "settingsIntro": "Prilagodite razgovor u AllModelAI-ju.",
    "inputField": "POLJE ZA UNOS",
    "inputTitle": "Boja polja za unos",
    "inputDescription": "Promijenite pozadinu polja u kojem pišete poruke.",
    "themeTitle": "Odaberite temu",
    "themeDescription": "Promijenite izgled uz ljubičaste naglaske AllModelAI-ja.",
    "bubbleTitle": "Odaberite boju",
    "bubbleDescription": "Odabrana boja zamjenjuje sivu pozadinu vaših poruka.",
    "liveResult": "PREGLED",
    "previewTitle": "Pregled razgovora",
    "autoSaved": "Promjene se spremaju automatski.",
    "previewHello": "Pozdrav, {name}! Što želite stvoriti danas?",
    "previewPrompt": "Pomogni mi stvoriti sjajan novi projekt",
    "messagePlaceholder": "Poruka za AllModelAI...",
    "selected": "Odabrano",
    "custom": "Prilagođeno",
    "creator": "autor",
    "light": "Svijetla",
    "dark": "Tamna",
    "auto": "Sustav",
    "bright": "Svijetlo i pregledno",
    "deepBlack": "Tamni radni prostor",
    "matchDevice": "Prema uređaju",
    "Black": "Crna",
    "Graphite": "Grafitna",
    "Blue": "Plava",
    "Yellow": "Žuta",
    "Purple": "Purpurna",
    "Lime": "Limeta",
    "Orange": "Narančasta",
    "Red": "Crvena",
    "Red orange": "Crvenonarančasta",
    "Violet": "Ljubičasta",
    "Gray": "Siva",
    "Green yellow": "Žutozelena",
    "Dashboard": "Nadzorna ploča",
    "Open chat": "Otvori razgovor",
    "Home": "Početna",
    "About": "O nama",
    "Pricing": "Cijene",
    "Models": "Modeli",
    "Sign in": "Prijava",
    "Sign up": "Registracija",
    "New conversation": "Novi razgovor",
    "Chat settings": "Postavke razgovora",
    "Temporary chat": "Privremeni razgovor",
    "New project": "Novi projekt",
    "Saved conversations": "Spremljeni razgovori",
    "Search saved chats": "Pretraži razgovore",
    "Settings": "Postavke",
    "Send message": "Pošalji poruku",
    "Model": "Model",
    "Chatting with": "Razgovor s",
    "Online": "Na mreži",
    "API needed": "Potreban API",
    "Ready": "Spremno",
    "Edit": "Uredi",
    "Delete": "Izbriši",
    "Cancel": "Odustani"
  },
  "ro": {
    "backChat": "Înapoi la chat",
    "personalChat": "CHAT PERSONAL",
    "settings": "Setări",
    "appearance": "Aspect",
    "settingsIntro": "Personalizează-ți chatul AllModelAI.",
    "inputField": "CÂMP DE TEXT",
    "inputTitle": "Culoarea câmpului de text",
    "inputDescription": "Schimbă fundalul câmpului în care scrii mesaje.",
    "themeTitle": "Alege tema",
    "themeDescription": "Schimbă aspectul păstrând accentele violet AllModelAI.",
    "bubbleTitle": "Alege culoarea",
    "bubbleDescription": "Culoarea aleasă înlocuiește fundalul gri al mesajelor tale.",
    "liveResult": "PREVIZUALIZARE",
    "previewTitle": "Previzualizarea chatului",
    "autoSaved": "Modificările se salvează automat.",
    "previewHello": "Salut, {name}! Ce vrei să creezi astăzi?",
    "previewPrompt": "Ajută-mă să creez un proiect nou excelent",
    "messagePlaceholder": "Mesaj către AllModelAI...",
    "selected": "Selectat",
    "custom": "Personalizat",
    "creator": "creator",
    "light": "Luminos",
    "dark": "Întunecat",
    "auto": "Sistem",
    "bright": "Luminos și simplu",
    "deepBlack": "Spațiu de lucru întunecat",
    "matchDevice": "Conform dispozitivului",
    "Black": "Negru",
    "Graphite": "Grafit",
    "Blue": "Albastru",
    "Yellow": "Galben",
    "Purple": "Purpuriu",
    "Lime": "Verde lime",
    "Orange": "Portocaliu",
    "Red": "Roșu",
    "Red orange": "Roșu-portocaliu",
    "Violet": "Violet",
    "Gray": "Gri",
    "Green yellow": "Galben-verzui",
    "Dashboard": "Panou",
    "Open chat": "Deschide chatul",
    "Home": "Acasă",
    "About": "Despre",
    "Pricing": "Prețuri",
    "Models": "Modele",
    "Sign in": "Autentificare",
    "Sign up": "Înregistrare",
    "New conversation": "Conversație nouă",
    "Chat settings": "Setări chat",
    "Temporary chat": "Chat temporar",
    "New project": "Proiect nou",
    "Saved conversations": "Conversații salvate",
    "Search saved chats": "Caută conversații",
    "Settings": "Setări",
    "Send message": "Trimite mesajul",
    "Model": "Model",
    "Chatting with": "Discuție cu",
    "Online": "Online",
    "API needed": "API necesar",
    "Ready": "Gata",
    "Edit": "Editează",
    "Delete": "Șterge",
    "Cancel": "Anulează"
  },
  "ja": {
    "backChat": "チャットに戻る",
    "personalChat": "個人チャット",
    "settings": "設定",
    "appearance": "外観",
    "settingsIntro": "AllModelAIのチャットを自分好みに設定しましょう。",
    "inputField": "入力欄",
    "inputTitle": "入力欄の色を選択",
    "inputDescription": "メッセージを入力する欄の背景を変更します。",
    "themeTitle": "テーマを選択",
    "themeDescription": "AllModelAIの紫色のアクセントを残して外観を変更します。",
    "bubbleTitle": "色を選択",
    "bubbleDescription": "選択した色が送信メッセージの灰色の背景に代わります。",
    "liveResult": "プレビュー",
    "previewTitle": "チャットのプレビュー",
    "autoSaved": "変更は自動的に保存されます。",
    "previewHello": "こんにちは、{name}さん！今日は何を作りたいですか？",
    "previewPrompt": "すばらしい新しいプロジェクト作りを手伝って",
    "messagePlaceholder": "AllModelAIにメッセージ...",
    "selected": "選択中",
    "custom": "カスタム",
    "creator": "クリエイター",
    "light": "ライト",
    "dark": "ダーク",
    "auto": "システム",
    "bright": "明るくシンプル",
    "deepBlack": "暗いワークスペース",
    "matchDevice": "デバイスに合わせる",
    "Black": "黒",
    "Graphite": "グラファイト",
    "Blue": "青",
    "Yellow": "黄",
    "Purple": "パープル",
    "Lime": "ライム",
    "Orange": "オレンジ",
    "Red": "赤",
    "Red orange": "朱色",
    "Violet": "バイオレット",
    "Gray": "灰色",
    "Green yellow": "黄緑",
    "Dashboard": "ダッシュボード",
    "Open chat": "チャットを開く",
    "Home": "ホーム",
    "About": "概要",
    "Pricing": "料金",
    "Models": "モデル",
    "Sign in": "ログイン",
    "Sign up": "登録",
    "New conversation": "新しい会話",
    "Chat settings": "チャット設定",
    "Temporary chat": "一時チャット",
    "New project": "新しいプロジェクト",
    "Saved conversations": "保存した会話",
    "Search saved chats": "会話を検索",
    "Settings": "設定",
    "Send message": "メッセージを送信",
    "Model": "モデル",
    "Chatting with": "チャット相手",
    "Online": "オンライン",
    "API needed": "APIが必要",
    "Ready": "準備完了",
    "Edit": "編集",
    "Delete": "削除",
    "Cancel": "キャンセル"
  },
  "zh": {
    "backChat": "返回聊天",
    "personalChat": "个人聊天",
    "settings": "设置",
    "appearance": "外观",
    "settingsIntro": "个性化你的 AllModelAI 聊天。",
    "inputField": "输入框",
    "inputTitle": "选择输入框颜色",
    "inputDescription": "更改消息输入框的背景。",
    "themeTitle": "选择主题",
    "themeDescription": "更改外观，同时保留 AllModelAI 的紫色点缀。",
    "bubbleTitle": "选择颜色",
    "bubbleDescription": "所选颜色将替换已发送消息的灰色背景。",
    "liveResult": "实时预览",
    "previewTitle": "聊天预览",
    "autoSaved": "更改会自动保存。",
    "previewHello": "你好，{name}！今天想创建什么？",
    "previewPrompt": "帮我创建一个出色的新项目",
    "messagePlaceholder": "给 AllModelAI 发送消息...",
    "selected": "已选择",
    "custom": "自定义",
    "creator": "创作者",
    "light": "浅色",
    "dark": "深色",
    "auto": "跟随系统",
    "bright": "明亮简洁",
    "deepBlack": "深色工作区",
    "matchDevice": "跟随设备设置",
    "Black": "黑色",
    "Graphite": "石墨色",
    "Blue": "蓝色",
    "Yellow": "黄色",
    "Purple": "紫红色",
    "Lime": "青柠色",
    "Orange": "橙色",
    "Red": "红色",
    "Red orange": "橘红色",
    "Violet": "紫罗兰色",
    "Gray": "灰色",
    "Green yellow": "黄绿色",
    "Dashboard": "控制面板",
    "Open chat": "打开聊天",
    "Home": "首页",
    "About": "关于",
    "Pricing": "价格",
    "Models": "模型",
    "Sign in": "登录",
    "Sign up": "注册",
    "New conversation": "新对话",
    "Chat settings": "聊天设置",
    "Temporary chat": "临时聊天",
    "New project": "新项目",
    "Saved conversations": "已保存的对话",
    "Search saved chats": "搜索对话",
    "Settings": "设置",
    "Send message": "发送消息",
    "Model": "模型",
    "Chatting with": "聊天对象",
    "Online": "在线",
    "API needed": "需要 API",
    "Ready": "就绪",
    "Edit": "编辑",
    "Delete": "删除",
    "Cancel": "取消"
  },
  "zh-TW": {
    "backChat": "返回聊天",
    "personalChat": "個人聊天",
    "settings": "設定",
    "appearance": "外觀",
    "settingsIntro": "個人化你的 AllModelAI 聊天。",
    "inputField": "輸入框",
    "inputTitle": "選擇輸入框顏色",
    "inputDescription": "變更訊息輸入框的背景。",
    "themeTitle": "選擇主題",
    "themeDescription": "變更外觀，同時保留 AllModelAI 的紫色點綴。",
    "bubbleTitle": "選擇顏色",
    "bubbleDescription": "所選顏色將取代已傳送訊息的灰色背景。",
    "liveResult": "即時預覽",
    "previewTitle": "聊天預覽",
    "autoSaved": "變更會自動儲存。",
    "previewHello": "你好，{name}！今天想建立什麼？",
    "previewPrompt": "幫我建立一個出色的新專案",
    "messagePlaceholder": "傳送訊息給 AllModelAI...",
    "selected": "已選取",
    "custom": "自訂",
    "creator": "創作者",
    "light": "淺色",
    "dark": "深色",
    "auto": "跟隨系統",
    "bright": "明亮簡潔",
    "deepBlack": "深色工作區",
    "matchDevice": "跟隨裝置設定",
    "Black": "黑色",
    "Graphite": "石墨色",
    "Blue": "藍色",
    "Yellow": "黃色",
    "Purple": "紫紅色",
    "Lime": "萊姆色",
    "Orange": "橙色",
    "Red": "紅色",
    "Red orange": "橘紅色",
    "Violet": "紫羅蘭色",
    "Gray": "灰色",
    "Green yellow": "黃綠色",
    "Dashboard": "控制台",
    "Open chat": "開啟聊天",
    "Home": "首頁",
    "About": "關於",
    "Pricing": "價格",
    "Models": "模型",
    "Sign in": "登入",
    "Sign up": "註冊",
    "New conversation": "新對話",
    "Chat settings": "聊天設定",
    "Temporary chat": "暫時聊天",
    "New project": "新專案",
    "Saved conversations": "已儲存的對話",
    "Search saved chats": "搜尋對話",
    "Settings": "設定",
    "Send message": "傳送訊息",
    "Model": "模型",
    "Chatting with": "聊天對象",
    "Online": "在線",
    "API needed": "需要 API",
    "Ready": "就緒",
    "Edit": "編輯",
    "Delete": "刪除",
    "Cancel": "取消"
  },
  "hi": {
    "backChat": "चैट पर वापस जाएँ",
    "personalChat": "निजी चैट",
    "settings": "सेटिंग्स",
    "appearance": "रूप-रंग",
    "settingsIntro": "अपनी AllModelAI चैट को अपने अनुसार बनाएँ।",
    "inputField": "इनपुट फ़ील्ड",
    "inputTitle": "इनपुट का रंग चुनें",
    "inputDescription": "संदेश लिखने वाले फ़ील्ड की पृष्ठभूमि बदलें।",
    "themeTitle": "अपनी थीम चुनें",
    "themeDescription": "AllModelAI के बैंगनी रंगों को रखते हुए रूप बदलें।",
    "bubbleTitle": "अपना रंग चुनें",
    "bubbleDescription": "चुना गया रंग आपके संदेशों की धूसर पृष्ठभूमि को बदल देगा।",
    "liveResult": "पूर्वावलोकन",
    "previewTitle": "आपकी चैट का पूर्वावलोकन",
    "autoSaved": "बदलाव अपने आप सहेजे जाते हैं।",
    "previewHello": "नमस्ते, {name}! आज आप क्या बनाना चाहेंगे?",
    "previewPrompt": "एक बेहतरीन नया प्रोजेक्ट बनाने में मेरी मदद करें",
    "messagePlaceholder": "AllModelAI को संदेश लिखें...",
    "selected": "चयनित",
    "custom": "कस्टम",
    "creator": "रचनाकार",
    "light": "हल्की",
    "dark": "गहरी",
    "auto": "सिस्टम",
    "bright": "उज्ज्वल और साफ़",
    "deepBlack": "गहरा कार्यक्षेत्र",
    "matchDevice": "डिवाइस के अनुसार",
    "Black": "काला",
    "Graphite": "ग्रेफाइट",
    "Blue": "नीला",
    "Yellow": "पीला",
    "Purple": "जामुनी",
    "Lime": "लाइम",
    "Orange": "नारंगी",
    "Red": "लाल",
    "Red orange": "लाल नारंगी",
    "Violet": "बैंगनी",
    "Gray": "धूसर",
    "Green yellow": "पीला हरा",
    "Dashboard": "डैशबोर्ड",
    "Open chat": "चैट खोलें",
    "Home": "मुखपृष्ठ",
    "About": "परिचय",
    "Pricing": "कीमतें",
    "Models": "मॉडल",
    "Sign in": "लॉग इन",
    "Sign up": "साइन अप",
    "New conversation": "नई बातचीत",
    "Chat settings": "चैट सेटिंग्स",
    "Temporary chat": "अस्थायी चैट",
    "New project": "नया प्रोजेक्ट",
    "Saved conversations": "सहेजी गई बातचीत",
    "Search saved chats": "बातचीत खोजें",
    "Settings": "सेटिंग्स",
    "Send message": "संदेश भेजें",
    "Model": "मॉडल",
    "Chatting with": "बातचीत",
    "Online": "ऑनलाइन",
    "API needed": "API आवश्यक",
    "Ready": "तैयार",
    "Edit": "संपादित करें",
    "Delete": "हटाएँ",
    "Cancel": "रद्द करें"
  },
  "nl": {
    "backChat": "Terug naar chat",
    "personalChat": "PERSOONLIJKE CHAT",
    "settings": "Instellingen",
    "appearance": "Weergave",
    "settingsIntro": "Maak je AllModelAI-chat helemaal van jou.",
    "inputField": "INVOERVELD",
    "inputTitle": "Kies de invoerkleur",
    "inputDescription": "Wijzig de achtergrond van het veld waarin je berichten typt.",
    "themeTitle": "Kies je thema",
    "themeDescription": "Wijzig de weergave met behoud van de paarse AllModelAI-accenten.",
    "bubbleTitle": "Kies je kleur",
    "bubbleDescription": "De gekozen kleur vervangt de grijze achtergrond van je berichten.",
    "liveResult": "VOORBEELD",
    "previewTitle": "Voorbeeld van je chat",
    "autoSaved": "Wijzigingen worden automatisch opgeslagen.",
    "previewHello": "Hallo, {name}! Wat wil je vandaag maken?",
    "previewPrompt": "Help me een geweldig nieuw project te maken",
    "messagePlaceholder": "Bericht aan AllModelAI...",
    "selected": "Geselecteerd",
    "custom": "Aangepast",
    "creator": "maker",
    "light": "Licht",
    "dark": "Donker",
    "auto": "Systeem",
    "bright": "Licht en helder",
    "deepBlack": "Donkere werkruimte",
    "matchDevice": "Volg je apparaat",
    "Black": "Zwart",
    "Graphite": "Grafiet",
    "Blue": "Blauw",
    "Yellow": "Geel",
    "Purple": "Purper",
    "Lime": "Limoen",
    "Orange": "Oranje",
    "Red": "Rood",
    "Red orange": "Roodoranje",
    "Violet": "Violet",
    "Gray": "Grijs",
    "Green yellow": "Geelgroen",
    "Dashboard": "Dashboard",
    "Open chat": "Chat openen",
    "Home": "Startpagina",
    "About": "Over ons",
    "Pricing": "Prijzen",
    "Models": "Modellen",
    "Sign in": "Inloggen",
    "Sign up": "Registreren",
    "New conversation": "Nieuw gesprek",
    "Chat settings": "Chatinstellingen",
    "Temporary chat": "Tijdelijke chat",
    "New project": "Nieuw project",
    "Saved conversations": "Opgeslagen gesprekken",
    "Search saved chats": "Gesprekken zoeken",
    "Settings": "Instellingen",
    "Send message": "Bericht versturen",
    "Model": "Model",
    "Chatting with": "Chatten met",
    "Online": "Online",
    "API needed": "API vereist",
    "Ready": "Gereed",
    "Edit": "Bewerken",
    "Delete": "Verwijderen",
    "Cancel": "Annuleren"
  },
  "tr": {
    "backChat": "Sohbete dön",
    "personalChat": "KİŞİSEL SOHBET",
    "settings": "Ayarlar",
    "appearance": "Görünüm",
    "settingsIntro": "AllModelAI sohbetinizi kendinize göre düzenleyin.",
    "inputField": "GİRİŞ ALANI",
    "inputTitle": "Giriş alanı rengini seçin",
    "inputDescription": "Mesaj yazdığınız alanın arka planını değiştirin.",
    "themeTitle": "Temanızı seçin",
    "themeDescription": "AllModelAI mor vurgularını koruyarak görünümü değiştirin.",
    "bubbleTitle": "Renginizi seçin",
    "bubbleDescription": "Seçilen renk, mesajlarınızın gri arka planının yerini alır.",
    "liveResult": "ÖNİZLEME",
    "previewTitle": "Sohbet önizlemesi",
    "autoSaved": "Değişiklikler otomatik kaydedilir.",
    "previewHello": "Merhaba, {name}! Bugün ne oluşturmak istersiniz?",
    "previewPrompt": "Harika bir yeni proje oluşturmama yardım et",
    "messagePlaceholder": "AllModelAI'a mesaj yazın...",
    "selected": "Seçili",
    "custom": "Özel",
    "creator": "üretici",
    "light": "Açık",
    "dark": "Koyu",
    "auto": "Sistem",
    "bright": "Aydınlık ve sade",
    "deepBlack": "Koyu çalışma alanı",
    "matchDevice": "Cihazınıza uyumlu",
    "Black": "Siyah",
    "Graphite": "Grafit",
    "Blue": "Mavi",
    "Yellow": "Sarı",
    "Purple": "Mor",
    "Lime": "Limon yeşili",
    "Orange": "Turuncu",
    "Red": "Kırmızı",
    "Red orange": "Kırmızı turuncu",
    "Violet": "Menekşe",
    "Gray": "Gri",
    "Green yellow": "Sarı yeşil",
    "Dashboard": "Kontrol paneli",
    "Open chat": "Sohbeti aç",
    "Home": "Ana sayfa",
    "About": "Hakkında",
    "Pricing": "Fiyatlar",
    "Models": "Modeller",
    "Sign in": "Giriş yap",
    "Sign up": "Kaydol",
    "New conversation": "Yeni konuşma",
    "Chat settings": "Sohbet ayarları",
    "Temporary chat": "Geçici sohbet",
    "New project": "Yeni proje",
    "Saved conversations": "Kayıtlı konuşmalar",
    "Search saved chats": "Sohbetlerde ara",
    "Settings": "Ayarlar",
    "Send message": "Mesaj gönder",
    "Model": "Model",
    "Chatting with": "Sohbet edilen",
    "Online": "Çevrimiçi",
    "API needed": "API gerekli",
    "Ready": "Hazır",
    "Edit": "Düzenle",
    "Delete": "Sil",
    "Cancel": "İptal"
  },
  "ar": {
    "backChat": "العودة إلى الدردشة",
    "personalChat": "دردشة شخصية",
    "settings": "الإعدادات",
    "appearance": "المظهر",
    "settingsIntro": "خصّص دردشة AllModelAI كما تريد.",
    "inputField": "حقل الإدخال",
    "inputTitle": "اختر لون حقل الإدخال",
    "inputDescription": "غيّر خلفية الحقل الذي تكتب فيه الرسائل.",
    "themeTitle": "اختر المظهر",
    "themeDescription": "غيّر المظهر مع الاحتفاظ باللمسات البنفسجية في AllModelAI.",
    "bubbleTitle": "اختر اللون",
    "bubbleDescription": "يستبدل اللون المحدد الخلفية الرمادية لرسائلك.",
    "liveResult": "معاينة مباشرة",
    "previewTitle": "معاينة الدردشة",
    "autoSaved": "تُحفظ التغييرات تلقائيًا.",
    "previewHello": "مرحبًا، {name}! ماذا تريد أن تنشئ اليوم؟",
    "previewPrompt": "ساعدني في إنشاء مشروع جديد رائع",
    "messagePlaceholder": "راسل AllModelAI...",
    "selected": "محدد",
    "custom": "مخصص",
    "creator": "مبدع",
    "light": "فاتح",
    "dark": "داكن",
    "auto": "النظام",
    "bright": "فاتح وبسيط",
    "deepBlack": "مساحة عمل داكنة",
    "matchDevice": "حسب جهازك",
    "Black": "أسود",
    "Graphite": "جرافيتي",
    "Blue": "أزرق",
    "Yellow": "أصفر",
    "Purple": "أرجواني",
    "Lime": "ليموني",
    "Orange": "برتقالي",
    "Red": "أحمر",
    "Red orange": "أحمر برتقالي",
    "Violet": "بنفسجي",
    "Gray": "رمادي",
    "Green yellow": "أصفر مخضر",
    "Dashboard": "لوحة التحكم",
    "Open chat": "فتح الدردشة",
    "Home": "الرئيسية",
    "About": "حول",
    "Pricing": "الأسعار",
    "Models": "النماذج",
    "Sign in": "تسجيل الدخول",
    "Sign up": "إنشاء حساب",
    "New conversation": "محادثة جديدة",
    "Chat settings": "إعدادات الدردشة",
    "Temporary chat": "دردشة مؤقتة",
    "New project": "مشروع جديد",
    "Saved conversations": "المحادثات المحفوظة",
    "Search saved chats": "البحث في المحادثات",
    "Settings": "الإعدادات",
    "Send message": "إرسال الرسالة",
    "Model": "النموذج",
    "Chatting with": "الدردشة مع",
    "Online": "متصل",
    "API needed": "يلزم API",
    "Ready": "جاهز",
    "Edit": "تعديل",
    "Delete": "حذف",
    "Cancel": "إلغاء"
  },
  "ar-EG": {
    "backChat": "ارجع للدردشة",
    "personalChat": "دردشة شخصية",
    "settings": "الإعدادات",
    "appearance": "الشكل",
    "settingsIntro": "ظبّط دردشة AllModelAI على ذوقك.",
    "inputField": "خانة الكتابة",
    "inputTitle": "اختار لون خانة الكتابة",
    "inputDescription": "غيّر خلفية الخانة اللي بتكتب فيها رسايلك.",
    "themeTitle": "اختار الشكل",
    "themeDescription": "غيّر الشكل مع الحفاظ على اللمسات البنفسجية في AllModelAI.",
    "bubbleTitle": "اختار اللون",
    "bubbleDescription": "اللون اللي تختاره هيبدّل الخلفية الرمادية لرسايلك.",
    "liveResult": "معاينة مباشرة",
    "previewTitle": "معاينة الدردشة",
    "autoSaved": "التغييرات بتتحفظ تلقائيًا.",
    "previewHello": "أهلًا، {name}! عايز تعمل إيه النهارده؟",
    "previewPrompt": "ساعدني أعمل مشروع جديد رائع",
    "messagePlaceholder": "ابعت رسالة لـ AllModelAI...",
    "selected": "المختار",
    "custom": "مخصص",
    "creator": "مبدع",
    "light": "فاتح",
    "dark": "غامق",
    "auto": "النظام",
    "bright": "فاتح وبسيط",
    "deepBlack": "مساحة شغل غامقة",
    "matchDevice": "زي جهازك",
    "Black": "أسود",
    "Graphite": "جرافيت",
    "Blue": "أزرق",
    "Yellow": "أصفر",
    "Purple": "أرجواني",
    "Lime": "ليموني",
    "Orange": "برتقالي",
    "Red": "أحمر",
    "Red orange": "أحمر برتقالي",
    "Violet": "بنفسجي",
    "Gray": "رمادي",
    "Green yellow": "أصفر مخضر",
    "Dashboard": "لوحة التحكم",
    "Open chat": "افتح الدردشة",
    "Home": "الرئيسية",
    "About": "عن الموقع",
    "Pricing": "الأسعار",
    "Models": "النماذج",
    "Sign in": "تسجيل الدخول",
    "Sign up": "اعمل حساب",
    "New conversation": "محادثة جديدة",
    "Chat settings": "إعدادات الدردشة",
    "Temporary chat": "دردشة مؤقتة",
    "New project": "مشروع جديد",
    "Saved conversations": "المحادثات المحفوظة",
    "Search saved chats": "دوّر في المحادثات",
    "Settings": "الإعدادات",
    "Send message": "ابعت الرسالة",
    "Model": "النموذج",
    "Chatting with": "بتتكلم مع",
    "Online": "متصل",
    "API needed": "محتاج API",
    "Ready": "جاهز",
    "Edit": "تعديل",
    "Delete": "حذف",
    "Cancel": "إلغاء"
  },
  "el": {
    "backChat": "Επιστροφή στη συνομιλία",
    "personalChat": "ΠΡΟΣΩΠΙΚΗ ΣΥΝΟΜΙΛΙΑ",
    "settings": "Ρυθμίσεις",
    "appearance": "Εμφάνιση",
    "settingsIntro": "Προσαρμόστε τη συνομιλία AllModelAI στα μέτρα σας.",
    "inputField": "ΠΕΔΙΟ ΕΙΣΑΓΩΓΗΣ",
    "inputTitle": "Χρώμα πεδίου εισαγωγής",
    "inputDescription": "Αλλάξτε το φόντο του πεδίου όπου γράφετε μηνύματα.",
    "themeTitle": "Επιλέξτε θέμα",
    "themeDescription": "Αλλάξτε την εμφάνιση διατηρώντας τις μωβ πινελιές AllModelAI.",
    "bubbleTitle": "Επιλέξτε χρώμα",
    "bubbleDescription": "Το επιλεγμένο χρώμα αντικαθιστά το γκρι φόντο των μηνυμάτων σας.",
    "liveResult": "ΠΡΟΕΠΙΣΚΟΠΗΣΗ",
    "previewTitle": "Προεπισκόπηση συνομιλίας",
    "autoSaved": "Οι αλλαγές αποθηκεύονται αυτόματα.",
    "previewHello": "Γεια σου, {name}! Τι θέλεις να δημιουργήσεις σήμερα;",
    "previewPrompt": "Βοήθησέ με να δημιουργήσω ένα υπέροχο νέο έργο",
    "messagePlaceholder": "Μήνυμα στο AllModelAI...",
    "selected": "Επιλεγμένο",
    "custom": "Προσαρμοσμένο",
    "creator": "δημιουργέ",
    "light": "Φωτεινό",
    "dark": "Σκοτεινό",
    "auto": "Σύστημα",
    "bright": "Φωτεινό και καθαρό",
    "deepBlack": "Σκοτεινός χώρος εργασίας",
    "matchDevice": "Σύμφωνα με τη συσκευή",
    "Black": "Μαύρο",
    "Graphite": "Γραφίτης",
    "Blue": "Μπλε",
    "Yellow": "Κίτρινο",
    "Purple": "Πορφυρό",
    "Lime": "Λαχανί",
    "Orange": "Πορτοκαλί",
    "Red": "Κόκκινο",
    "Red orange": "Κοκκινοπορτοκαλί",
    "Violet": "Μωβ",
    "Gray": "Γκρι",
    "Green yellow": "Κιτρινοπράσινο",
    "Dashboard": "Πίνακας ελέγχου",
    "Open chat": "Άνοιγμα συνομιλίας",
    "Home": "Αρχική",
    "About": "Σχετικά",
    "Pricing": "Τιμές",
    "Models": "Μοντέλα",
    "Sign in": "Σύνδεση",
    "Sign up": "Εγγραφή",
    "New conversation": "Νέα συνομιλία",
    "Chat settings": "Ρυθμίσεις συνομιλίας",
    "Temporary chat": "Προσωρινή συνομιλία",
    "New project": "Νέο έργο",
    "Saved conversations": "Αποθηκευμένες συνομιλίες",
    "Search saved chats": "Αναζήτηση συνομιλιών",
    "Settings": "Ρυθμίσεις",
    "Send message": "Αποστολή μηνύματος",
    "Model": "Μοντέλο",
    "Chatting with": "Συνομιλία με",
    "Online": "Σε σύνδεση",
    "API needed": "Απαιτείται API",
    "Ready": "Έτοιμο",
    "Edit": "Επεξεργασία",
    "Delete": "Διαγραφή",
    "Cancel": "Ακύρωση"
  },
  "bg": {
    "backChat": "Обратно към чата",
    "personalChat": "ЛИЧЕН ЧАТ",
    "settings": "Настройки",
    "appearance": "Изглед",
    "settingsIntro": "Персонализирайте чата си в AllModelAI.",
    "inputField": "ПОЛЕ ЗА ВЪВЕЖДАНЕ",
    "inputTitle": "Цвят на полето за въвеждане",
    "inputDescription": "Променете фона на полето, в което пишете съобщения.",
    "themeTitle": "Изберете тема",
    "themeDescription": "Променете изгледа със запазени виолетови акценти на AllModelAI.",
    "bubbleTitle": "Изберете цвят",
    "bubbleDescription": "Избраният цвят заменя сивия фон на вашите съобщения.",
    "liveResult": "ПРЕГЛЕД",
    "previewTitle": "Преглед на чата",
    "autoSaved": "Промените се запазват автоматично.",
    "previewHello": "Здравейте, {name}! Какво искате да създадете днес?",
    "previewPrompt": "Помогни ми да създам страхотен нов проект",
    "messagePlaceholder": "Съобщение до AllModelAI...",
    "selected": "Избрано",
    "custom": "Персонализиран",
    "creator": "творец",
    "light": "Светла",
    "dark": "Тъмна",
    "auto": "Системна",
    "bright": "Светло и изчистено",
    "deepBlack": "Тъмно работно пространство",
    "matchDevice": "Според устройството",
    "Black": "Черен",
    "Graphite": "Графитен",
    "Blue": "Син",
    "Yellow": "Жълт",
    "Purple": "Пурпурен",
    "Lime": "Лайм",
    "Orange": "Оранжев",
    "Red": "Червен",
    "Red orange": "Червено-оранжев",
    "Violet": "Виолетов",
    "Gray": "Сив",
    "Green yellow": "Жълто-зелен",
    "Dashboard": "Табло",
    "Open chat": "Отвори чата",
    "Home": "Начало",
    "About": "За нас",
    "Pricing": "Цени",
    "Models": "Модели",
    "Sign in": "Вход",
    "Sign up": "Регистрация",
    "New conversation": "Нов разговор",
    "Chat settings": "Настройки на чата",
    "Temporary chat": "Временен чат",
    "New project": "Нов проект",
    "Saved conversations": "Запазени разговори",
    "Search saved chats": "Търсене в чатовете",
    "Settings": "Настройки",
    "Send message": "Изпрати съобщение",
    "Model": "Модел",
    "Chatting with": "Разговор с",
    "Online": "На линия",
    "API needed": "Нужен е API",
    "Ready": "Готово",
    "Edit": "Редактирай",
    "Delete": "Изтрий",
    "Cancel": "Отказ"
  },
  "sk": {
    "backChat": "Späť do chatu",
    "personalChat": "OSOBNÝ CHAT",
    "settings": "Nastavenia",
    "appearance": "Vzhľad",
    "settingsIntro": "Prispôsobte si chat AllModelAI.",
    "inputField": "TEXTOVÉ POLE",
    "inputTitle": "Farba textového poľa",
    "inputDescription": "Zmeňte pozadie poľa, do ktorého píšete správy.",
    "themeTitle": "Vyberte tému",
    "themeDescription": "Zmeňte vzhľad so zachovaním fialových prvkov AllModelAI.",
    "bubbleTitle": "Vyberte farbu",
    "bubbleDescription": "Vybraná farba nahradí sivé pozadie vašich správ.",
    "liveResult": "NÁHĽAD",
    "previewTitle": "Náhľad chatu",
    "autoSaved": "Zmeny sa ukladajú automaticky.",
    "previewHello": "Ahoj, {name}! Čo chcete dnes vytvoriť?",
    "previewPrompt": "Pomôž mi vytvoriť skvelý nový projekt",
    "messagePlaceholder": "Správa pre AllModelAI...",
    "selected": "Vybrané",
    "custom": "Vlastné",
    "creator": "tvorca",
    "light": "Svetlá",
    "dark": "Tmavá",
    "auto": "Systémová",
    "bright": "Svetlo a prehľadne",
    "deepBlack": "Tmavý pracovný priestor",
    "matchDevice": "Podľa zariadenia",
    "Black": "Čierna",
    "Graphite": "Grafitová",
    "Blue": "Modrá",
    "Yellow": "Žltá",
    "Purple": "Purpurová",
    "Lime": "Limetková",
    "Orange": "Oranžová",
    "Red": "Červená",
    "Red orange": "Červenooranžová",
    "Violet": "Fialová",
    "Gray": "Sivá",
    "Green yellow": "Žltozelená",
    "Dashboard": "Prehľad",
    "Open chat": "Otvoriť chat",
    "Home": "Domov",
    "About": "O nás",
    "Pricing": "Ceny",
    "Models": "Modely",
    "Sign in": "Prihlásiť sa",
    "Sign up": "Registrovať sa",
    "New conversation": "Nová konverzácia",
    "Chat settings": "Nastavenia chatu",
    "Temporary chat": "Dočasný chat",
    "New project": "Nový projekt",
    "Saved conversations": "Uložené konverzácie",
    "Search saved chats": "Hľadať konverzácie",
    "Settings": "Nastavenia",
    "Send message": "Odoslať správu",
    "Model": "Model",
    "Chatting with": "Chat s",
    "Online": "Online",
    "API needed": "Vyžaduje API",
    "Ready": "Pripravené",
    "Edit": "Upraviť",
    "Delete": "Vymazať",
    "Cancel": "Zrušiť"
  },
  "sr": {
    "backChat": "Назад на ћаскање",
    "personalChat": "ЛИЧНО ЋАСКАЊЕ",
    "settings": "Подешавања",
    "appearance": "Изглед",
    "settingsIntro": "Прилагодите AllModelAI ћаскање себи.",
    "inputField": "ПОЉЕ ЗА УНОС",
    "inputTitle": "Боја поља за унос",
    "inputDescription": "Промените позадину поља у ком пишете поруке.",
    "themeTitle": "Изаберите тему",
    "themeDescription": "Промените изглед уз љубичасте акценте AllModelAI.",
    "bubbleTitle": "Изаберите боју",
    "bubbleDescription": "Изабрана боја замењује сиву позадину ваших порука.",
    "liveResult": "ПРЕГЛЕД",
    "previewTitle": "Преглед ћаскања",
    "autoSaved": "Промене се аутоматски чувају.",
    "previewHello": "Здраво, {name}! Шта желите да направите данас?",
    "previewPrompt": "Помози ми да направим сјајан нови пројекат",
    "messagePlaceholder": "Порука за AllModelAI...",
    "selected": "Изабрано",
    "custom": "Прилагођено",
    "creator": "ствараоче",
    "light": "Светла",
    "dark": "Тамна",
    "auto": "Системска",
    "bright": "Светло и прегледно",
    "deepBlack": "Тамни радни простор",
    "matchDevice": "Према уређају",
    "Black": "Црна",
    "Graphite": "Графитна",
    "Blue": "Плава",
    "Yellow": "Жута",
    "Purple": "Пурпурна",
    "Lime": "Лимета",
    "Orange": "Наранџаста",
    "Red": "Црвена",
    "Red orange": "Црвенонаранџаста",
    "Violet": "Љубичаста",
    "Gray": "Сива",
    "Green yellow": "Жутозелена",
    "Dashboard": "Контролна табла",
    "Open chat": "Отвори ћаскање",
    "Home": "Почетна",
    "About": "О нама",
    "Pricing": "Цене",
    "Models": "Модели",
    "Sign in": "Пријава",
    "Sign up": "Регистрација",
    "New conversation": "Нови разговор",
    "Chat settings": "Подешавања ћаскања",
    "Temporary chat": "Привремено ћаскање",
    "New project": "Нови пројекат",
    "Saved conversations": "Сачувани разговори",
    "Search saved chats": "Претражи разговоре",
    "Settings": "Подешавања",
    "Send message": "Пошаљи поруку",
    "Model": "Модел",
    "Chatting with": "Ћаскање са",
    "Online": "На мрежи",
    "API needed": "Потребан API",
    "Ready": "Спремно",
    "Edit": "Уреди",
    "Delete": "Обриши",
    "Cancel": "Откажи"
  },
  "da": {
    "backChat": "Tilbage til chat",
    "personalChat": "PERSONLIG CHAT",
    "settings": "Indstillinger",
    "appearance": "Udseende",
    "settingsIntro": "Gør din AllModelAI-chat personlig.",
    "inputField": "TEKSTFELT",
    "inputTitle": "Vælg tekstfeltets farve",
    "inputDescription": "Skift baggrunden i feltet, hvor du skriver beskeder.",
    "themeTitle": "Vælg tema",
    "themeDescription": "Skift udseende med AllModelAI's violette detaljer.",
    "bubbleTitle": "Vælg farve",
    "bubbleDescription": "Den valgte farve erstatter den grå baggrund i dine beskeder.",
    "liveResult": "FORHÅNDSVISNING",
    "previewTitle": "Forhåndsvisning af chat",
    "autoSaved": "Ændringer gemmes automatisk.",
    "previewHello": "Hej, {name}! Hvad vil du skabe i dag?",
    "previewPrompt": "Hjælp mig med at skabe et fantastisk nyt projekt",
    "messagePlaceholder": "Besked til AllModelAI...",
    "selected": "Valgt",
    "custom": "Tilpasset",
    "creator": "skaber",
    "light": "Lys",
    "dark": "Mørk",
    "auto": "System",
    "bright": "Lyst og enkelt",
    "deepBlack": "Mørkt arbejdsområde",
    "matchDevice": "Følg din enhed",
    "Black": "Sort",
    "Graphite": "Grafit",
    "Blue": "Blå",
    "Yellow": "Gul",
    "Purple": "Purpur",
    "Lime": "Lime",
    "Orange": "Orange",
    "Red": "Rød",
    "Red orange": "Rødorange",
    "Violet": "Violet",
    "Gray": "Grå",
    "Green yellow": "Gulgrøn",
    "Dashboard": "Kontrolpanel",
    "Open chat": "Åbn chat",
    "Home": "Hjem",
    "About": "Om os",
    "Pricing": "Priser",
    "Models": "Modeller",
    "Sign in": "Log ind",
    "Sign up": "Opret konto",
    "New conversation": "Ny samtale",
    "Chat settings": "Chatindstillinger",
    "Temporary chat": "Midlertidig chat",
    "New project": "Nyt projekt",
    "Saved conversations": "Gemte samtaler",
    "Search saved chats": "Søg i samtaler",
    "Settings": "Indstillinger",
    "Send message": "Send besked",
    "Model": "Model",
    "Chatting with": "Chatter med",
    "Online": "Online",
    "API needed": "API påkrævet",
    "Ready": "Klar",
    "Edit": "Rediger",
    "Delete": "Slet",
    "Cancel": "Annuller"
  }
};
