// Full interface language list for the Settings page.
// Each entry: display name shown in the dropdown, BCP-47 code, and native label.
export const LANGUAGES = [
  { name: "English", code: "en", native: "English" },
  { name: "Russian", code: "ru", native: "Русский" },
  { name: "Ukrainian", code: "uk", native: "Українська" },
  { name: "Polish", code: "pl", native: "Polski" },
  { name: "German", code: "de", native: "Deutsch" },
  { name: "Finnish", code: "fi", native: "Suomi" },
  { name: "French", code: "fr", native: "Français" },
  { name: "Spanish", code: "es", native: "Español" },
  { name: "Italian", code: "it", native: "Italiano" },
  { name: "Czech", code: "cs", native: "Čeština" },
  { name: "Slovenian", code: "sl", native: "Slovenščina" },
  { name: "Croatian", code: "hr", native: "Hrvatski" },
  { name: "Romanian", code: "ro", native: "Română" },
  { name: "Japanese", code: "ja", native: "日本語" },
  { name: "Chinese", code: "zh", native: "中文（简体）" },
  { name: "Taiwanese Chinese", code: "zh-TW", native: "中文（台灣）" },
  { name: "Indian", code: "hi", native: "हिन्दी" },
  { name: "Portuguese", code: "pt", native: "Português" },
  { name: "Dutch", code: "nl", native: "Nederlands" },
  { name: "Turkish", code: "tr", native: "Türkçe" },
  { name: "Arabic", code: "ar", native: "العربية" },
  { name: "Egyptian Arabic", code: "ar-EG", native: "العربية المصرية" },
  { name: "Greek", code: "el", native: "Ελληνικά" },
  { name: "Bulgarian", code: "bg", native: "Български" },
  { name: "Slovak", code: "sk", native: "Slovenčina" },
];

// UI strings for the Settings page. Languages without a dictionary entry
// fall back to English, so every listed language is always selectable.
const STRINGS = {
  account: {
    en: "Account",
    ru: "Аккаунт",
    uk: "Акаунт",
    pl: "Konto",
    de: "Konto",
    fi: "Tili",
    fr: "Compte",
    es: "Cuenta",
    it: "Account",
    cs: "Účet",
    sl: "Račun",
    hr: "Račun",
    ro: "Cont",
    ja: "アカウント",
    zh: "账户",
    "zh-TW": "帳戶",
    hi: "खाता",
    pt: "Conta",
    nl: "Account",
    tr: "Hesap",
    ar: "الحساب",
    "ar-EG": "الحساب",
    el: "Λογαριασμός",
    bg: "Акаунт",
    sk: "Účet",
  },
  heading: {
    en: "Your workspace profile",
    ru: "Профиль вашего рабочего пространства",
    uk: "Профіль вашого робочого простору",
    pl: "Twój profil przestrzeni roboczej",
    de: "Dein Arbeitsbereich-Profil",
    fi: "Työtilaprofiilisi",
    fr: "Votre profil d’espace de travail",
    es: "Tu perfil del espacio de trabajo",
    it: "Il tuo profilo di lavoro",
    cs: "Váš profil pracovního prostoru",
    sl: "Vaš profil delovnega prostora",
    hr: "Vaš profil radnog prostora",
    ro: "Profilul spațiului tău de lucru",
    ja: "ワークスペースのプロフィール",
    zh: "你的工作区资料",
    "zh-TW": "你的工作區資料",
    hi: "आपकी वर्कस्पेस प्रोफ़ाइल",
    pt: "Seu perfil do espaço de trabalho",
    nl: "Jouw werkruimteprofiel",
    tr: "Çalışma alanı profiliniz",
    ar: "ملف مساحة العمل الخاص بك",
    "ar-EG": "ملف مساحة العمل بتاعتك",
    el: "Το προφίλ του χώρου εργασίας σας",
    bg: "Профил на работното ви пространство",
    sk: "Váš profil pracovného priestoru",
  },
  subtitle: {
    en: "Manage your avatar, identity, language, and account security.",
    ru: "Управляйте аватаром, профилем, языком и безопасностью аккаунта.",
    uk: "Керуйте аватаром, профілем, мовою та безпекою акаунта.",
    pl: "Zarządzaj awatarem, tożsamością, językiem i bezpieczeństwem konta.",
    de: "Verwalte Avatar, Identität, Sprache und Kontosicherheit.",
    fi: "Hallitse avataria, identiteettiä, kieltä ja tilin turvallisuutta.",
    fr: "Gérez votre avatar, votre identité, la langue et la sécurité du compte.",
    es: "Gestiona tu avatar, identidad, idioma y seguridad de la cuenta.",
    it: "Gestisci avatar, identità, lingua e sicurezza dell’account.",
    cs: "Spravujte avatara, identitu, jazyk a zabezpečení účtu.",
    sl: "Upravljajte avatar, identiteto, jezik in varnost računa.",
    hr: "Upravljajte avatarom, identitetom, jezikom i sigurnošću računa.",
    ro: "Gestionează avatarul, identitatea, limba și securitatea contului.",
    ja: "アバター、ID、言語、アカウントのセキュリティを管理します。",
    zh: "管理你的头像、身份、语言和账户安全。",
    "zh-TW": "管理你的頭像、身分、語言和帳戶安全。",
    hi: "अपना अवतार, पहचान, भाषा और खाता सुरक्षा प्रबंधित करें।",
    pt: "Gerencie seu avatar, identidade, idioma e segurança da conta.",
    nl: "Beheer je avatar, identiteit, taal en accountbeveiliging.",
    tr: "Avatarınızı, kimliğinizi, dilinizi ve hesap güvenliğinizi yönetin.",
    ar: "إدارة الصورة الرمزية والهوية واللغة وأمان الحساب.",
    "ar-EG": "إدارة الصورة الرمزية والهوية واللغة وأمان الحساب.",
    el: "Διαχειριστείτε το avatar, την ταυτότητα, τη γλώσσα και την ασφάλεια του λογαριασμού.",
    bg: "Управлявайте аватара, самоличността, езика и сигурността на акаунта.",
    sk: "Spravujte avatara, identitu, jazyk a zabezpečenie účtu.",
  },
  fullName: {
    en: "Full name",
    ru: "Полное имя",
    uk: "Повне ім’я",
    pl: "Imię i nazwisko",
    de: "Vollständiger Name",
    fi: "Koko nimi",
    fr: "Nom complet",
    es: "Nombre completo",
    it: "Nome completo",
    cs: "Celé jméno",
    sl: "Polno ime",
    hr: "Puno ime",
    ro: "Nume complet",
    ja: "氏名",
    zh: "全名",
    "zh-TW": "全名",
    hi: "पूरा नाम",
    pt: "Nome completo",
    nl: "Volledige naam",
    tr: "Ad soyad",
    ar: "الاسم الكامل",
    "ar-EG": "الاسم الكامل",
    el: "Πλήρες όνομα",
    bg: "Пълно име",
    sk: "Celé meno",
  },
  email: {
    en: "Email address",
    ru: "Электронная почта",
    uk: "Електронна пошта",
    pl: "Adres e-mail",
    de: "E-Mail-Adresse",
    fi: "Sähköpostiosoite",
    fr: "Adresse e-mail",
    es: "Correo electrónico",
    it: "Indirizzo email",
    cs: "E-mailová adresa",
    sl: "E-poštni naslov",
    hr: "Adresa e-pošte",
    ro: "Adresă de email",
    ja: "メールアドレス",
    zh: "电子邮箱",
    "zh-TW": "電子郵件",
    hi: "ईमेल पता",
    pt: "Endereço de e-mail",
    nl: "E-mailadres",
    tr: "E-posta adresi",
    ar: "البريد الإلكتروني",
    "ar-EG": "الإيميل",
    el: "Διεύθυνση email",
    bg: "Имейл адрес",
    sk: "E-mailová adresa",
  },
  avatar: {
    en: "Avatar image URL",
    ru: "Ссылка на аватар",
    uk: "Посилання на аватар",
    pl: "Adres URL awatara",
    de: "Avatar-Bild-URL",
    fi: "Avatarin URL-osoite",
    fr: "URL de l’avatar",
    es: "URL de la imagen de avatar",
    it: "URL immagine avatar",
    cs: "URL obrázku avatara",
    sl: "URL slike avatarja",
    hr: "URL slike avatara",
    ro: "URL imagine avatar",
    ja: "アバター画像のURL",
    zh: "头像图片链接",
    "zh-TW": "頭像圖片連結",
    hi: "अवतार छवि URL",
    pt: "URL da imagem do avatar",
    nl: "Avatar-afbeelding URL",
    tr: "Avatar resmi URL’si",
    ar: "رابط صورة الملف الشخصي",
    "ar-EG": "لينك صورة البروفايل",
    el: "URL εικόνας avatar",
    bg: "URL на аватар",
    sk: "URL obrázku avatara",
  },
  language: {
    en: "Interface language",
    ru: "Язык интерфейса",
    uk: "Мова інтерфейсу",
    pl: "Język interfejsu",
    de: "Sprache der Oberfläche",
    fi: "Käyttöliittymän kieli",
    fr: "Langue de l’interface",
    es: "Idioma de la interfaz",
    it: "Lingua dell’interfaccia",
    cs: "Jazyk rozhraní",
    sl: "Jezik vmesnika",
    hr: "Jezik sučelja",
    ro: "Limba interfeței",
    ja: "インターフェースの言語",
    zh: "界面语言",
    "zh-TW": "介面語言",
    hi: "इंटरफ़ेस भाषा",
    pt: "Idioma da interface",
    nl: "Interfacetaal",
    tr: "Arayüz dili",
    ar: "لغة الواجهة",
    "ar-EG": "لغة الواجهة",
    el: "Γλώσσα περιβάλλοντος",
    bg: "Език на интерфейса",
    sk: "Jazyk rozhrania",
  },
  save: {
    en: "Save profile",
    ru: "Сохранить профиль",
    uk: "Зберегти профіль",
    pl: "Zapisz profil",
    de: "Profil speichern",
    fi: "Tallenna profiili",
    fr: "Enregistrer le profil",
    es: "Guardar perfil",
    it: "Salva profilo",
    cs: "Uložit profil",
    sl: "Shrani profil",
    hr: "Spremi profil",
    ro: "Salvează profilul",
    ja: "プロフィールを保存",
    zh: "保存资料",
    "zh-TW": "儲存資料",
    hi: "प्रोफ़ाइल सहेजें",
    pt: "Salvar perfil",
    nl: "Profiel opslaan",
    tr: "Profili kaydet",
    ar: "حفظ الملف الشخصي",
    "ar-EG": "احفظ البروفايل",
    el: "Αποθήκευση προφίλ",
    bg: "Запази профила",
    sk: "Uložiť profil",
  },
  notice: {
    en: "Profile and language preferences saved.",
    ru: "Профиль и язык интерфейса сохранены.",
    uk: "Профіль і мову інтерфейсу збережено.",
    pl: "Zapisano profil i preferencje językowe.",
    de: "Profil und Spracheinstellungen gespeichert.",
    fi: "Profiili ja kieliasetukset tallennettu.",
    fr: "Profil et préférences de langue enregistrés.",
    es: "Perfil y preferencias de idioma guardados.",
    it: "Profilo e preferenze linguistiche salvati.",
    cs: "Profil a jazykové předvolby uloženy.",
    sl: "Profil in jezikovne nastavitve shranjene.",
    hr: "Profil i jezične postavke spremljeni.",
    ro: "Profilul și preferințele de limbă au fost salvate.",
    ja: "プロフィールと言語設定を保存しました。",
    zh: "资料和语言偏好已保存。",
    "zh-TW": "資料和語言偏好已儲存。",
    hi: "प्रोफ़ाइल और भाषा प्राथमिकताएँ सहेजी गईं।",
    pt: "Perfil e preferências de idioma salvos.",
    nl: "Profiel en taalvoorkeuren opgeslagen.",
    tr: "Profil ve dil tercihleri kaydedildi.",
    ar: "تم حفظ الملف الشخصي وتفضيلات اللغة.",
    "ar-EG": "تم حفظ البروفايل وتفضيلات اللغة.",
    el: "Το προφίλ και οι γλωσικές προτιμήσεις αποθηκεύτηκαν.",
    bg: "Профилът и езиковите настройки са запазени.",
    sk: "Profil a jazykové nastavenia boli uložené.",
  },
  confirmTitle: {
    en: "Change interface language?",
    ru: "Изменить язык интерфейса?",
    uk: "Змінити мову інтерфейсу?",
    pl: "Zmienić język interfejsu?",
    de: "Sprache der Oberfläche ändern?",
    fi: "Vaihda käyttöliittymän kieli?",
    fr: "Changer la langue de l’interface ?",
    es: "¿Cambiar el idioma de la interfaz?",
    it: "Cambiare la lingua dell’interfaccia?",
    cs: "Změnit jazyk rozhraní?",
    sl: "Spremenim jezik vmesnika?",
    hr: "Promijeniti jezik sučelja?",
    ro: "Schimbi limba interfeței?",
    ja: "インターフェースの言語を変更しますか？",
    zh: "更改界面语言？",
    "zh-TW": "更改介面語言？",
    hi: "इंटरफ़ेस भाषा बदलें?",
    pt: "Alterar o idioma da interface?",
    nl: "Interfacetaal wijzigen?",
    tr: "Arayüz dili değiştirilsin mi?",
    ar: "تغيير لغة الواجهة؟",
    "ar-EG": "نغير لغة الواجهة؟",
    el: "Να αλλάξει η γλώσσα του περιβάλλοντος;",
    bg: "Промяна на езика на интерфейса?",
    sk: "Zmeniť jazyk rozhrania?",
  },
  confirmText: {
    en: "The site will switch to the selected language. Do you want to continue?",
    ru: "Сайт переключится на выбранный язык. Продолжить?",
    uk: "Сайт перемкнеться на обрану мову. Продовжити?",
    pl: "Strona przełączy się na wybrany język. Czy chcesz kontynuować?",
    de: "Die Seite wechselt zur ausgewählten Sprache. Möchtest du fortfahren?",
    fi: "Sivusto vaihtuu valittuun kieleen. Haluatko jatkaa?",
    fr: "Le site passera dans la langue sélectionnée. Voulez-vous continuer ?",
    es: "El sitio cambiará al idioma seleccionado. ¿Quieres continuar?",
    it: "Il sito passerà alla lingua selezionata. Vuoi continuare?",
    cs: "Stránka se přepne do vybraného jazyka. Chcete pokračovat?",
    sl: "Spletna stran bo preklopila na izbrani jezik. Ali želite nadaljevati?",
    hr: "Stranica će se prebaciti na odabrani jezik. Želite li nastaviti?",
    ro: "Site-ul va comuta la limba selectată. Vrei să continui?",
    ja: "サイトが選択した言語に切り替わります。続行しますか？",
    zh: "网站将切换到所选语言。要继续吗？",
    "zh-TW": "網站將切換到所選語言。要繼續嗎？",
    hi: "साइट चयनित भाषा में बदल जाएगी। क्या आप जारी रखना चाहते हैं?",
    pt: "O site mudará para o idioma selecionado. Deseja continuar?",
    nl: "De site schakelt over naar de geselecteerde taal. Wil je doorgaan?",
    tr: "Site seçilen dile geçecek. Devam etmek istiyor musunuz?",
    ar: "سيتحول الموقع إلى اللغة المحددة. هل تريد المتابعة؟",
    "ar-EG": "الموقع هيتحول للغة المختارة. تحب تكمل؟",
    el: "Ο ιστότοπος θα αλλάξει στην επιλεγμένη γλώσσα. Θέλετε να συνεχίσετε;",
    bg: "Сайтът ще превключи на избрания език. Искате ли да продължите?",
    sk: "Stránka sa prepne do vybraného jazyka. Chcete pokračovať?",
  },
  yes: {
    en: "Yes",
    ru: "Да",
    uk: "Так",
    pl: "Tak",
    de: "Ja",
    fi: "Kyllä",
    fr: "Oui",
    es: "Sí",
    it: "Sì",
    cs: "Ano",
    sl: "Da",
    hr: "Da",
    ro: "Da",
    ja: "はい",
    zh: "是",
    "zh-TW": "是",
    hi: "हाँ",
    pt: "Sim",
    nl: "Ja",
    tr: "Evet",
    ar: "نعم",
    "ar-EG": "أيوه",
    el: "Ναι",
    bg: "Да",
    sk: "Áno",
  },
  no: {
    en: "No",
    ru: "Нет",
    uk: "Ні",
    pl: "Nie",
    de: "Nein",
    fi: "Ei",
    fr: "Non",
    es: "No",
    it: "No",
    cs: "Ne",
    sl: "Ne",
    hr: "Ne",
    ro: "Nu",
    ja: "いいえ",
    zh: "否",
    "zh-TW": "否",
    hi: "नहीं",
    pt: "Não",
    nl: "Nee",
    tr: "Hayır",
    ar: "لا",
    "ar-EG": "لأ",
    el: "Όχι",
    bg: "Не",
    sk: "Nie",
  },
  security: {
    en: "Security",
    ru: "Безопасность",
    uk: "Безпека",
    pl: "Bezpieczeństwo",
    de: "Sicherheit",
    fi: "Tietoturva",
    fr: "Sécurité",
    es: "Seguridad",
    it: "Sicurezza",
    cs: "Zabezpečení",
    sl: "Varnost",
    hr: "Sigurnost",
    ro: "Securitate",
    ja: "セキュリティ",
    zh: "安全",
    "zh-TW": "安全",
    hi: "सुरक्षा",
    pt: "Segurança",
    nl: "Beveiliging",
    tr: "Güvenlik",
    ar: "الأمان",
    "ar-EG": "الأمان",
    el: "Ασφάλεια",
    bg: "Сигурност",
    sk: "Zabezpečenie",
  },
  securityHeading: {
    en: "Keep your account in your control.",
    ru: "Держите аккаунт под своим контролем.",
    uk: "Тримайте акаунт під своїм контролем.",
    pl: "Zachowaj kontrolę nad swoim kontem.",
    de: "Behalte die Kontrolle über dein Konto.",
    fi: "Pidä tilisi hallinnassasi.",
    fr: "Gardez le contrôle de votre compte.",
    es: "Mantén tu cuenta bajo tu control.",
    it: "Mantieni il controllo del tuo account.",
    cs: "Mějte svůj účet pod kontrolou.",
    sl: "Ohranite nadzor nad svojim računom.",
    hr: "Održavajte kontrolu nad svojim računom.",
    ro: "Păstrează controlul contului tău.",
    ja: "アカウントを自分で管理しましょう。",
    zh: "让你的账户始终在你的掌控之中。",
    "zh-TW": "讓你的帳戶始終在你的掌控之中。",
    hi: "अपने खाते पर नियंत्रण रखें।",
    pt: "Mantenha sua conta sob seu controle.",
    nl: "Houd de controle over je account.",
    tr: "Hesabınızın kontrolünü elinizde tutun.",
    ar: "حافظ على التحكم في حسابك.",
    "ar-EG": "خلي حسابك تحت إدارتك.",
    el: "Κρατήστε τον λογαριασμό σας υπό έλεγχο.",
    bg: "Дръжте акаунта си под контрол.",
    sk: "Majte svoj účet pod kontrolou.",
  },
  changePassword: {
    en: "Change password",
    ru: "Изменить пароль",
    uk: "Змінити пароль",
    pl: "Zmień hasło",
    de: "Passwort ändern",
    fi: "Vaihda salasana",
    fr: "Changer le mot de passe",
    es: "Cambiar contraseña",
    it: "Cambia password",
    cs: "Změnit heslo",
    sl: "Spremeni geslo",
    hr: "Promijeni lozinku",
    ro: "Schimbă parola",
    ja: "パスワードを変更",
    zh: "修改密码",
    "zh-TW": "修改密碼",
    hi: "पासवर्ड बदलें",
    pt: "Alterar senha",
    nl: "Wachtwoord wijzigen",
    tr: "Şifreyi değiştir",
    ar: "تغيير كلمة المرور",
    "ar-EG": "غير الباسورد",
    el: "Αλλαγή κωδικού",
    bg: "Промени паролата",
    sk: "Zmeniť heslo",
  },
  logout: {
    en: "Sign out of AllModelAI",
    ru: "Выйти из AllModelAI",
    uk: "Вийти з AllModelAI",
    pl: "Wyloguj się z AllModelAI",
    de: "Aus AllModelAI abmelden",
    fi: "Kirjaudu ulos AllModelAI:sta",
    fr: "Se déconnecter d’AllModelAI",
    es: "Cerrar sesión en AllModelAI",
    it: "Esci da AllModelAI",
    cs: "Odhlásit se z AllModelAI",
    sl: "Odjava iz AllModelAI",
    hr: "Odjava iz AllModelAI",
    ro: "Deconectează-te din AllModelAI",
    ja: "AllModelAIからサインアウト",
    zh: "退出 AllModelAI",
    "zh-TW": "登出 AllModelAI",
    hi: "AllModelAI से साइन आउट करें",
    pt: "Sair do AllModelAI",
    nl: "Afmelden bij AllModelAI",
    tr: "AllModelAI’dan çıkış yap",
    ar: "تسجيل الخروج من AllModelAI",
    "ar-EG": "سجل خروج من AllModelAI",
    el: "Αποσύνδεση από το AllModelAI",
    bg: "Излез от AllModelAI",
    sk: "Odhlásiť sa z AllModelAI",
  },
};

const RTL_CODES = ["ar", "ar-EG"];

export const translate = (key, code) =>
  STRINGS[key]?.[code] || STRINGS[key]?.en || key;

export const isRtlLanguage = (code) => RTL_CODES.includes(code);

// Applies the chosen language to the document and returns its metadata.
export const applyLanguage = (name) => {
  const language = LANGUAGES.find((item) => item.name === name) || LANGUAGES[0];
  document.documentElement.lang = language.code;
  document.documentElement.dir = isRtlLanguage(language.code) ? "rtl" : "ltr";
  return language;
};
