import { useEffect, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import './ProductionCenter.css';
const tabs=[['overview','Overview'],['jobs','Background Jobs'],['search','Global Search'],['notifications','Notifications'],['usage','Usage & Budgets'],['webhooks','Webhooks'],['security','Security & Privacy'],['deployment','Deployment']];
async function api(url,options={}){const response=await fetch(url,{credentials:'include',...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Request failed');return data;}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
export default function ProductionCenter(){
 const saved=sessionStorage.getItem('allmodelai_user'),user=saved?JSON.parse(saved):null;
 const[active,setActive]=useState('overview'),[health,setHealth]=useState(null),[jobs,setJobs]=useState([]),[notifications,setNotifications]=useState([]),[usage,setUsage]=useState(null),[audit,setAudit]=useState([]),[webhooks,setWebhooks]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[query,setQuery]=useState(''),[results,setResults]=useState([]),[jobType,setJobType]=useState('research'),[jobInput,setJobInput]=useState(''),[hook,setHook]=useState({name:'',url:''}),[hookSecret,setHookSecret]=useState('');
 const load=()=>{api('/api/health').then(setHealth).catch(e=>setError(e.message));if(active==='jobs')api('/api/jobs').then(setJobs).catch(e=>setError(e.message));if(active==='notifications')api('/api/notifications').then(setNotifications).catch(e=>setError(e.message));if(active==='usage')api('/api/usage/report').then(setUsage).catch(e=>setError(e.message));if(active==='webhooks')api('/api/webhooks').then(setWebhooks).catch(e=>setError(e.message));if(active==='security')api('/api/audit').then(setAudit).catch(e=>setError(e.message));};
 useEffect(load,[active]);
 useEffect(()=>{if(active!=='jobs')return;const timer=setInterval(()=>api('/api/jobs').then(setJobs).catch(()=>{}),1000);return()=>clearInterval(timer);},[active]);
 if(!user)return <Navigate to="/" replace/>;
 const createJob=async()=>{try{const created=await post('/api/jobs',{type:jobType,payload:{objective:jobInput}});setJobs(items=>[created,...items]);setJobInput('');}catch(e){setError(e.message);}};
 const search=async()=>{try{setResults((await api(`/api/search?q=${encodeURIComponent(query)}`)).results||[]);}catch(e){setError(e.message);}};
 const createWebhook=async event=>{event.preventDefault();try{const created=await post('/api/webhooks',hook);setWebhooks(items=>[created,...items]);setHookSecret(created.secret);setHook({name:'',url:''});}catch(e){setError(e.message);}};
 const exportData=async()=>{const response=await fetch('/api/privacy/export',{credentials:'include'});if(!response.ok)return setError('Could not export account data.');const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='allmodelai-data-export.json';link.click();URL.revokeObjectURL(url);};
 const requestVerification=async()=>{try{await post('/api/auth/verify/request',{});setNotice('Verification request created. Configure Resend delivery in production.');}catch(e){setError(e.message);}};
 return <main className="production-center"><header><Link className="production-brand" to="/dashboard"><span>AI</span>AllModelAI</Link><div><Link to="/skills-hub">Skills</Link><Link to="/chat">Chat</Link></div></header><section className="production-hero"><p>OPERATIONS & RELIABILITY</p><h1>Production Center</h1><span>Run, secure, measure, and monitor AllModelAI from one operational workspace.</span></section><div className="production-layout"><nav>{tabs.map(([key,label])=><button className={active===key?'active':''} onClick={()=>{setActive(key);setError('');setNotice('');}} key={key}>{label}</button>)}</nav><section className="production-panel">{error&&<p className="production-error">{error}</p>}{notice&&<p className="production-notice">{notice}</p>}
 {active==='overview'&&<><h2>Production readiness</h2><div className="health-grid">{health&&Object.entries(health.checks).map(([name,ready])=><article className={ready?'ready':''} key={name}><i/><div><strong>{name}</strong><small>{ready?'Configured':'Needs configuration'}</small></div></article>)}</div><div className="readiness-list">{[['Background processing','Persistent jobs with progress, cancellation, and completion notifications'],['API authentication','Bearer keys with hashing, expiry, budgets, and usage counters'],['Data controls','Search, privacy export, audit trail, and account token flows'],['Observability','Health status, provider configuration, usage, cost, latency, and fallback records']].map(item=><article key={item[0]}><span>✓</span><div><strong>{item[0]}</strong><p>{item[1]}</p></div></article>)}</div></>}
 {active==='jobs'&&<><h2>Background jobs</h2><div className="job-create"><select value={jobType} onChange={e=>setJobType(e.target.value)}>{['research','evaluation','meeting','workflow','document'].map(type=><option key={type}>{type}</option>)}</select><input value={jobInput} onChange={e=>setJobInput(e.target.value)} placeholder="Job objective or input reference"/><button onClick={createJob} disabled={!jobInput.trim()}>Queue job</button></div><div className="job-list">{jobs.map(job=><article key={job.id}><header><strong>{job.type}</strong><span className={job.status}>{job.status}</span></header><div className="progress"><i style={{width:`${job.progress}%`}}/></div><small>{job.stage} · {job.progress}%</small>{['queued','running'].includes(job.status)&&<button onClick={()=>api(`/api/jobs/${job.id}`,{method:'DELETE'}).then(load)}>Cancel</button>}</article>)}</div></>}
 {active==='search'&&<><h2>Global search</h2><div className="global-search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search chats, documents, agents, prompts, meetings, and workflows"/><button onClick={search}>Search</button></div><div className="search-results">{results.map(item=><article key={`${item.type}-${item.id}`}><small>{item.type}</small><h3>{item.name}</h3><p>{item.excerpt}</p></article>)}</div></>}
 {active==='notifications'&&<><h2>Notifications</h2><div className="notification-list">{notifications.map(item=><article className={item.readAt?'read':''} key={item.id}><i/><div><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString()}</small></div>{!item.readAt&&<button onClick={()=>api(`/api/notifications/${item.id}/read`,{method:'PATCH'}).then(()=>setNotifications(items=>items.map(row=>row.id===item.id?{...row,readAt:new Date().toISOString()}:row)))}>Mark read</button>}</article>)}</div></>}
 {active==='usage'&&<><h2>Usage and budgets</h2><div className="usage-grid"><article><small>REQUESTS</small><strong>{usage?.totals.requests||0}</strong></article><article><small>INPUT TOKENS</small><strong>{usage?.totals.inputTokens||0}</strong></article><article><small>OUTPUT TOKENS</small><strong>{usage?.totals.outputTokens||0}</strong></article><article><small>ESTIMATED COST</small><strong>${usage?.totals.estimatedCost||0}</strong></article><article><small>FALLBACKS</small><strong>{usage?.totals.fallbacks||0}</strong></article></div><div className="usage-events">{usage?.events.slice(0,30).map((event,index)=><p key={`${event.createdAt}-${index}`}><span>{event.model}</span><span>{event.inputTokens+event.outputTokens} tokens</span><span>{event.latencyMs} ms</span><b>${event.estimatedCost}</b></p>)}</div></>}
 {active==='webhooks'&&<><h2>Webhook integrations</h2><form className="webhook-form" onSubmit={createWebhook}><input value={hook.name} onChange={e=>setHook({...hook,name:e.target.value})} placeholder="Integration name"/><input value={hook.url} onChange={e=>setHook({...hook,url:e.target.value})} placeholder="https://example.com/allmodelai-hook"/><button>Create webhook</button></form>{hookSecret&&<div className="hook-secret"><strong>Copy the signing secret now</strong><code>{hookSecret}</code><button onClick={()=>navigator.clipboard.writeText(hookSecret)}>Copy</button></div>}<div className="webhook-list">{webhooks.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.url}</small></div><button onClick={()=>api(`/api/webhooks/${item.id}`,{method:'DELETE'}).then(()=>setWebhooks(rows=>rows.filter(row=>row.id!==item.id)))}>Delete</button></article>)}</div></>}
 {active==='security'&&<><h2>Security and privacy</h2><div className="security-actions"><article><h3>Email verification</h3><p>Create a short-lived account verification token.</p><button onClick={requestVerification}>Request verification</button></article><article><h3>Export my data</h3><p>Download conversations and workspace records as JSON.</p><button onClick={exportData}>Download export</button></article><article><h3>Developer access</h3><p>Manage expiring, budget-limited Bearer API keys.</p><Link to="/expansion-hub">Open API manager</Link></article></div><h3>Recent audit events</h3><div className="audit-list">{audit.map(item=><p key={item.id}><strong>{item.action}</strong><span>{item.targetType} {item.targetId}</span><small>{new Date(item.createdAt).toLocaleString()}</small></p>)}</div></>}
 {active==='deployment'&&<><h2>Deployment and infrastructure</h2><div className="deploy-grid">{[['PostgreSQL adapter','Set DATABASE_URL and run migrations before horizontally scaling.'],['Background workers','Move the in-process worker to Redis/BullMQ for multiple instances.'],['Document extraction','Connect PDF/DOCX/OCR workers for binary documents.'],['Monitoring','Set SENTRY_DSN and connect centralized logs and alerts.'],['Email delivery','Set RESEND_API_KEY and EMAIL_FROM for verification and resets.'],['CI/CD','GitHub Actions, Dockerfiles, health checks, and production environment validation are included.']].map(([name,text])=><article key={name}><h3>{name}</h3><p>{text}</p></article>)}</div><pre><code>{`docker compose up --build\n\n# Health probe\ncurl http://localhost:5050/api/health`}</code></pre></>}
 </section></div></main>;
}
